\documentclass[11pt]{article}
\usepackage{amsmath}
\title{Further documentation on code and methods for the mshmm package}
\author{Terry Therneau}
\addtolength{\textwidth}{1in}

\addtolength{\oddsidemargin}{-.5in}
\setlength{\evensidemargin}{\oddsidemargin}
\newcommand{\code}[1]{\texttt{#1}}

%\VignetteIndexEntry{Code detail}
%\VignetteEngine{knitr::knitr}
%\VignetteEncoding{UTF-8}

<<setup, echo=FALSE>>=
library(survival)
library(hmm)

library(knitr)
opts_chunk$set(tidy=FALSE, fig.keep='none',
               fig.path='compete',fig.width=6,fig.height=4)
options(continue="  ", width=60)
pdf.options(pointsize=10) #text in graph about the same as regular text
@ 

\begin{document}
\maketitle

\chapter{Introduction}
\begin{quote}
Kernighan's Law:  ``Everyone knows that debugging is twice as
hard as writing a program in the first place. So if you're as clever as 
you can be when you write it, how will you ever debug it?''
\end{quote}

Work on my own packages has taught me the wisdom of the above. 
Even more to relevant is ``how will you understand the code when you
look at it a year from now''?
Nevertheless, though I try to be simple, there are parts of the code that
are complex.
Even for the 'simpler' parts, 
I find that any time that a new case arises, months or years later that makes me
need to examine my code (and they always do) the end result will be
3x as many additions to the comments as to the code.

This is an attempt to add more context to critical regions.  There are some 
parts of the code where comments just are not enough, one needs figures, tables
and entire paragraphs of text.
I originally undertook this further documentation using Knuth's ``web of code''
idea. I have used the noweb package to intersperse technical
documentation with the source code for the survival package, and the first
drafts of the mshmm package were done that way.
However, despite its advantages, the uptake of noweb by the R community
in general has been nearly nil. 
It is increasingly clear that no future maintainer will continue the 
work, e.g.,
on the survival github page I have yet to recieve a suggested update that
actually
fixed the .Rnw source file instead of the .R file derived from it.  This means
that I can't merge a suggested change automatically, but have to replicate it
myself.

This package does not use noweb.
Instead, this latex document will contain an index, and the R
source code has comments pointing to the index of the code vignette.
(The R code can't refer to ``figure 3.2 in the vignette'' because figure
numbers and labels change).


\section{Parsing the formulas}
\subsection{Overview}
Here is the transition matrix for a moderately complex model.
We have two latent amyloisis states, and 3 latent cognitive states.

<<qplus>>=
states <- c(outer(paste0("A", 0:1), paste0("C", 0:2), paste0), "death")
statedata <- data.frame(state= states,
                        A=c(0,1, 0,1, 0,1, 2),
                        N=c(0,0, 1,1, 2,2, NA),
                        D=c(0,0, 0,0 ,0,0, 1))
statedata
qmat <- qplus(statedata, death= "death")
statefig(cbind(2,2,2,1), qmat, alty=rep(1:2, c(7,8)))
@ 

And here is an example call using this data.
<<echo=TRUE, eval=FALSE>>=
mfit <- hmm(list(Surv(time, death) ~ male,
                 0:death ~ iage
                 A(0):A(1) ~ apoe + ns(iage,4)/ common,
                 N(0):N1(1) + N(1):N(2) ~ iage + cmc),
            marker = list(dx ~ N/ multinomial(pattern= pmat),
                           memory~ N + practice/ gaussian,
                           centiloid + sqrt(p.tau181) ~ A(1:2) /gaussian)
            data= dementia, id=ptnum, qmatrix = qmat, 
            statedata = statedata)
@ 

The first argument of hmm is \code{formula}, as with most modeling functions,
and in this case it is a list. 
The 13 separate transitions (arrows) may each have different predictors.
The first element of the list is the default formula, later elements
augment this for specified transitons.
The marker argument is also a list that maps each marker to the state(s)
for which it is a read-out.

The first goal in parsing this is to create an overall master formula:
Surv(time, death) ~ male + iage + apoe + ns(iage,4) + cmc + dx + memory + 
practice + centiloid + sqrt(p.tau181). This will be used as
an argument to the model.frame() call use to create the analysis data set.
This master formula isn't used again.

After dealing with missing values, the code will
use model.reponse() to obtain y, pull the 3 marker variables into a
\code{ymarker} matrix of responses, and create a second master formula,
without the markers, as the argument to model.matrix.

Given the X matrix and it terms and assign attributes, we can the tackle the
second stage of parsing, and create the tmap and cmap matrices.
The tmap matrix has a row per term, so we need the terms first.

\subsection{First pass}
Step 1 is to break the formula into parts, using \code{parsecovar1} for
the formula and \code{parsemarker1} for the marker list.
  The first formula is
the default formula \code{dformula}, the rest become a 3 component list
containing the left sides, the right sides and the options.
The marker argument becomes a list with 4 components of state, marker,
formula and options.
From this we can create a single master formula that is used to drive 
the model.frame process, which ensures that all of the variables we need
will be found in the model frame. In this case the master formula would have
\code{Surv(time, death)} on the left, and
\code{male + apoe + cmc + male*apoe + years + dx + memory + practice}
on the right.  The terms structure of that master formula is very useful.
Further processing of the formulas is deferred until after the model frame
is in hand.

What if the default formula has sex, and
one of the sub-formulas has -sex in it? 
If we just paste together the character form, then if -sex were in the very last
formula, then sex would not appear in the data frame, and formulas that used
sex would fail.
But we paste together terms.labels attributes, which only contain the terms that
do appear (no - signs) and all is well.
One special case would be if sex appeared in the default formula, and then was
removed from every transition in the formula list: sex would then be in the
data frame though we don't need it. If sex also had missing values you could lose
rows we don't intend to.
This error requires almost malicous intent on the part of the user, so we have
decided not to worry about it.

Should we walk the parse tree of the formula, or convert it to character and use
string manipulations?  The latter looks promising until you see a fragment 
like this:
\code{entry:death + dementia:death~ sex + ns(iage, df=4) / common},
whose parse tree is shown in figure \ref{figparse}.
Walking the parse tree is a bit more subtle, but we then can take advantage of 
all the knowledge built into the R parser.
A formula is a 3 element list of ``~'', leftside, rightside, or 2 elements if 
it has only a right hand side.  Legal ones for hmm have both left and right.

\begin{figure}
<<R, echo=FALSE>>= 
opar <- par(mar=c(1,1,1,1))
ptplot(entry:death + dementia:death~ sex + ns(iage, df=4) / common)
par(opar)
@
  \caption{The parse tree for the formula 
    \code{entry:death + dementia:death~ sex + ns(iage, df=4) / common)}.
    At branches we show the class followed by the value.}
  \label{figparse}
\end{figure}

<<R, ptree>>=
test <- cu:death + dem:death ~ x1 + x2
length(test)
test[[1]]
test[[2]]
test[[3]]

length(test[[3]])
test[[3]][[1]]
test[[3]][[2]]
@ 

Extrapolating from the above, the way one walks a parse tree is to simply
step along the nested list.
Nested functions can be quite efficient, and look simple, but also be
difficult to get ones arms around, and an absolute bear to debug.
Here is a simple function from the parsemarker.R code, whose job it is to
pluck off the leftmost object in the right hand side of a formula, and
return a list containing that object as the first item, and the updated formula
without that item as the second.  
Here is a listing of the function, along with a test formula.
<<r, >>=
grableft <- function(x) {
    if (is.call(x) && x[[1]]== as.name('+')) {
        if (is.name(x[[2]])) list(x[[2]], x[[3]])
        else {
            temp <- grableft(x[[2]])
            x[[2]] <- temp[[2]]
            list(temp[[1]], x)
        }
    } else stop("state identifier can only be followed by '+'")
}

test <- (~ N + practice+ sex)[[2]]
ptplot(test)
@ 

The execution sequence looks like below, each indent a recursive call to 
grableft, executed statements listed seqentially within the indent.
\begin{itemize}
  \item grableft(N + practice + sex)
    \begin{itemize}
      \item temp <- grableft(N + practice)  (+ N practice)
        \begin{itemize}
          \item list(N, practice)
        \end{itemize}
      \item x[[2]] <- temp[[2]] (x = + practice sex)
      \item list(N, practice + sex)
    \end{itemize}
\end{itemize}

One useful ideas is to use the terms() function to much of the work for
us. For the right hand size the resulting \code{term.names} attribute nicely
picks off the variables that should be pasted together to make a master
formula from a list of formulas, which is exactly how we create the master
formula.
However, it doesn't work for something like 1:2 on the left hand side of
a formula, since '1' and '2' are not valid variable names. 
More fatally, terms() considers A:B and B:A to be the same, which means that
both never appear in the same terms object, and which label is used can
be rather arbitrary. In truth an
A$\rightarrow$B transition is not the same as B$\rightarrow$A, and we might
even have both in the same formula line.
Nor does terms() work for splitting off the options, which involves finding the 
last '/' on the line.  So for many of the operations we will need to
walk the tree. 

In the code, 
the parsecovar1 routine accepts the list of formulas and returns 3 lists:
left hand sides, right hand sides (less options), and options, which are the
things like ``common'' and ``init'' that live after the last /.
The list of right hand sides is used to build the master formula,
the left hand sides and the options are dealt with in pass 2.
which is used to create the model frame and the X matrix.
The left hand sides information and the options are dealt with in pass 2.

\paragraph{Markers}
The markers formulas can be a bit more complex.
Here are some valid ones
\begin{itemize}
  \item \code{A(0:1):log(amyloid) + A(0:1):log(tau) ~1 / gaussian}
  \item \code{N:pzmemory ~ 1 / gaussian}
  \item \code{N:pzmemory ~ practice / gaussian(param='mean')/ common}
  \item \code{state:dx ~1   / multinomial(pattern = pmat)}
\end{itemize}

I would not recommend putting two markers on one line, but it is allowed
should someone want to force common paramenters.  I can't think of a use
case for this, and will likely not mention it in the documentation.
Having two lines for a marker is necessary for the case above, where we
want to force the practice effect to be common, but not the means.

The parsemarker1 routine separates out the options (a list with one
element per formula), the right hand side less the options (most of which
are ~1 formulas), the vector of marker names, and a list with the
state information for each marker:state pair.  Last is a vector giving
the number of markers per line, so that the parsemarker2 routine can
match markers to formulas.
For these creation of the model frame, hmm will require the marker variables,
log(amyloid), log(tau), pzmemory, and dx,
along with any further covariates on the right hand side, 'practice' in
this case. Everything else is passed forward.

\subsection{ Second pass}
\paragraph{Transitions}
The left hand side of each formula specifies the set of transitions to which
the covariates apply, and is more complex.
Say instance that we had 7 states and the following statedata
data set.
\begin{center}
  \begin{tabular}{cccc}
    state & A&  N&  D \\ \hline 
    A0N0 &  0&  0 & 0\\
    A1N0 &  1&  0 & 0\\
    A0N1 &  0&  1 & 0\\
    A1N1 &  1&  1 & 0\\
    A0N2 &  0&  2 & 0\\
    A1N2 &  1&  2 & 0\\
    Death&  2 & NA& 1 
\end{tabular}
\end{center}

  Here are some valid transitions
\begin{enumerate}
   \item 0:state('Death'),   any transition to the death state
   \item 0:Death, same as above
   \item A0N0:D(0), a transition from A0N0, but not to death
   \item A(0):A(1), any transition that starts with A=0 and ends with A=1
   \item N(0):N(1,2) + N(1):N(2), an upward change of N
   \item A0N0:c('A0N1','A1N0'); a pair of states
   \item (1:3 + 2:3):4;  we can refer to states by number
   \item c(1,2):3 is legal, (1,2):3 is not; the second flagged as invalid
     by the R parser
\end{enumerate}

For the second step of parsing, what we need from parsecovar2
is the coefficient map \code{cmap}. 
It has one row for each covariate, one column for each transition, and contains
the index of the relevant coefficient(s) for the linear predictor of the
given transition; 0 if this particular covariate is not relevant to the
transition.
Given \code{cmap}, there is a simple transformation from
the total coefficent vector \code{coef} to a matrix form B
with one column per transition, see the coef.to.B function. 
B will have 0 wherever cmap is zero, and \verbzX%*% Bz gives the
matrix of linear predictors; one row per observation, one column per transition.
Each row is used to fill in elements of $H$, which is used to create transtion
probability matrices $P_i(t) = exp(H)$.

A matrix \code{tmap} with one row per term is an intermediate step: a factor 
or ns() term has multiple coefficients.  The term() function (and users) work
with terms, the assign attribute of the X matrix translates this to 
coefficients.

not yet done, document the details of parsecovar2

\paragraph{Markers}
To understand the role of markers, first write out the likelihood.
Assume there were three markers a, b, c, then the likelihood 
for any given subject can be written as
$$
\pi_0 \left[D_a(y_{1a}, t_1)D_b(y_{1b}t_1) D_c(y_{1c}, t_1)\right] P(t_1,t_2) 
\left[D_a(y_{2a},t_2) D_b(y_{2b},t_2) D_c(y_{2c},t_2)) \right] P(t_2,t_3)  \ldots, 
\left[D_a(y_{na},t_n) D_b(y_{nb},t_n) D_c(y_{nc}, t_n) \right]
$$
with $pi$ the initial distribution over states,
$P$ an nstate by nstate transition matrix, and $D$ a diagnoal response matrix
for each marker.
Each row of $XB$ for a subject generates a transition matrix $P$ except the
last, and row of data with markers generates a set of $D$ matrices, 
otherwise $D$ is the identity matrix.

For the markers it is useful to think about the compuation piecewise.
\begin{enumerate}
  \item For many data sets, in particular those which treat current age as a
    time-dependent covariate, the will be many rows of data which only update
    age, most rows won't corrspond to time points at which markers were 
    measured.  Even for data rows that 
    correspond to a patient visit, not every marker will may measured on every
    subject. 
  \item The $D$ matrix for a given subject $i$, time $j$ and marker $m$
    has diagonal element
    $D_{kk} = f(y_{ijm}; \eta_{ijk1}, \eta_{ijk2}, \ldots)$ where $k$ is the state,
    $y$ is the observed response for the marker
    and 1, 2, etc are the parameters of the distribution, e.g., mean and std.
  \item Diagonal element $k$ of $D$ is the likelihood of seeing this particular
    $y$, given that the true state is $k$.
  \item The code creates a response function for each state:marker pair.
    As input it will have the vector of $m$ observed values for the marker 
    (missings excluded) and a matrix of $\eta$ values with $m$ rows and the
    appropriate number of columns, along with control values determined at
    setup.  It returns a matrix with a row per state and $m$ columns, each
    column contains the elements of one of the D matrices.
\end{enumerate}

The parsemarker2 routine will need to generate a list containing the response
function for each marker, along with the index of which columns of the cmap
matrix map into each, along with cmap.

Look again at the marker equations:
\begin{itemize}
  \item \code{A(0:1):log(amyloid) + A(0:1):log(tau) ~ 1 / gaussian}
  \item \code{N:pzmemory ~ 1/ logisitic}
  \item \code{N:pzmemory ~ practice / gaussian(param='mean')}
  \item \code{state:dx ~ 1 / multinomial(pattern = pmat)}
\end{itemize}

\begin{itemize}
 \item The first thing is that in an HMM the value of a marker is
   predicted from the state, not vice versa, the ordering N:pzmemory is
   intentional. Having the mean as the only predictor is common.
   A(0:1) above says to use the ``A'' column of the statedata data set.
   Subjects in the A0N0, A0N1 and A0N2 states are assumed to share the same 
   mean and std for their amyloid values. 
   The A=3 row of statedata is the death state; there is no mean or std since
   amyloid PET is not performed on a corpse.
 \item The specified distribution will have multiple parameters, the mean
   and std for a Gaussian for example. As in lines 2 and 3 we can specify
   different formulae for the mean and std, mean memory scores are influenced 
   both by the true state and a practice effect, but we assumed no practice
   effect for the std.  The default is to use the same set of predictors for
   both.
 \item The multinomial distribution requires a pattern matrix which specifies
   the mapping between linear predictors and states.
\end{itemize}

For a gaussian distribution there will be 2 parameters per peak, the mean 
and std. Likewise for logistic and gamma.
The number of peaks is taken from the relevant column of statedata: 2 for A, 
3 for N.  The total number of linear predictors for the A:log(amyloid) mapping
will be 4, with names of ``A0:log(amyoid).mean'', ``A0:log(amyloid).log(std)'',
``A2:log(amyoid).mean'' and  ``A1:log(amyloid).log(std)''.  
The response function will be passed an $m$ by 4 matrix of linear predictors,
where $m$ is the number of non-missing values of log(amyloid),
It will return a nstate=7 by $m$ matrix of probabilities, the last (death)
row of which is 0.  
The associated cmap will have 4 columns with nonzero elements in the rows
rows for the intercept (4 columns) an and practice (2 columns).

A multinomial outcome will have labels that are not quite as obvious. Say that
we have the following pattern matrix.
<<pattern>>=
pmat <- rbind(c(-1, 1, 0), c(2, -1, 3), c(0, 4, -1))
dimnames(pmat) <- list(true=c("C0", "C1", "C2"), 
                       obs =c("CU", "MCI", "dementia"))
pmat
@ 

This has declared that we will never mistakenly apply a ``dementia'' label to
someone who is in the C0 state, nor a ``cognitively unimpaired'' label to
one who is in dementia. Thus the multinomial distribution for true C0 has
only 1 parameter (it is effectively binomial) and likewise for C2, 
C1 has 2 parameters.
The -1 codes the cell that should be thought of as the reference.
In this case labels will be ``N0:dx.p1'', ``N0:dx.p2'', etc. Three N states
by 4 paramters. There is not a nice 1:1 relationship between any parameter and 
the entries in the probability matrix. 
It is possible, though I would find it odd, to force parameters to be
equal.  A second row of 2, -1, 2 for instance would force the probability of
classifiying true C1 as unimpaired or demented to be identical.

We handle this with a function for each distribution.
\begin{itemize}
 \item The function is called with a statedata list (created by parsemarker1)
   which has the name of the column, ( e.g. 'A'), the label for for each peak
   each peak (0, 1), and the expansion of this to the 7 states (1,2,1,2,1,2,0);
   factor labels of the marker, and any user specified arguments 
   (\code{param='mean'}).
 \item This function creates a response function, with default parameters set
   properly, and returns it.
 \item It also creates a matrix of labels, a row for state and parameter,
   one column for each linear predictor it will require.
 \item Optional check and formatting function are also returned. The first
   is called as a data check, a beta distribution for instance expect the
   marker to be between 0 and 1.  The second is used to format results, e.g.,
   the misclassification matrix for a multinomial or
   log(std) to std for gaussian.
 \item The compuatation function recieves the vector y and the matrix of linear
   predictors. It returns a nstate x m matrix of density values.
\end{itemize}

The user can write either \code{gaussian} or \code{gaussian(param=std)}, as
an example. The parsecovar routine picks up the name, puts the parameters in
a list along with the state data, and calls the initialzation function. The
fact that the code uses log(std) is something the user need not even know.

One important foonote is the use of A(0:1) in the formula, which says that there
is no gaussian peak for death.  For N the use of NA for death accomplishes the
same thing.
If death is the true state, there is no tau measurement, and the associated D 
matrix has a 0 in the last position. 
Put another way, having a tau measurement means that you weren't dead.

One thing that confused me in this process was that if a model has at least
one categorical predictor, it is possible to bundle the death state into
that outcome, e.g., treat CU/MCI/dementia/death as the categorical outcome.
That is how some examples in the msm documentation are set up. One can then
set the pattern matrix for the multinomial to have a final row ``true death''
and final colum ``observed death'' that are both 0 except for a lower right
corner of 1.  In the hmm function death is handled via the status variable
instead, and adding a death to the in-office-diagnosis would be a mistake.
(This came to a head the first time I had an msm model without any categorical
markers and wondered ``where do I put death''.)
In an hmm, we computation at any given time point purposely does any exact
state last, to accomodate the admittedly strange case of a subject who had a 
clinical evaluation in the morning and died in the afternoon.

The code in parsemarker2 has some non-obvious features. 
The fact that I allow two state:marker pairs in a single formula means that
the vector of markers will be longer than the list of formulas or options.
This leads to multiple indexing nusances.
This was do to allow the /common option to apply across two state:marker pairs
in the same way that it does in the formula section.
I do currently have any use case for this, but expect that someone will.

This is perhapse the most perplexing bit of code:
<<echo=TRUE, eval=FALSE>>=
mindex <- match(marker, umarker)
for (i in 1:nform) {
    j <- findex[[i]] # index of markers on this formula line
    k <- unlist(lapply(eindex[mindex[j]], function(x)
        x[rlist[[j[1]]]$subset]))
    # k is the set of columns of cmap, to which this formula applies
    dtemp <- dmap[,k]
    if (hascommon(parse1$options[[i]])) dtemp <- dtemp[,1]
@ 

Use our earlier example
<<echo=TRUE, eval=FALSE>>=
 marker = list(A(0:1):log(amyloid) + A(0:1):log(tau) ~1 / gaussian,
               N:pzmemory ~ 1 / gaussian,
               N:pzmemory ~ practice / gaussian(param='mean')/ common,
               state:dx ~1   / multinomial(pattern = pmat))
@
The findex variable will be list(c(1,2), 3, 4, 5).
The eindex list has one element for each unique marker, and
will denote linear predictor columns of 1:4 for amyloid, 5:8 for
tau, 9:14 for pzmemory, and 15:19 for dx. 
The rlist object has an element for each marker, in the order of the markers,
but all markers in a single formula will share the same rlist. 
For formula number 3, j=4, rlist[[4]]['subset'] = c(1,3), which are the two
mean parameters. Only those linear predictors use the practice variable. 



\section{Response functions}
\subsection{Continuous}
\index{response function: gaussian}
For the derivative of a normal use the identity that
$df(x)/dx = f(x) d(log(f))/dx$.  The second term on the right is easier.
For a normal
\begin{align*}
  f(x) &= \frac{1}{\sqrt{2\pi} \sigma} e^{-.5\left((x-\mu)/\sigma\right)^2} \\
  \log(f) &= -.5\log(2\pi) - \log(\sigma) - .5\left((x-\mu)/\sigma\right)^2 \\
  \frac{\partial log(f)}{\partial \eta_1} &= 
       \frac{\partial log(f)}{\partial\mu}\frac{\partial \mu}{\partial \eta_1}\\
      &(x-\mu)/\sigma^2 1 \\
  \frac{\partial log(f)}{\partial \eta_2} &= 
       \frac{\partial log(f)}{\partial\sigma} 
       \frac{\partial \sigma}{\partial \eta_2}\\
     & = \left(-1/\sigma + \frac{(x-\mu)^2}{\sigma^3} \right) \sigma \\
     & = -1 + \left(\frac(x-\mu)}{sigma}\right)^2
\end{align*}\

Since $\sigma = \exp(\eta_2)$ the derivative wrt $\eta_2$ is $\sigma$ times the
derivative wrt $\sigma$.

The code is set up such that the hmmgauss routine returns the derivative of
each state's prediction with respect to the parameters
$\eta_1$ (mean) and $\eta_2$ (log sigma) for that state. The parent routine,
which has the key for $\eta$ as a function of the coefficients, then finishes
the derivative for subject $i$ using the chain rule 
\begin{align*}
 \frac{\partial L}{\partial \beta} &= \sum_j \frac{\partial L}{\partial \eta_j}
   \frac{\partial \eta_j}{\partial \beta} \\
 &= \sum_j \frac{\partial L}{\partial \eta_j} X_{ij}
\end{align*}

\index{response function: logistic}
The logistic distribtion is parameterized by mean and scale $(/mu, s)$ where
the $s= \sigma \sqrt(3)/pi$, or conversely $\sigma^2= s^2\pi^2/3$. 
We parameterize by mean and std for the user.
\begin{align*}
  \log(f) = -log(s) +(y-\mu)/s - log(1+ e^{(y-\mu)/s}) \\
  \frac{\partial log(f)}{\partial \mu} &= -\frac{\mu}{s} \left[
    1+ \frac{ e^{(y-\mu)/s}}{1+  e^{(y-\mu)/s}} \right] \\
  \frac{\partial log(f)}{\partial s} &= -1/s -(y-\mu)/s^2\left[ 
    1+ \frac{ e^{(y-\mu)/s}}{1+  e^{(y-\mu)/s}} \right] \\
   \frac{\partial log(f)}{\partial \eta} &= \frac{\partial log(f)}{\partial s}
                    \frac{\partial{s}}{\partial \eta} \\
        &= \frac{\partial log(f)}{\partial s} s             
\end{align*}

\index{response function: beta}
The beta distribution is paramerized by shapes $a=\exp(eta_1)$ and 
$b= exp(\eta_2)$, and $0\le y \le 1$ must be between 0 and 1.
The mean is $\mu= a/(a+b)$ and the variance is $\sigma^2= ab/[(a+b)^2(a+b+1)]$,
so though it might be nice to think in terms of mean and variance for the
user, doing so directly is impractical.
The function and derivatives don't play nicely on log scale for $y$ of 
exactly 0 or 1, one end up with 0* infinity.
R has the \code{psi} function, which is the derivative of $\log(\Gamma(y))$.
Think of $f(y,a,b) = g(a,b)h(y,a,b)$ where $g$ are the $\Gamma$ terms, and use
the identity $dg/da = g d(log(g))/da$ along with the product rule.

\begin{align*}
  f(y) &= \frac{\Gamma(a+b)}{\Gamma(a)\Gamma(b)} y^{a-1}(1-y)^{b-1} \\
  \frac{\partial g(y,a,b)}{\partial a} h(y,a,b) &=  f(y,a,b))
                   \left[\psi(a+b)- \psi(a)] \\
   \frac{\partial g(y,a,b)}{\partial b} h(y,a,b) &=  f(y,a,b))
                   \left[\psi(a+b)- \psi(b)] \\
   g(y,a,b) \frac{partial h(y,a,b)}{\partial a) = g(y,a,b)
     \left[(a-1)y^{a-2} (1-y)^{b-1} \right]
   g(y,a,b) \frac{partial h(y,a,b)}{\partial b) = -g(y,a,b)
     \left[y^{a-1} (b-1)(1-y)^{b-2} \right]
  \frac{\partial f}{\partial \eta_1} &= a \left[
     \frac{\partial g(y,a,b)}{\partial a} h(y,a,b) + 
      g(y,a,b) \frac{partial h(y,a,b)}{\partial a) \right]
     \frac{\partial f}{\partial a} \\
  \frac{\partial f}{\partial \eta_2} &= b   \left[
     \frac{\partial g(y,a,b)}{\partial b} h(y,a,b) + 
      g(y,a,b) \frac{partial h(y,a,b)}{\partial b) \right]
\end{align*}

\index{response function: multinomial}

If the marker variable is categorical, then we model the response as a
multinomial.  If there are $m$ possible outcomes, then for each true state
$s$ we have probabilitites $p_{s1}$, $p_{s2}$, \ldots, $p_{sm}$, with the
natrual constraints the probabilities lie between 0 and 1, and that they sum
to 1.
One of the easiest ways to do this is 
\begin{equation*}
  p_{sj} =  e^{\eta_{sj}}/\sum_{k=1}^m e^{\eta_{sk}}
\end{equation*}
where wlog $\eta_{s1}$ is assumed to be 0. There will be $s(k-1)$ linear 
predictors in total, $k-1$ for each state.
Derivatives for any given state $s$ are (suppressing the $s$ subsript)
\begin{align*}
  \frac{\partial p_j}{\eta_k} &= 
       e^{\eta_j}\left[\frac{I_{(j=k)}}{\sum_k e^{\eta_{k}}} -
        \frac{e^{\eta_{j}}}{\left(\sum_k e^{\eta_{ik}}\right)^2} \right] \\
       &= \left\{ \begin{array}{rl}
           p_{j}(1-p_{j}) & j=k \\
           -p_{j}p_{k} & j\ne k  \end{array} \right. \\
\end{align*} 
which is a standard multinomial variance matrix, one for each true state.
The derivative wrt $\eta_1$ is 0 by definition, so column 1 of the 
matrix will be discrared, retaining dervative wrt $\eta_2$, $\eta_3$, etc. 
Nevertheless the values in row 1, which make use of $p_1$, are correct.

Recognize that there is no grand biologic rationale behind this transformation.
Using $\exp(\eta)$ terms in this no more than a simple computational strategy
that yields 3 important properties: $\eta$ is unconstrained, $0 <p<1$ and
$\sum_k p_{sk}=1$; and is one of the simpler ways to do so. 
 Do not fall into the trap of overinterpeting individual
terms or coefficients in the linear predictor.
Another trap, which this author fell into, is to confuse the first derivative
matrix above.  The formula looks just like the multinomial variance, making
for a compact and easy to remember compuation, but the result is just a first
derivative. It has the simple additivity properties of first derivatives, i.e.,
the derivative of $\phat_1 + 2\phat_2$ is column 1 + 2 times column 2 of
the first derivative matrix. Don't start thinking about covariance.

The multinomial routine in the code also allows for a pattern matrix, zero
values in the matrix mark state/marker values that never occur in practice.
This may be do to a priori knowlege, or practical experience: if this pair is
never observed to happen the maximun for the $\eta$ will be $-\infty$ and there
is not good reason to waste time and energy estimating such a parameter.



\section{Rescaling and constraints}
The code rescales X internally, largely to avoid issues with any extreme
X values. This is possible if each column if every linear predictor has
an intercept term. The first column of $X$ is an intercept, and let
$m_j$ be the mean and $s_j$ the scale for column $j$, with $m_1=0$ and 
$s_1$= 1
Then 
\begin{align*}
 Z_{ij}  &= \left(X_{ij}- m_i)/s_i \\
 Z &= XT \\
 T_{ij}&= \left\{ \begin{array}{cc}
       1 & j=1 \\
       -m_j/s_j & i=1, j>1 \\
       1/s_j    & i=j, j>1  \end{array} \\
 T^{-1}_{ij} &=  \left\{ \begin{array}{cc}
            s_j & i=j \\
            m_j & i=1, j>1 \end{array}
\end{align*}



   
If B is the matrix of coefficients, $XB = (XT)(T^$


\section{Likelihood}
The likelihood for a subject has 3 parts: initial value, transition
matrices, and observation matrices, with I will call $p(0)$, $P(s,t)$
and $D(t)$.
Let $t_{i1}, t_{i2}, ...$ be the time points for subject $i$,
$y(t_{i1}, y(t_{i2}), ...$ the observed state, 0 for censored, and $Q$ the 0/1
matrix of valid transitions. 

\subsection{Simple interval censored}
For the formulas below we will suppress the $i$ subscript, as the likelihood
can be computed separately for each subject. 
The pair $(t_m, t_{m+1})$ is an arbitrary interval for a subject.
$B$ is a matrix of coefficients, one column per transition probability,
which is one per non-zero element of $Q$, the \code{qmatrix} argument.
The \code{cmap} matrix maps elements of $B$ to the parameters to be
maximized.

\begin{align}
  p_j(t_{1}) &= I{y(t_1) = j} \nolabel \\
  R_{jk}(t) &= \left\{ \begin{array}{cc}
    -\sum_{k \ne j} -R_{jk}  & j=k \label{rmat1} \\
    e^{\eta_{jk}(t)}       &  j \ne k, Q_{jk}>0  \label{rmat2}\\
    0                &  j \ne k, Q_{jk} =0 \nolabel \end{array} \right. \\
  \eta &= XB  \nolabel \\
  P(t_m, t_{m+1}) &= e^{[t_{m+1} - t_m]R(t_m)}  \label{pmat1} \\
  D_{jk}(t_m)= \left\{ \begin{array}{cc}
    1 & y(t_m) =j, j \ne \mbox{exact}   \label{dmat1a} \\
    1 & y(t_m)= 0, j \ne \mbox{death}   \label{dmat1b} \\
    R_{jk}(t_{m-1}) &  y(t_m)= k, k = \mbox{exact}  \label{dmat2} \\
    0 & \rm{otherwise} \nolabel \end{array} \right.
\end{align}

The overall probability vector for the subject is
\begin{equation*}
  p = p(t_1) P(t_1, t_2) D(t_2) P(t_2, t_3) D(t_3) \ldots 
\end{equation*}
The starting vector matches the first observation, it is an error for the
first obs to be censored.
The $R$ matrix depends on the matrix of linear predictors, $\beta$ will have
one column for each non-zero element of $Q$.
In the code we use alpha rather than p, an artifact of the notation used
in the msm package.

An exact state is one whose entry time is observed exactly, the 
\code{exact} option in the code, the most common case is death.
For a observed state that is not exact, $D$ is a diagonal matrix with 
a single 1 on the diagonal corresponding to the observed state.
For an exactly observed state, we multiply by the transition rates just 
before the event occurred, hence the $m-1$.  The covariates just before
the event, which are what we want, will equal the most recent prior
measurment.
For a censored obs, the subject is known tobe in any state *except* death
at that time, where for this rule ``death''
is any exactly observed absorbing state, which is almost always death.
One can have an exact state that is not absorbing, an example is surgical
resection of a section of inflamed bowel in Crohn's disease.
The msm package also allows for a state with known exit time, but I have not
yet found a need for this.

For a non-zero element of $q_{jk}$ of $Q$, the derivative of $R_{jk}$ with
respect to $\eta_{jk}$ is $R_{jk}$, and 0 for all other elements of $R$.
The derivative of $P$ with respect to $\eta_{jk}$ is more complex, since each
element of $P$ depends on all the elements of $R$.
This is returned by the pade routine as a matrix of dimension 
(nstate, nstate, q) where $q$ is the number of non-zero elements of $Q$.
This is \code{ptemp\$dmat} in the hmm2 routine. 
From the product rule
\begin{equation}
  \frac{\partial p(t)P(t,s)}{\partial \eta_q} &= 
  \frac{\partial p(t)}{\partial \eta_q} P(t,s) + 
  p(t)\frac{\partial P(t,s)}{\partial \eta_q} \label{productderiv}
\end{equation}
To prove this simply write out the matrix product as a sum of terms, apply
the product rule for derivatives to each term, and reassemble the result.

The the partial of $p(t)$ kept as a matrix \code{P.d} which has a column for 
each state and a row for each linear predictor, 
row $q$ of this matrix is the $dp/d \eta$ 
element of the first term in \eqref{productderiv}.
The first term of \eqref{productderiv} is easy: \code{P.d \%*\% P} in the
code. 

The R code for the second term is a little more subtle. Consider a single
a single linear predictor $q$, which is a single row of \code{P.d} and the
\code{[, , q]} margin of $\partial P$. This does not collapse into a single
matrix multiply, we can do it as a loop over the linear predictors, each 
interation updates a single row of \code{P.d}.

So far so good, but the above is not quite what we need. The maximizer wants
to have the derivative with respect to $\beta$, not $\eta = XB$.
If there are no time dependent covariates for a subject, then all rows of
$\eta$ for a given subject are identical, and we could transform to derivatives
wrt $\beta$ at the end of processing this subject.  But many data sets will
have TD covariates, i.e., rows of $X$ for a subject will vary over time.

The transformation of derivatives from $\eta$ to $\beta$ is however simple.
The first term of \eqref{productderiv} is simple matrix multiplication, just
as before, where $P.d$ has a row for each element of $\beta$.
For the second we use the chain rule
\begin{equation*}
\frac{\partial P_{jk}}{\partial beta_m} &=
  \sum_{s=1}^q \frac{\partial P_{jk}}{\partial eta_s} 
   frac{\partial \eta_s}{\partial \beta_m} 
\end{equation*}

The cmap matrix provides map between covariates, coefficients
and $\eta$.
If cmap[j,k] >0, then X[i,j]* beta[cmap[j,k]] is part of linear predictor $j$.
So a ncol(cmap) by length(beta) transformation matrix $Z$ will have 
\begin{equation*}
 Z_{mk} &\equiv \left\{ \begin{array}{cc}
   X_{ij} & C_{jm}=k\\
   0       & otherwise \end{array} \right.
\end{equation*}
This can set up once using matrix subscripts, i.e., let
etabeta be a matrix with rows of (m,k,j) from the above equation, 
one row/value for each nonzero element of cmap.
Then for row $i$ if X we have \code{Z[etabeta[,1:2]] <- X[i, etabeta[,3]]}.

or more efficienty by temporarily treating the derivative as a matrix with
nstate*nstate rows and using the crossprod function.


Aside:The \code{cmap} matrix tracks the mapping between the matrix form of the
parameters $B$ and the vector form $\beta$;
the matrix form is what we want for $XB$ and the vector form is what the
maximization functions want.
We use both so often the hmm code keeps track of both, and uses the
$B.to.coef$ and $coef.to.B$ routines to translate from one to the other.
The $B$ matrix will have a lot of zeros, since most parameters will refer to
a single transition.


Let $\theta$ be an arbitrary parameter, then since $\eta = XB$
\begin{equation*}
  \frac{\partial \theta}{\beta} = X\frac{\partial\theta}{\eta}
\end{equation*}

Consider a single element of $P_{jk}$A given transition matrix $P$ corresponds to a single row of $X$.
The following code fragment will do the expansion for a set of rows $j$
belonging to 
<<eval=FALSE, echo=TRUE>>=
temp <- dim(Pderiv)
dim(Pderiv) <- c(temp[1]*temp[2], temp[3])
crossprod(X[,j], Pderiv)
@ 
In R, this can be done by temporarily changing the dimension of the derivative
to (nstate^2, 
\begin{align}


number of non-zero $Q$. 
