\documentclass{article}
\usepackage{amsmath}
\title{Interval censored multi-state hazard models}
\author{Terry Therneau}

\addtolength{\textwidth}{1in}
\addtolength{\oddsidemargin}{-.5in}
\setlength{\evensidemargin}{\oddsidemargin}
\newcommand{\code}[1]{\texttt{#1}}

%\VignetteIndexEntry{Model theory}
%\VignetteEngine{knitr::knitr}
\begin{document}
\maketitle

<<setup, echo=FALSE>>=
library(hmm)
library(survival)
library(knitr)

knitr::opts_chunk$set(comment=NA, tidy=FALSE, highlight=FALSE, echo=FALSE,
               fig.with=7, fig.height=5.5, fig.path="figures/",
               out.width="\\textwidth", out.height="!", device="pdf",
               cache=FALSE, background="#FFFFFF",
               warning=FALSE, error=FALSE)
@ 

\section{Introduction}
This report describes the underlying mathematics behind interval censored
multistate hazard models, and their extension to model with latent states,
which are a variant of hidden Markov models.
The second of these can in particular be complex, and took me some time
to assimilate.
The report is at least in part documentation for a future me who has 
forgotten those details.
We will first talk about interval censored models, then build on that for
HMM

\section{Multi-state hazard models}
The survival package deals with multistate hazard (MSH) models which are 
based on a 
non-parametric baseline hazard.
The Aalen-Johansen estimator is a natural extension of the Kaplan-Meier,
and the MSH models a natural extension of the Cox model.
The \code{survfit} routine produces both the KM and AJ estimates, and the
\code{coxph} function estimates both the simple proportional hazards (Cox)
MSH model fits.

\begin{figure}
<<nafld1, echo=FALSE>>=
states <- c("0MC", "1MC", "2MC", "3MC", "death")
smat <- matrix(0, 5,5, dimnames=list(states, states))
smat[1,2] <- smat[2,3] <- smat[3,4] <- 1
smat[1:4,5] <- 1
smat[1,3] <- smat[2,4] <- smat[1,4] <- .7
statefig(rbind(4,1), smat, alty= c(1,2,1,2,2,1,1,1,1,1))
@ 
 \caption{Transitions for the NAFLD data, 0--3 = number of the defined
metabolid comorbidites.}
 \label{fig:nafld}
\end{figure}

This library deals with interval censored variants of these models. 
As an illustration consider Figure \ref{fig:nafld}, 
which shows the state space diagram for the NAFLD data set, an
example used in the survival vignette on multistate models.  
At any given visit, subjects will have accumulated
0--3 of three predefined metabolic comorbidites (MC):
diabetes, hypertension, and hyperlipidemia.
If measured continuously, subjects will progress via the solid arrows from 0 
to 1 to 2 to 3 comorbidities.
We assume, biologically,  that no one progresses on two of the markers at the 
\emph{exact} same instant.
In the observed data, however, there will be subjects who are in the 0MC
state at one visit, and in the 2MC state at their next visit; as that following
visit might be several years later.  Such visit pairs lead to the dashed
line transtions in Figure \ref{nafld1}.
(Since comorbidities in the study were defined as ``history of diabetes'', 
``history of dyslipidemia'', and ``history of hypertension''
no one can go backwards.)

The primary underlying difference between the two approaches is
that the semiparametric MSH model fit by coxph is a model for
observed \emph{transitions} while the interval censored MSH model of mshmm
is a model for observed \emph{states}.  
Say that subject X was seen at age 55, 58.2 and 61.4 with their first
MC of diabetes at the second visit.
The coxph fit assumes that a 0MC:1MC transition has occured at exactly age
58.2, while the IC model assumes that there was a transtion at some 
unknown time betwee 55 and 58.2.
Interval censored data is also known as panel data, from studies where
the particpants come back at a regular interal and each visit involves
a panel of tests. The state at each visit is known, but not when between
state transitions had occured.

The perceptive user will have noticed that a call to ismh looks remarkably
like a call to coxph.  This is on purpose, but there are some important
differences between the calls.
The first is that imsh requires
a matrix of valid transions $Q$.  For the above data this is shown below,
and corresponds to the solid arrows in figure \ref{nafld}.
(The computer won't know that a direct 0MC to 2MC transition is impossible
without being told.)
<<qmatrix>>=
states <- c("0MC", "1MC", "2MC", "3MC", "death")
qmat <- matrix(0, 5,5, dimnames=list(from=states, to=states))
qmat[1,2] <- qmat[2,3] <- qmat[3,4] <- 1
qmat[1:4, 5] <- 1
qmat
@ 

A second difference is that the icmsh routine uses a parametric baseline
hazard for each state to state transition, most often a spline function
of age or time.  As a consequence the rates include an intercept term.
Last, some states will not be interval censored, e.g., death; the likelihood
term at a death time is somewhat different.

It turns out that there is a close connection between the simple interval
censored multi-state models discussed so far, and multi-state hidden
Markov models (msHMM), i.e., one can fit them both using the same underlying
function.
HMM models as applied to clinical studies were actually the motivation for 
this package.
 For multistate hidden Markov model the assumption is that the internal
states (other than death) are not observed directly. Instead we observe
one or more imperfect biomarkers of each state. Badly damaged lungs (true state)
might reveal themselves via a low forced expiratory volume (FEV) test, for
instance.

A primary reference for the material was Christopher Jackson's excellent manual 
for the msm package \cite{Jackson16}.
Others that I found particularly helpful were a web page by Nokoalai
Shokiriv \cite{Shokhirev}, Satten and Lingini \cite{Satten96} and
computational details from Kalbfleisch and Lawless \cite{Kalbfleisch85}.
Per Shokhirev there are 3 canonical problems for HMM models.

\begin{enumerate}
  \item Given the model parameters, compute the probability of a particular
    output sequence.  This is solved by the Forward or Backwards algorithms.
  \item Given the model parameters and an output sequence, compute the
    most likely path for the hidden states (the true but unobserved path).
    This is solved by the Viterbi algorithm.
  \item Given an output sequence, find the most likely set of model
    parameters.  This is solved by the Baum-Welch algorithm.
\end{enumerate}
We are focused on problem 1: an underlying search algorithm will choose
parameters $\beta$, which map to rates, which in turn lead to a likelihood
value.  The search algorithm uses this to find an MLE.
Many references, e.g. Wikipedia, focus only on problem 2 to the exclusion of
the others.  This led to much early confusion for this author, e.g., 
the Viterbi algorithm involves a forward recursion and earns a 'forward'
label there.
It might look like 3 is our target, but that would only be true if there 
were no covariates and we were directly estimating the rates.

Symbol matching.  I'm a statistician and am attached to $X$ for a 
predictor, $y$ for the observed response, $\beta$ for parameters,
$i$ for subject and $t$ for time.  Many texts illustrate a single subject
and so can use $i$ for something else, and almost all differ from my
notational choices.  (There is fairly broad agreement on $s$ for the states,
but not much else.)

\begin{itemize}
  \item Shokhirev is written in discrete time, $i=1, \ldots, N$ indexes time.
    \begin{itemize}
      \item $q_i$ is the path through the states, $o_i$ are the
        observed outcomes.
      \item $B$ is the emission matrix with $b_{ij} = b_i(o_j)$ the
        probability that $j$ will be observed if $i$ is the true state.
        (Yes, he reuses $i$ multiple times).
    \end{itemize}
  \item Jackson's msm manual has
    \begin{itemize}
      \item $Q$ is the rate matrix, $P$ the transition probability matrix,
        and $E$ an error matrix.
      \item Subject $i$ progresses through true states $s_{ij}$ with
        $j=1, \ldots, n_i$ and has observed values $y_{ij}$.
    \end{itemize}
\end{itemize}


\section{Interval censored data}
Start with the simpler case of interval censored or panel data.
The second label comes from studies where a subject returns on a fixed
schedule and a set or panel of measurements is obtained at each visit.
If a given subject were found to be in state $s_1$ at the 1 year visit 
and state $s_3$ at the year 2 visit, say,
we do not know  when during that year they transitioned from 1 to 3, 
or whether other states were visited in the interim.

Let $S$ be the set of $m$ states, $p(0)$ the distribution of states at time
0, often $(1, 0, \ldots)$, $P(s,t; \theta)$ the $m$ by $m$ transition
 probability matrix from time $s$ to time $t$, depending on a parameter
vector $\theta$.
Then $p(t,\theta)= p(0) P(0,t)$ will be the probability in state
vector at time $t$.

Let $R$ be an $m$ by $m$ rate matrix, the $jk$ element is the rate of transition
from state $j$ to state $k$; rates are assumed to be constant over a
time window from $s$ to $t$.
Set the diagonal of $R$ such that row sums are 0, then it is well known that 
$P(s,t) = \exp[(t-s)R]$. 
In every actual problem we will work with the rates will be a function of time,
either time since enrollment, subject age, or often both.
What is uniformly done is to break time into smaller segments and assume
that $R$ is constant over each segment.
As a historical footnote, the assumption of constant rates over 
age/sex/calendar year strata is the basis for national death rate tables, with
two centuries experience that this quite adequate for adult ages.

Assume that $t_0, t_1, t_2, \ldots$ are the
time points that partition the line, with often $t_0=0$.  
Then
\begin{equation*}
  p(t_{i+1}) = p(t_i) e^{(t_{i+1}-t_i)R_i}
\end{equation*}

\begin{figure}
<<simple, echo=FALSE>>=
states <- c("Cognitively\nUnimpaired", "Mild Cognitive\nImpairment",
            "Dementia", "Death")
smat <- matrix(0, 4, 4, dimnames=list(states, states))
smat[1,2] <- smat[2,3] <- 1
smat[1:3, 4] <- 1
statefig(rbind(3,1), smat)
@ 
 \caption{Possible multi-state model}
 \label{fig:simple}
\end{figure}

Because we do not observe the transitions, the user needs to specify which
elements of $R$ are non-zero.  
So for instance in the NAFLD model of Figure \ref{fig:nafld} we would allow
only the solid lines; in a simple cognitive model of
\ref{fig:simple}
we might assume that subjects can only go forward from CU to MCI to Dementia.
However, if the data contains any who were observed to be CU after an MCI
visit, the likelhood of the data, under this model, is 0; which is an issue
we will address using the hidden Markov model (HMM).
In the MSH models of coxph function, we need to add arrows for every observed
transition.

\begin{figure}
<<stepfun>>=
xx <- seq(0, 6, length=50)+ 60
yy <- exp((xx-62)/6)
opar <- par(mfrow=c(1,2), mar=c(5,5,1,1))
plot(xx, yy, type='l', lty=1, col='gray', ylim=c(0.5, exp(5/6)),
     xlab="Age", ylab="Hazard")
x1 <- c(0, 1.1, 2.1, 2.9, 3, 4,6) + 61
lines(x1, exp((x1-62)/6), type='s', lwd=2)
x2 <- c(0, 2.3, 4.5, 6) + 60.4
lines(x2, exp((x2- 62)/6), type='s', col=2, lwd=2)
legend(60,2.3, c("Underlying spline", "Smith", "Jones"),
       col=c('grey', 'black', 'red'), lwd=c(1,2,2), bty='n')

plot(xx, yy, type='l', lty=1, col='gray', ylim=c(0.5, exp(5/6)),
     xlab="Age", ylab="Hazard")
x1 <- sort(c(61:66, x1))
lines(x1, exp((x1-62)/6), type='s', lwd=2)
x2 <- sort(c(61:66, x2))
lines(x2, exp((x2-62)/6), type='s', col=2, lwd=2)
abline(v=61:66, lty=3, col='gray')
par(opar)
@ 
  \caption{Left panel: underlying spline model along with the realized step
    functions for two hypothetical subjects with visits at ages
    (61, 62.1, 63.1, 63.9, 64, 65) and (60.4, 62.7, 64.9), respectively.
    Right panel: Augmented data with subject age updated at each birthday.}
    
The baseline hazard is modeled as a parametric function of time, but the
actual likelihood treats this as peicewise constant over the set of time
points $t$ used in the data.
This is because the probability transformation matrix 
$P(s,t) =\exp(A[t-s])$ has a simple form when the matrix of hazards $A$
is constant from $s$ to $t$.
If the baseline were increasing, for instance, we might worry about a bias
from different length intervals; if Smith and Jones had the same covariates,
but Smith was observed at ages 61, 62.1, 63.1, 63.9, 64 and 65, and Jones
at ages 60.4, 62.7 and 64.90, then Jones' computation effectively have a 
lower average rate due to less frequent observation. 
This is shown in the left panel of Figure \ref{fig:simple}, the red line
is lower on average.
A standard response is to add extra censored cutpoints
at 1 year age intervals in order to force an update of $t$, as shown
in the right panel. 
A more rigorous approach will add all observed time points to every subject,
but this is overkill (IHMHO).

Adding dummy observations for each subject so that all share these yearly
cutpoints is a nuisance, but the R tools are effective.
As a contrast, in the \code{icmstate} package the baseline is treated as
non-parametric.  The cutpoints will be the set of observed event times,
and if time is measured in days it is likely that there is only one observed 
event at any given event time, leading to a sparse $R$ matrix and faster
computation.
(Computing a lot of matrix exponentials is a major part of the compute time.)
A disadvantage is that an EM algorithm is needed at each time point to
estimate the baseline rate.

Assume subject $i$ is seen at times $t_{j}$, $j=0, \ldots, n_i$, with observed
states $s_{j}$, where $t_{0}=0$ is the starting time.
The likelihood computation for interval censored models can be thought of 
in three parts, for each subject $i$
 \item The initial probability in state vector $p(t_0)$.
 \item The transtion matrix from $t_{m-1} to t_{m}$ for $m>0$
 \item Restrictions on the current state at each observed observation time
   $t_{m}$
\end{itemize}
For a simple interval censored model (suppressing the $i$ subscript) the
initial probability vector matches the intial state at enrollment.
The algorithm is
\begin{enumerate}
  \item $p_j(t_0) = I(s(t_0) =j)$
  \item For $m=1, \ldots, k$, where $t_k$ is the last observation for the 
    subject
    \begin{itemize}
      \item $P(t_{m-1}, t_m) = \exp(R(t_{m-1}[t_m- t_{m-1}])$
      \item $p(t_m) = p(t_{m-1})P(t_{m-1}, t_m) D(t_m)$
    \end{itemize}
\end{enumerate}
where $D$ is one of 3 forms.
\begin{itemize}
  \item If $s(t_m)= d$ where $d$ is a death or other absorbing state, then
    $D_{jk} = exp[R_{jk}(t_{m-1})]$ for all $j \ne k$.
  \item If $s(t_m) =k$, $k$ not a death state, then $D_{kk}=1$ and 0 otherwise,
    i.e., all elements of $p$ except the $k$th are zeroed.
  \item If this is a censored observation, then $D_{kk}=1$ for all non-death
    states $k$, i.e., we know they are not dead, but not which other state.
\end{itemize}
A way to think of this is that the probability matrices $P$ march forward
in time, with a new interval for each change in covariates. 
Whenever a subject is actually observed, then the $p$ vector becomes 
constrained to smaller set of possibilities.
An interesting aside is that the last action above need not be exercised until
the final row of a subject, updating at intermediate censoring points is not
necessary.

If one subject is measured a lot more often than others, the $P$ matrices
become close to the identity; they do not contribute a lot more to the
loglik due to multiple measurements, i.e., this does not add a bias.
(They do contribute a tiny bit more information, since the time of any
observed transition is more bounded.)

As a simple example, assume three states and two subjects with the same
$R$ matrix below, both of which transition from state 1 to state 2 at 6
months and remain there until 2 years.
However subject 1 is measured bi-monthly and subject 2 yearly.
The compuation below shows that the probability of conversion at any given
visit for subject 1 at each visit, along with the overall probability at
one year.  The value for subject 2 is, as we would expect, close to the sum 
over 
subject 1 of ``in state 1 at 0, 2 at month 2, 4, 6, 8, 10, 12'', 
``in state 1 at 0 and 2, state 2 at month 4, 6, 8, 10, 12'', etc.
They are not identical, since the small probability of revision from 2:1
means that the the single observation has a smidge larger space of possible
paths.  If $R_{21}=0$ then they are identical; there is a single first visit
when state 2 is observed.

<<rateexample>>=
R = rbind(c(-.15, .1, .05), c(.05, -.25, .2), c(0,0,0))
P1 <- expm(R/6)  # bi-monthly, for subject 1
P2 <- expm(R)    # yearly, for subject 2
temp1 <- double(6)
for (i in 1:6) 
    temp1[i] <- P1[1,2] * P1[1,1]^(i-1) * P1[2,2]^(6-i)
names(temp1) <- paste0("month", 1:6*2)
round(temp1, 4)
temp2 <- P2[1,2]
round(c(temp2, sum(temp1)), 4) # probability some time during the year
@ 

The rates in the hazard matrix $R$ will normally be functions of $X\beta$
where $X$ is a matrix of per-subject covariates and $\beta$ is a matrix
with one column for each possible transtion; again similar to coxph.
Because the baseline is parametric $\beta$ will also include an intercept
term, and often a spline for age.

If we assume a Markov assumtion, then $P(s,t) = P(s,u)P(u,t)$ for any time
point $u$ between $s$ and $t$. 
(I had to write this out as a long sum in order to prove it to myself:
the fact that matrix multiplication
does exactly the right thing wrt the unknown state at time $u$ is still a
bit magic.)

\section{HMM likelihood}

For a hidden Markov model (HMM) the likelihood has one more piece.  At each
observation time there are one or more marker variables $y_{ijk}$ measured on a
subject.  The number $k$ could be the same at any visit, or different,
e.g. a particular test might not be done on all visits, or for all subjects.
The second component of the models is a set of densities $f_k(y_k | m)$, 
the probability such a measurement $y$ if the true state of the subject
is $m$.
In many cases the observed states $y$ will have the same labels as the
true states, such duplicate labels mostly serve to generate confusion.  

Let $S$ be the set of possible true states; 
4 in our basic Alzheimer's model, with
$s_1, s_2, \ldots, s_n$ a possible path through those true states for
some subject who has $n$ observations.
      
The HMM probability is formally a very large sum:
\begin{equation}
  P(y_i | \beta, \pi) = \sum_{s_1, s_2, \ldots} Pr(y_{ij} | s_{ij}) 
      Pr(s_{ij}; \beta, \pi)
  \label{full}
\end{equation}
where $\pi$ is an initial probability distribution.
The sum is over all possible paths through the states: if subject Jones
had 7 observations and there are 4 states this would be a sum over
$4^7 \approx 16,000$ terms.
For each of those possible paths we have the probability of that path,
given the coefficients of the model, times
the probability of observing
the vector of states $y_i$ for that true path.

A big simplification comes from two assumptions: first that $y_{ij}$ depends
only on the current true state $s_i(t_{ij})$ (subject $i$, $j$th observation)
and the Markov property of the underlying
chain, which means that the current state depends only 
on the prior state.
This allows the computation to be written as a nested sum:
\begin{align}
   P(y_i | \beta, \pi) &= \sum_{s_1} \left[f(y_{i1}| s_1)P(\pi,s_1, \beta) B_2 
            \right] \nonumber \\
    B_2  &= \sum_{s_2} \left[ f(y_{i2}| s_2)P(s_1,s_2, \beta) B_3 \right] 
            \nonumber\\
    B_3  &= \sum_{s_3} \left[P(y_{i3}| s_3)P(s_2,s_3, \beta) B_4 \right]
            \nonumber \\
    B_4  &=  \ldots     \label{recur}
 \end{align}
The above equivalent to equation 12 in the msm vignette.

The references all now say ``thus calculating the probability reduces to
matrix multiplication'', which was not at all obvious to me.
The first trick is to remember that $P(t_0,t_1)P(t_1,t_2) = P(t_0, t_2)$,
and likewise for multiplication of 3, 4 etc of the steps.
Now, let $D_{im}$ be a diagonal matrix with $jj$ element 
$f(y_{im} | s_m = j; \gamma)$, the probability of the observed $y$ at
time $m$ for each possible true underlying state,
possibly depending on some parameters $\gamma$.
The $jk$ element of $T_{im} = P(t_{m-1}, t_m)D_{im}$ is the probability that 
subject
$i$ will be in true state $k$ \emph{and} observed status $y_{im}$ at time $m$
given that they were in true state $j$ at time $m-1$.
If there are multiple response measured at the time then use
$P(t_{m-1}, t_m)D_{im1}D_{im2}\ldots$.  Multiplication of the diagonal matrices
is the probability that all of the responses align.
The matrix product $p(t) = p(0) \prod_{k=2}^m T_{ik}$ is the vector
containing for each true state the probability that subject $i$ will
will be in that state at observation $m$ and have the sequence $y_{i1},
y_{i2}, \ldots y_{im}$ of observed measurements.
For an observed death $T$ has the same form with $D$ a diagonal matrix 
containing the entries in the death column of $R$.

The probability for a subject is then a sum over states; the probability they
are currently in state 1 given the observed outcomes + probability in state 2
given the observed outcomes + \ldots;  
which is the sum of elements of $p(t)$.
The probability for the entire study is the product of per-subject values.
(Note that msm package uses $\alpha$ instead of $p$ in both code and
documentation).
If you look closely, this is the same formula and the non-HMM case, but with a
different $D$ matrix.  We can in fact view the simple interval censored fit
as an HMM fit where the markers are error free.

(I now think the paragraph just below is wrong, but not yet convinced enough to
remove it. The $y$ values are realizations of the true state so are 
conditionally independent given state, not independent.)

[One important assumtion of the above is that the $y$ values are independent
given $p$.
A simple counter-example would be a study where most are measured yearly but
subject 2 is measured daily. There is more information about subject 2, as
we essentially no longer have any error with respect to their true state, 
but not 365 times more information. 
For instance, if the marker in question depended both on true state and some
other umeasured covariate (blood type AB biases the biomarker assay high, say)
then 365 repeated lab runs will not reduce absolute error by $\sqrt(1/365)$.
The variation is shrunk but the bias remains.
I don't think this is a serious problem in most studies, however.]

\section{Intial state}
The very first step of the computation requires a bit more thought.
The initial state is normally a reflection of the recruitment process, not
the process of disease progression. 
As such the considerations for this value are completely different than for 
the rest of the HMM likelhood.
Which subjects from our target population (the one we \emph{want} to explore)
are available in the sampling frame, which of those 
fullfill the eligiblity criterion of the study, and which were chosen?  
There are four approaches available.

The first is to use a single vector $p(0)= \pi$ for all subjects.
This is the initialize step in Shokhirev for instance.
Each subject is assumed to be randomly chosen from an underlying population with
probability vector $\pi$.
The parameter estimate $\pi$ may be fixed or estimated, and may involve 
per-subject covariates.  We might have run an external regression to assign
probabilities to each state, for instance.
In some cases the estimated result will be of interest in
itself, in others we might regard it as a nuisance parameter.

In approach 2 every subject has a different entry probability.
The simplest variant of this is if we assume the initial state is known
for each subject, call this 2a.  
For instance, the initial enrollment visit might involve a more complete
evaluation, such that the underlying state is certain; each subject's
initial $\pi$ will then have a single 1 and remaining elements of 0.
The \code{cav} dat set of the msm manual is analysed in this way.
One important consequence of this view is the error matrix for the first
visit. Consider the cardiac allograph vasculopathy (CAV) data set in the msm
package, with observed states of none/mild/severe/death and true states of 
C1/C2/C3/death; for the visit at time 0 $D$ should be the identity, not an
estimated missclassification matrix.  One way for the user to enforce this
is to code the time 0 value of the measured response as NA.

A second variant 2b is to estimate the per-subject $\pi$, external to
the HMM fit.
In the dementia example we might assume that Pr(CU/MCI/dementia) at enrollment
is a function of age, and employ a simple multinomial model to estimate it, 
using the initial visits as the data.
The age specific predicted values from this fit will then be used as $\pi_i$
for subject $i$.
(No one enrolls in the death state, of course).
We expect that method 1 will be more efficient since it uses all the information
within the HMM fit.

The third approach uses updated prevalence and is appropriate to the MCSA, 
a study 
in which the subjects are an age and sex stratified population sample. 
In this special case the the distribution of enrollment states at each age is
itself informative of the progression process. 
Mechanically, it was done in the following way, using all subjects aged 50 or
over
\begin{itemize}
  \item Assume a known, common distribution at age 50.
  \item For someone who enters at age 82, say, use the current model estimates
    to compute the prevalence of states in the population, at age 82, for
    someone with the same covariates as the subject of interest.
  \item Rescale that prevelence by an estimate of enrollment probability for
    each state.
\end{itemize}

This creates an age specific $\pi$ vector for each subject.
For the dementia example above we might assume that at age 50 all subjects 
in the underlying population are cognitively unimpaired.
If someone were recruited at age 82.2, the overall population prevalence
at that age is $p(82.2)= \pi(50) P_i(50, 82.2 ;X_i,\beta)$, $P_i$ being the 
transition matrix appropriate for the covariates $X_i$ of this subject.
Pragmatically, this is obtained by adding dummy rows for the subject
at age 50, 51, \ldots, 82, all censored, and adding an indicator variable that
marks the onset of the ``real'' observations. The working vector $p(82)$ is then
created automatically by the standard computations.
However, the study did not randomly select subjects from the distribution
just computed --- that would have meant enrolling a lot of dead people. 
A non-renormalized value would discourage high death rates; the likelihood
will see it as an
unlikey event to have enrolled several living 82 year olds but no dead ones 
if Pr(death) by age 82 is 50\%.
We use a renormalized value for state $s$ of
$$\pi_s(82.2) = p_s(82.2 | X_i) P(\mbox{enroll} | s) / \sum_s \pi_s(82.2) $$
At present the conditional probability vector is set by the user, often to
(1, 1, \ldots, 1, 0), i.e., success for any state but death. 


One shortcoming of the above is that it cannot be implemented if the hazard
includes time-dependent covariates; as the necessary $X_i$ values prior to 
age 82 are not known to us.  If there are no TD covariates and recruitment
is a true random sample from the population, however, this approach can lead
to a substantial gain in information.
The pattern of enrollment diagnoses, by age, is in this particular case  
informative with respect to the underlying population progression.

A last approach, not inplemented, is discussed in Satten and Longini.
Use
\begin{equation*}
p(0) = \sum_{s_1} f(S=s_1| y_{i1}, \gamma) \pi(s_1)/ \sum p(0)
\end{equation*}
That is, $p(0)$ becomes a posterior distribution over the states given
the first observation.  
The distribution is allowed to depend on parameters of the misclassification
process ($\gamma$) and on initial state, but not on the paramters of
the transition probabilities $\beta$.
They then choose a suitable prior for $\pi$ and integrate it out.
I am not clear on whether this improves estimates or not.

\section{Censoring and Death}
Censoring in the hmm package is viewed somewhat differently than in the
survival package.  
First, there is the censoring indicator of the Surv() response, which marks
only whether this observation corresponds to an ``exact time'' state.  It will
normally only be used for death.
The second are censored markers and correspond to partial information, often
one of 3 types:
\begin{enumerate}
  \item For a continuous reporter, for instance, there might be a lower 
    threshold
    $z$ on the assay for that reporter.  The proper element of $D$ for a
    value below threshold would be $ \int_0^z f(x) dx$.
    This is equivalent to left censoring in a parametric survival model, 
    an upper threshold will correspond to right censoring.
  \item For a categorical response censoring corresponds to knowing a subset of
    response values. In the Mayo Clinic Study of Aging (MCSA) for instance, one
    of the markers for cognition is assessment of congitively unimpaired,
    mild cognitive impairment or dementia (CU/MCI/Dem).  Patients who have 
    a partial assessment, e.g., phone or a record review, will lack the cognitive
    testing battery and can be only be classed as non-demented (NC) or demented.
    A missclassification matrix for this is shown in Table \ref{tab:missclass2}.
    One subtle but important point is that observation of NC does not mean that
    the \emph{true} state is CU or MCI, but that the \emph{observed} state is
    CU or MCI.  To forstall such confusions we take care to use different labels
    for true states and observed states.
  \item Any censored data row is known to not be in the death state.
\end{enumerate}

\begin{table} \centering
  \begin{tabular}{rcccc}
 State& CU & MCI & Dem & ND  \\ \hline
 C0 & $1-a$& $a$ & 0   & $1$ \\
 C1 & $b$  & $1-(b+c)$& $c$& $1-c$ \\
 C2 & 0    & $d$      &$1-d$&$d$ \\
 Death&0 &0 &0 &0
 \end{tabular}
\caption{Missclassification table with non demented (ND) = CU + MCI as
  a censored category. }
\label{tab:missclass2}
\end{table}

One case that is not handled above is the (rare) case of a biomarker
measured on the day of death, e.g., an auto accident at the end of a day of
medical appointments. The user will need to move the prior visit back a smidge.
Two other rare but possible cases are
\begin{itemize}
  \item An exact state which is not aborbing, e.g., 
    the surgical remission state that occurs after resection of an inflamed
    bowel segment, in the managment of Chohn's disease.
  \item A state which is ascertained without error but the time of
    entry into said state is unknown, e.g., MAFLD.
\end{itemize}

When there is a single categorical marker, as in the table above, one temptation
is to include death as one of the categorical states. This is done in the msm
manual for instance. Table \ref{missclass2} would have another column ``death''
with values of 0,0,0,1.
In our code and in the explanation here we have been careful not to do this:
death (and any other known state) are in the Surv() object, only hidden states
are reported out by markers.
There are a few reasons for this.
\begin{itemize}
  \item Death is different, it leads to a separate compuation in the likelihood.
    Because of this we will need to mark it off separately anyway.
  \item The CU/MCI/dementia variable is measured at a clinical visit, death
    comes from other sources, so we are mixing two things together.
  \item When a model has multiple categorical markers, which gets the death
    addition? If there are only continuous markers, where does it go?
\end{itemize}
One counter argument is that we could as easily say that death identifies
one of the true states, and any marker that maps to that state inherits the
behavior. 
(It is one case where using the same label for a marker and the state is
complely valid.) 
This solves the first point above. But we still need a data marker
in the continuous case.

\section{Modeling cognitive decline}

Suppose we have two parallel latent processes, call them the accumulation of
amyloid/tau damage and the accumulation of cerebral vascular damage.
We can think of them in the the following diagram.

<<decline>>=
opar <- par(mfrow=c(1,2), mar=c(1,1,1,1))
aname <- c("A0", "A1", "A2", "death")
amat <- matrix(0, 4,4, dimnames=list(aname, aname))
amat[1,2] <- amat[2,3] <- 1
amat[1:3,4] <- 1
statefig(c(3,1), amat)

vname <- c("CeV0", "CeV1", "CeV2", "death")
vmat <- amat
dimnames(vmat) <- list(vname, vname)
statefig(c(3,1), vmat)

par(opar)
@ 

This gives a 10 state model.  If we assume that two different transitions never
happen at the same momement we have the following transition matrix.

\begin{center}
  \begin{tabular}{ccccc|ccc|cccc}
    && \multicolumn{3}{c}{A0} & \multicolumn{3}{c}{A1} & 
    \multicolumn{3}{c}{A2} \\
    && CeV0& CeV1 & CeV2 & CeV0 & CeV1 & CeV2 &CeV0 &CeV1 &CeV2 & death\\ \hline
   &V0   & r1 &    & r1 &    &    &    &    &    & d1 \\
A0 &CeV1   &    & r3 &    & r4 &    &    &    &    & d2 \\
   &CeV2   &    &    &    &    & r5 &    &    &    & d3 \\ \hline
   &CeV0   &    &    &    & r6 &    & r7 &    &    & d4 \\
A1 &CeV1   &    &    &    &    & r8 &    & r9 &    & d5 \\
   &CeV2   &    &    &    &    &    &    &    & r10& d6 \\ \hline
   &CeV0   &    &    &    &    &    &    & r11&    & d7 \\
A2 &CeV1   &    &    &    &    &    &    &    & r12& d8 \\
   &CeV2   &    &    &    &    &    &    &    &    & d9 \\
&death
  \end{tabular}
\end{center}

There are 12 different state to state transitions and 9 to death.
If we don't want to fail from too many coefficients, then we might 
assume that the effect of some covariate \code{zed} is additive.  
We would have formula lines such as
\begin{verbatim}
  A0CeV0:A1CeV0 + A0CeV1:A1CeV1 + A0CeV2:A1CeV2 ~ zed /common,
  A1CeV0:A2CeV0 + A1CeV1:A2CeV1 + A1CeV2:A2CeV2 ~ zed /common,
  A0CeV0:A0CeV1 + A1CeV0:A1CeV1 + A2CeV0:A2CeV1 ~ zed /common,
  A0CeV1:A0CeV2 + A1CeV1:A1CeV2 + A2CeV1:A2CeV2 ~ zed /common,
\end{verbatim}
which says that there is an effect of zed on the A0:A1 transition, independent
of the CeV state, and another for A1:A2. Likewise an independent effect for
CeV0:CeV1, independent of the A state, and another for CeV1:CeV2.  
Twelve transtions but only 4 coefficients for zed.
One could collapse further and have a single effect of zed for an increase
in A, with the same effect on either A0:A1 or A1:A2.

This additive view is essentially the graph above, i.e., thinking of the
two transitions as independent. 
We can have the same discussion about transitions to death: do the A and
CeV processes have additive contributions (6 coefficients) or interactive
ones (9 coefficients).
The design of our multistate models is backward from the usual glm model, say,
in that for the coxph, msm, and hmm software covariate*transition interactions 
are assumed and have to be explicityly removed,
whereas in a glm model additivity is uniformly assumed and interactions are
added with *.

If we assume overall additivity for covariates, 
then how do we model interactions between the processes themselves, 
i.e., if the baseline rate of A1:A2 transition is affected by CeV damage?
This is picked up by the intercept terms, which control baseline rates.
We can make these terms additive as well, or not. 
Say that x1= APOE positivity. The idea is that an e4 allele affects transition
rates for A via biological paths not dependent on CeV state,
while interactions in the intercept term capture that CeV itself also modifies the
A process via other background processes.
Sorting out whether ``A affects CeV'' or ``CeV affects A'' from the pattern of
intercept terms will certainly be a challenge, one that I may not be
up for.
(Ignoring age for a moment, if the A1CeV1:A2CeV1 rate was smaller than
A1CeV2:A2CeV2, but CeV1:CeV2 rates did not depend on A, that could 
be an argument that
CeV affects A but not vice-versa.
Parsing out smooth age effects will be harder).
For the dementia problems my intercept term will be a spline on age,
and the discussion about shared intercepts is exactly parallel to that
for separate, shared or proportional hazards in the multi-state hazard model.
We might well assume for instance that $\beta(age)$ has the same shape for 
A0:A1 and A1:A2, with a single constant of proportionality.
Assuming the same shape for A0:A1 and CeV0:CeV1 would be a stretch.

\subsubsection*{Move to the user guide}
To make like easier wrt specifying covariate effects in HMM we can use the
statedata option. This is a data frame with a required variable ``state'', but
which can have multiple other columns.  For the above we would have the 9 row
data frame below.

<<statedata>>=
A <- c("A0", "A1", "A2")
CeV <- c("CeV0", "CeV1", "CeV2")
sdata <- data.frame(state= c(t(outer(A,CeV, paste0))),
                    A= rep(A, each=3), CeV=rep(CeV,3))
sdata 
@ 

One can then use \code{A0:A1 ~ x1} in the formula as an alias for all 9 matching
row pairs of statedata, only 3 of which are actual transitions.
(The underlying code takes care of that part).

\section{Matrix exponential}
We tend to forget that deep in the standard libraries the standard exp()
function is defined using an approximation.  One idea is that 
\begin{align*}
  \exp(x) & = \left(e^{x/2}\right)^2 \\
          &=  \left(\left(e^{x/4}\right)^2\right)^2 \\
          &=  \left(\left(\left(e^{x/8}\right)^2\right)^2\right)^2) \\
          &= \vdots
\end{align*}
along with the fact that for a limited range $a < x < b$, $\exp(x)$ is well
appoximated by a simple polynomial or ratio of polynomials. 
Compute $\exp(x/2^k)$ for an approriate $k$, then repeatedly square the result. 
The actual code is more sophisticated but this is the basic.

The exponetial of a matrix $A$ is defined similarly to the standard exponential
\begin{align*}
  exp(x) &= 1+ x + x^2/2 + x^3/3! + x^4/4! + \ldots \\
         &= lim_{n \rightarrow \infty} \left( 1+ 1/n\right)^n \\
  exp(A) &= I + A + A^2/2 + A^3/3! + A^4/4! + \ldots \\
         &= lim_{n \rightarrow \infty} \left( I+ A/n\right)^n
\end{align*}
Moler and van Loan's famous 1978 paper ``Nineteen dubious ways to compute the 
exponential of a matrix'' and its 2003 update \cite{Moler78, Moler03}
showed that the compuation can be difficult and inspired much work on the topic.
A basic problem is that the elements of a matrix can be of quite different
magnitudes.

Our matrix $A$ is a transition rate matrix, where the off diagonal $jk$ element
contains the transition rate from state $j$ to state $k$
\begin{itemize}
  \item $A_{jk} \ge 0$, $j \ne k$
  \item $A_{jj} = -\sum_{k\ne j} A_{kj}$
  \item $A_{jk} =0$ if and only if the transtion cannot occur
  \item The transition probability matrix $P= \exp(A)$ satisfies
    \begin{itemize}
      \item $sum_k P_{jk} =1$, all rows sum to 1
      \item $0 \le P_{jk} \le 1$
    \end{itemize}
\end{itemize}
This means that the matrices are better behaved than the general case.
There are three different approaches that will be of interest to us.

\subsection{Closed form solutions}
Case 1: If all of the positive elements of $A$ lie in a single row or a single
column, then there are simple closed form formulas. This occurs quite often
in the survival package, e.g., for any time point at which only a single
of transition occurs, but rarely if at all in this package.

Case 2: There is a small set of designs for which the closed form formulas 
exists, though they are more complicated. The msm package pursued this 
approach, we have not.

\subsection{Matrix decomposition}
If the eigenvectors of $A$ are linearly independent, then 
\begin{equation*}
  e^A = U{\rm diag}(e^\lambda)U^{-1}
\end{equation*}
where $U$ is the matrix of right eigenvectors and $\lambda$ the eigenvalues.
A (right) eigenvector $u$ satisfies $Au= \lambda u$.
If the matrix of eigenvectors $U$ is non-singular, and with 
$\Lambda$ the diagonal matrix of eigenvalues we have
\begin(align*) {
    AU &= = U\Lambda\\
    A &= (AU)U^{-1} \\
      &= U \Lambda U^{-1} \\
    exp(A) &= U \exp(\Lambda) U^{-1}
\end{align*}
The exponential of a diagonal matrix $D$ is a diagonal matrix with 
$jj$ element $\exp(D_{jj})$; the final equation above arises directly from 
the Taylor series for exp.

A left eigenvector matrix $V$ satisfies $VA = \Lambda V$. 
This can also be defined as the transpose of the right eigenvectors of 
$A$ transpose. 
The eigenvalues that correspond to left and right eigenvectors are identical, 
and it turns out that $VU=I$. 
(I found this last identity listening to a lecture, but have not found it 
mentioned in any of the texts I have looked at.)
The lapack eigen routines wil return both left and right eigenmatrices if
requested; there is no need for our routine to compute $U$-inverse.

\begin{itemize}
  \item If the eigenvalues $\lambda$ are distinct, then $U$ must be full rank.
  \item If $A$ is upper triangular, which is true if there are no loops or
    returns in the state space (a feature of many of our models),
    then there is a fast algorithm to calculate $U$, $\lambda$, and $U^{-1}$.
  \item If there are tied eigenvalues, $U$ will still often be full rank,
    and if it is not the Jordan canonical form applies.
  \item If $U$ is close to singular, then this algorithm for the matrix
    exponential can be imprecise,
    with error proportional to the condition number of $U$ times the underlying
    machine precision. When $U$ is exactly singular, computation of the
    Jordan form is very difficult; small round off errors cause the problem to
    flip back and forth between \emph{exactly} singular and \emph{almost}
    singular.
  \item The better approach, exemplified in the expm-eigen.c function in the
    expm package, is to pay attention to the condition number, and switch to
    a Pade approach if it is large.  They use an inverse condition number
    of \code{.Machine\$double.eps}, which is fairly aggressive.
\end{itemize}

A primary attraction of the decompostion method is that it gives an immediate
solution for computing the derivatives of $\exp(A)$ with respect to the
parameters and derivatives are something that we need
for many of the solution methods. Per Kalbfleisch and Lawless 
\cite{Kalbfleisch85}
\begin{align*}
 \frac{\partial e^A}{\partial \theta} &= UVU^{-1} \\
 V_{jk} &= \left( \begin{array}{cc} G_{jk}\frac{(e^{\lambda_j} - e^{\lambda_k}}
     \lambda_j- \lambda_k} & \lambda_j/ne \lambda_k \\
                  G_{jj}te^{\lambda_j} & \lambda_j= \lambda_k \end{array} \\
 G &=  U^{-1} \frac{\partial A}{\partial \theta} U
\end{align*}

In our code we take a chained approach.  The matrix exponential routines
calculate the above derivatives with $\theta$ as the individual elements of
$A$, i.e., $dA/d\theta$ will be a matrix of zeros with a single 1 off the
diagonal and -1 on the diagonal.
If $A$ contains $m$ non-zero transition rates this leads to $m$ derivative
matrices for $\exp(A)$. 

The individual elements of $A$ are the linear predictors $\exp(\eta)$,
$\eta=XB$, one linear predictor for each non-zero rate in $A$. 
Then by the chain rule
\begin{align*}
  \theta_m &= \exp(\eta_m) \\
  \eta_m   &= \sum_j X_{ij}\beta_j
  \frac{\partial f(e^\eta)}{\partial \beta_j} &= 
  \frac{\partial f(\theta)}{\partial \theta} 
  \frac{\partial \theta}{\partial\eta} \frac{\partial \eta}{\partial \beta_j}
    \\
   &= \frac{\partial f(\theta)}{\partial \theta} e^\eta X_{ij}
\end{align*}
To keep the notation simple the above has focused on a single transition rate
$k$, for a covariate/coefficient that does not participate in that transition
treat $X$ as zero.
The upshot is that our matrix exponential routines can return the derivatives 
with respect to$\theta$, and the rest of the computation done by simpler R code.

\subsection{Pade approximation}
The \code{Matrix} library includes an \code{expm} function and the \code{expm}
library a more refined version, both based on more recent work by
\cite{Higham22}.
Both turn out to be refinements of the simple ``scale and square'' algorithm 
mentioned above for the simple exponent.
If the elements of $A/s$ are bounded to $\le 1$ then
$$
  e^{A/s} \approx p(A/s)/q(A/s)
$$
where $p$ and $q$ are polynomials in $A/s$. The order of the polynomial is 2
to 8, chosen dynamically based on matrix values.
The coefficients of the polynomials are
The scale factor $s$ is chosen as the power of 2 the properly bounds the 
elements, and at the end the result $\exp(A/s)$ is repeatedly squared to
create $\exp(A)$. 

If we don't need derivatives it is difficult to improve on the \code{expm}
library, certainly in terms of reliability.  But we do need derivatives.
We have created a clone of one of the simpler methods (Wards method) from
the expm library --- it skips the more sophisticated preconditioning steps ---
and then compute the derivative by brute force. 
This is based on the unproven assertion that transition matrices are ``nice''
and we can skip these preconditioning steps, and working out the impact 
of these steps on the derivative is well beyond my skill set.

\begin{itemize}
  \item Start with $dA/\theta_k$ as above, the derivative with respect to a
    change in the $k$th rate.
  \item Then $dA^2/\theta_k = A(dA/\theta_k) + (dA/\theta_k)A$
  \item $dA^3/\theta_k = A^2(dA/\theta_k) + (dA^2/\theta_k) A$
  \item etc
\end{itemize}
The allows accumulation of the derivatives of $p(A)$ (one per element, each
a matrix), and similarly for $q(A)$.
Then use the identity that
$$
\frac{\partial A^{-1}}/{\partial \theta} = A^{-1}
  \frac{\partial A}/{\partial \theta} A^{-1}
$$
And finally, update the derivatives yet again throughout the squaring steps.

\subsection{Using BLAS}
One last important point with respect to speed is visible by looking at the
code for expm.c in the expm library: all matrix operations are performed
by calls to LAPACK routines, which in turn are based on BLAS.
The BLAS (basic linear algebra subprograms) are carfully tuned to each
particular computer achitecture and hardware. Using them can result
in surprising speedups: 50 to 100 fold for larger matrices, though we
anticipate less for our smaller problems.

There are multiple routines for eigenvalues in LAPACK, the R eigen routine
uses dgeev (function La\_rs, src/modules/lapack/Lapack.c).
They make a first call to determine the optimal size of a work array, 
allocate the array, then call the routine. 
The expm-eigen code in the expm package also uses dgeev in the same way.

An alternate route is to use dgees, which utilizes a Schur decomposition.
This satisfies $A= QSQ'$ where $Q$ is orthagonal and Schur matrix $S$ is 
quasi-triangular. That is, the block diagonal of $S$ is made up of 1x1 elements
containing the real eigenvalues, and 2x2 elements for each complex pair of
eigenvalues $a \pm \sqrt{bc}$
$$
\left( \begin{array} cc a& b\\ c&d \end{array} \right)
$$
The eigenvalues of an upper triangular matrix are real and on the diagonal.
When we have an upper triangular matrix, we can use the dtrevc routine directly,
which expects a Schur factor. 
Note that since the row sums of a transition matrix are 0, the final row of
an upper triangular transition matrix is 0 (the death state, which absorbs from
all others.) 

\section{Fisher scoring}
The hmm function allows ``Fisher scoring'' as a choice of algorithm for finding
the maximum.  This is the union of four ideas.

Let $U(\theta)$ be the matrix of first derivatives, one row per subject and
one column per parameter, $1'U$ is the overall first derivative.
At the solution $\hat\beta$ we have 
\begin{align*}
  E(U) &= 0 \\
  E(U'U) &= {\rm var}{\hat\theta} \\
         &= E(H^{-1}) \\
  H_{jk} &= \frac{\partial \log(f)}{\theta_j \theta_k}
\end{align*}
$H$ is the second derivative matrix or Hessian. 

The first idea in the code is to use the empirical value $U'U/n$ as a 
replacement for $H$ in the Newton-Raphson algorithm.
The first derivatives of all log-likelihood components are available
analytically, including the matrix exponential, so are fairly economical to
compute.  For modest problems ($< 50$ parameters) we have found the compute
time to increase by 2-3 fold when computing the derivative as well as the
loglik for a given set of coefficients.
 The Hessian matrix, on the other hand, needs to
be computed analytically and so is much more expensive.  Update algorithms
like BFGS reduce this considerably of course, but we have found each iteration
of optim to be much slower than the above.

When we are far from the true maximum this approximation might not be accurate,
of course, so the code adds an additional amount to the diagonal, resulting in
the Levenburg-Marquardt algorithm.  It is only necessary that this approximate
Hessian be \emph{accurate enough} to correctly step in the direction of the true
maximum log-likelihood.
We purposefully start with a more conserative (larger) diagonal
addition than most texts, trading some speed for more safety.  
Internally, the data has been centered and scaled, so addition of the same
constant to all diagonal terms is reasonable.

As a third component, the potential update from this LM step is subjected to a
trust region argument based on chapter 9.7 of \cite{Press02}. 
The LM step itself is based on an assumption that the log-likelihood is locally
quadratic, it extrapolates from the current position to the next estimate
based on that assumption.  
The trust region addition compares the realized value of the
loglik, at proposed new estimates, to what the predicted value of
the function would be at that point if the quadratic were perfect.
If these two values are far apart this is evidence that the Taylor series has
reached too far, i.e., beyond the region where the series is accurate.
The strategy is to then take a smaller step, that is, stay within the span
for which the Taylor series prediction is sufficiently good, where it can
be ``trusted''.

The last addition is to allow constraints. This is a matrix $C$, the solution
is forced to satisfy $C\beta >0$, each row of $C$ is a separate constraint.
This is accomplished by using quadratic programing, applied to the proposed
LM step, to find an optimal solution to the LM function (a quadratic) that
also obeys all of the constraints. What this means in practice is that none
of the trial solutions will be outside the bounds.

We have found the constraints to be very useful for sevaral of our fits.
For complex problems, the final solution may well not lie on any of the
constraint boundaries, and yet the presence of the constraint had kept
the maximizer from taking a particulary bad step.  Some of these constraints
will be simple, e.g. a higher amyloid burden cannot decrease the death rate.
(Amyloid might not cause death, but it certainly can't help.)

There are two caveats with our method for constraints. The first is that it is
important to start at a solution which satisfies all of the constraints, e.g.,
all coefficients of 0.  If starting in a region where the constraints are
violated, there is no guarrantee that our simple QP approach will find
*any* feasable solution.  It turns out to be harder to back out of an invalid 
area of the solution space than to avoid such areaa from the first.
A second issue with constrains is that if any of them are active at the 
solution, then
the estimated variance $\sum_i U_i'U_i /n$ may be an overestimate.
Williams \cite{Williams20} addresses this issue by using an MCMC approach.

\bibliographystyle{plain}
\bibliography{refer}

\end{document}
