\documentclass{article}
\usepackage{amsmath}
\title{Censored multistate hazard (MSH) models}
\author{Terry Therneau}

\addtolength{\textwidth}{1in}
\addtolength{\oddsidemargin}{-.5in}
\setlength{\evensidemargin}{\oddsidemargin}
\newcommand{\code}[1]{\texttt{#1}}
\newcommand{\comment}[1]{{\color{blue} #1}} 

%\VignetteIndexEntry{Censored multistate hazard (MSH) models}
%\VignetteEngine{knitr::knitr}
%\VignetteEncoding{UTF-8}

<<setup, echo=FALSE>>=
suppressMessages(library(mshmm)) # suppress message about Matrix and survival
library(msm)
library(knitr)
library(splines)
opts_chunk$set(tidy=FALSE, comment=NA, highlight=FALSE,
               fig.path='figures/',fig.width=7,fig.height=5.5,
               out.width="\\textwidth", out.height="!", device="pdf",
               background="#FFFFFF", cache=FALSE)

options(continue="  ", width=60)
pdf.options(pointsize=10) #text in graph about the same as regular text
table2 <- function(...) table(..., useNA = "ifany")
options(show.significant.stars = FALSE) # be statistically intelligent
palette("Okabe-Ito")
options(mc.cores= floor(parallel::detectCores()*.8)) #don't use them all
@ 

\begin{document}
\maketitle

\section{Multi-state hazard models}
The survival package deals with multistate hazard (MSH) models that are 
based on a 
non-parametric baseline hazard.
The Aalen-Johansen estimator is a the natural multi-state extension of the 
Kaplan-Meier, and the MSH models themselves
a natural extension of the Cox model.
The \code{survfit} routine produces both the KM and AJ estimates, and the
\code{coxph} function estimates both the simple proportional hazards (Cox)
MSH model fits.
We can think of these are MSH models based on observed transitions.
A basic premise of the underlying likelihood is that, over the time window
of observation for a subject, we directly observe all of the transitions 
made by that subject, i.e., what transitions and when.

The primary fitting function of this package, \code{cmsh}, deals with
MSH models that are based on intermittently observed states. 
In the simples case we will know that a particular transition must have occured
between patient visit $k$ and $k+1$ but won't know exactly when within
that interval; the transition time is interval censored. 
In the most general case the current state at 
a visit can only be assessed indirectly, leading to a multistate hidden
Markov model (MSHMM), the title for the package.  
(Footnote: we originally planned for two fitting functions, censored MSH =
cmsh for the simple cases and mshmm for the more complex; but the arguments
and computation for the two overlapped to such a great degree that one user
level function now does both; we kept the simpler name.)

\subsection{Colon cancer}
\begin{figure}
<<simpleprog, echo=FALSE>>=
pstate <- c("Entry", "Progression", "Death")
pmat <- matrix(0, 3, 3, dimnames=list(pstate, pstate))
pmat[1,2] <- pmat[1,3] <- pmat[2,3] <- 1
statefig(1:2, pmat)
@ 
  \caption{A simple model of cancer progression.}
  \label{simpleprog}
\end{figure}

A primary difference between models fit using \code{coxph} and \code{cmsh}
is that the former is focused on modeling the \emph{observed transitions},
and implicitly assumes we know when those transitions happened,
while the latter on modeling the \emph{observed state} at selected times.
Consider Figure \ref{simpleprog}, for instance, in a cancer clinical trial
where patients are followed up every 8 weeks.  
We could think of cmsh as providing a model for the time to \emph{actual}
progression and coxph a model for the time to \emph{detection}
of progression.


For a study with regular follow-up, such as a clinical trial, 
we have found that the results of a \code{coxph} and \code{cmsh} fit
are often nearly identical, particularly with respect to covariates.
If treatment decreases the rate of true progression by 30\% it will do the
same to the rate of detected progression.

\subsection{Fatty liver disease}

\begin{figure}
<<nafld, echo=FALSE>>=
states <- c("0MC", "1MC", "2MC", "3MC", "death")
smat <- matrix(0, 5,5, dimnames=list(states, states))
smat[1,2] <- smat[2,3] <- smat[3,4] <- 1
smat[1:4,5] <- 1
smat[1,3] <- smat[2,4] <- smat[1,4] <- .7
statefig(rbind(4,1), smat, alty= c(1,2,1,2,2,1,1,1,1,1))
@ 
 \caption{Transitions for the NAFLD data, 0--3 = number of the defined
metabolid comorbidites.}
 \label{fig:nafld}
\end{figure}

A more interesting case is a study of metabolic dysfunction-associated
steatotic liver disease (MASLD), which we will use below
in section \ref{sect:nafld}.
All adult subject subjects with a diagnosss of MAFLD from 1997 to 2012,
along with 4 potential controls for each case, matched on age, sex, and
year of office visit, were followed forward for
the occurence of any of 3 metabolic comorbidities (MC):
diabetes, hypertension, and hyperlipidemia.
A state space is shown in Figure \ref{fig:nafld}.
(Since comorbidities in the study were defined as 
``history of diabetes'', 
``history of dyslipidemia'', and ``history of hypertension''
no arrows go backwards.)
The follow-up visits are in the course of standard clinical care, and have
wide differences in within and between subject spacing,
with 20, 50, 80 and 95th percentiles of 3, 10, 19 and 50 months.
If there are systematic differences in visit frequency, e.g., if women saw
their physician more often on average than men,
this can introduce a bias in the coxph analysis; the interval censored
likelihood accounts for this variable spacing.

\subsection{Mayo Clinic Study of Aging}
The Mayo Clinic Study of Aging is a population based study of cognitive
change in older adults.
Starting in 2004, an age and sex stratified sample of subjects aged 70--89
was recruited from Olmsted County, Minnesota.  
Subjects are scheduled to return at 15 month intervals, at each visit they
are assessed with respect to cognitive status along with an array of other
covariates.  At regular intervals the cohort has been refreshed with new
waves of recruitement, each wave widened the age range for recruitement.
The \code{dementia} data set is a constructed data set based on a 2021
version of the MCSA data, with the same covariate, outcome, and visit 
distrbution. 
The research needs of this study have been the motivation for most of
the features in the package, and we will fit a variety of models
using the dementia data.  One simple example is shown in Figure
\ref{mcsafig1}.

\begin{figure}
<<mcsafig1, echo=FALSE>>=
mstate <- c("CU", "MCI", "dementia", "death")
mmat <- matrix(0,4,4, dimnames=list(mstate, mstate))
mmat[1,2] <- mmat[2,3] <- 1
mmat[1:3,4] <- 1
statefig(rbind(3,1), mmat)
@ 
 \caption{State space for progression of cognitive decline: states of
   cognitively unimpaired (CU), mild cognitive impairment (MCI),
   dementia and death.}
 \label{mcsafig1}
\end{figure}

\subsection{Model and notation}

One requirement for cmsh fits will be a transition matrix, e.g., the
one below for the NAFLD study.
It contains a positive value for any possible transition (usually 1), and
0 for transitions that are not.
In the NAFLD data for instance, there are subjects whose have no
comorbidities on their first visit and 2 on the next, which might be several
years later. We know, biologically, that this subject had to pass
through the 1MC state, but the program will not unless we tell it so.

<<nstatex, echo=FALSE>>=
smat
@ 

A second difference is that the cmsh routine uses a parametric baseline
hazard for each state to state transition, most often a spline function
of age or time.  As a consequence the rates include an intercept term.

A third, a probably the most profound difference is that \code{cmsh}
can accomodate partially observed outcomes.
It turns out that there is a close connection between the simple interval
censored multi-state models discussed so far, and multi-state hidden
Markov models, i.e., one can fit them both using the same underlying
function.

For some set of states we might observe only a set of
one or more imperfect biomarkers.
We might label stages of cerebral vascular damage as C0, C1, C2 and C3
for instance, where C0 is normal and C3 is severe.  
MRI based measures such as white matter hyperintensity (WMH) or fractional
aniostropy can give partial insight into the current state, with  
direct measurment only available at autopsy.

An MSH model where all the state measures are indirect is known as a hidden
Markov model: since the true state is never directly observed, the states are
 ``hidden''. 
In the wikipedia entry on HMM for instance, refers to $X$ as the
states, $Y$ the observed values and the density $f(Y|X)$ as the emission 
probability
(or $P(Y\in A|X)$ for discrete $Y$).
In our models we often have all three types of states
\begin{enumerate}
 \item Transtions where both the state and the time of
   entry to the state are known, e.g., death.
 \item Known states, where for a visit at time $t$ the current state can be
   assessed acurrately, but the time of entry to that state is not known.
 \item Hidden (latent) states, which are measured only indirectly.
\end{enumerate}

Since the majority of our models have been hybrids of the above, what one might
call a semi-hidden Markov model, we have used cmsh (censored MSH) as the
name of the primary fitting function rather than hmm. 
We will use `states' to refer to true states, some of which may be 
latent, `markers' for variables that are indirect measures of those states,
`covariates' for measured variables, e.g., sex, age,
that affect the transition rates from state to state, 
the relationship between a marker and states, or initial state for each
subject, and last a matrix of coefficients $\beta$.
Then $\eta = X\beta$ is a matrix of linear predictors, each column mapping to
some aspect of the model, e.g., a particular transition rate.  
Here $X$ is the standard $n$ by $p$ design matrix of statistics, one row
per observation, containing intercept, covariate, spline term, etc columns.

We should state at the outset that these problems are also the target of
the \code{msm} package, so why create a new one?
There are currently four primary differences between the two packages.
\begin{enumerate}
  \item From a user point of view, mshmm is designed to have similar structure
    and code to the survival package.  The two packages share a 
    primary author, who (of course) finds this style more natural.
  \item For more complex data, like the dementia example found further below in
    this vignette, the underlying optimization functions in msm were very often
    not successful at finding the maximum, and very slow when they did succeed.
    Expermentation with more robust approaches, along with a need for these 
    models within our dementia research program, 
    have been the primary drivers for the mshmm package.  
  \item Follow-up summaries of the model, e.g., mean time in state, are more
    fully fleshed out in the msm package (though we plan to improve this).
\end{enumerate}
As a user, 1 and 2 might recommend mshmm, while item 3, a longer history, and 
a deserved reputation for reliability would recommend msm.  
We emphatically do not claim that mshmm is superior. Use what works for you.
Christopher Jackson, the author of msm, has provided invaluable feedback
about techincal aspects of the models, along with comments about fits and issues
with particular data sets; both of which have been a key to the success of this
endeavor.

\section{Data}
The mshmm functions use a different shape
of input data than the multistate survfit and coxph functions in the survival
package.
The survival functions use data that has been cast into the counting process
form:
\begin{itemize}
  \item Each line has a subject id along with a time interval (t1, t2] to which
    this observation applies.
  \item Covariates apply over the entire interval, from start to finish,
    likewise for stratification variables, if present.
  \item Outcomes occur at the end of the interval.
\end{itemize}
The data for cmsh should be in \emph{timeline} form.
\begin{itemize}
  \item Each line of the data has a subject id, along with a time value
  \item Other variables on the line are information that was measured or
    known \emph{at that time point}
\end{itemize}

A timeline data set is actually more natural in the sense that it mimics the 
way in which data is gathered. 
It also may be easier to create, since one can use a wider variety of R tools.
For ordinary survival, however, a Kaplan-Meier say,
data in timeline form requires two rows of data per subject:
the first observation at time 0 will have baseline covariates along with a
status of alive; a second
observation at the time of death or last follow-up will have the status at that
time point (alive/dead).
This is different than the traditional way that survival data is coded,
i.e., a single observation with a time/status variable pair.
The multistate format for the survival package evolved out of simple survival
and so retains that instance as a special case, i.e., one line per subject
for the simple cases of alive/dead or competing risks.

A second observation is that a timeline dataset will have many missing 
values, e.g., blood pressure would not normally be known on the day of death,
 especially if death date is obtained from other sources.
One consequence is that the usual first step of other modeling functions such
as \code{lm} or \code{coxph}, i.e., to remove any data row that contains missing
values, is not taken by the cmsh function.  The handling of missings
is more nuanced.

\begin{figure}
<<nafld1, echo=FALSE>>=
nstate <- c("0MC", "1MC", "2MC", "3MC", "death")
nmat <- matrix(0, 5, 5, dimnames=list(from=nstate, to=nstate))
nmat[1, 2:5] <- c(1, .6, .6, 1)
nmat[2, 3:5] <- c(1, .6, 1)
nmat[3, 4:5] <- nmat[4,5] <-1
statefig(rbind(4,1), nmat, alty=c(1,2,1,2,2,1,1,1,1))
@
 \caption{Observed transtions in the NAFLD data}
 \label{fig:nafld1}
\end{figure}
 
In interval censored multistate data, the subjects may be observed to be in
some state $s$ at time $t$, but the the time of entry to that state is unknown.
When there is interval censoring, the user will need to create a map of
the valid transitions, as the underlying code is not able to do so with
assurance.  For example consider the data for the NAFLD study, found in 
the survival package.  
Subjects were retrospectively categorized into one of 4 states at each office
visit, with respect to the number of metabolic comorbidities (MC) that 
they had accumulated to that point; the three MC of interest are
diabetes, hyperlipiemia, and hypertension.
Figure \ref{fig:nafld1} shows the observed transtions.
A given subject might have a multi-year gap between two office visits,
leading to the accumulation of multiple MC in the interim;
these observed transitions are drawn as dotted lines in Figure \ref{fig:nafld1}.
The true transition matrix, which would be used as input 
to the cmsh function will omit the dashed lines;
it has zero for transtions which do not actually occur (biologically).

In this data set the 1MC state is interval censored: for a subject who had
none of the three conditions at their initial visit at age 56, say,
and 2 MC observed at a visit 2 years later,
we do not know exactly when that second condition arose in that interval.
For almost all interval censored data sets there is at least one state which
is not interval censored, i.e., death.  

Contrast this to simpler multi-state hazard (MSH) model as fit by coxph, where
the recorded times are taken to be the actual transtion times.
In the MSH model fit
by coxph a subject is assummed to still occupy the state of their most recent 
transtion until proven otherwise, e.g., observation of 
1MC at 3 years and a second at 10 implies 1MC at 9.999\ldots: 
there is an implicit
assumption that all transitions are observed over the time interval.
In an interval censored MSH, censoring means only ``not dead at this time''.
A subject who is 1MC at year 3 and censored at 10 could be in any of the
1MC, 2MC, or 3MC states at that later time.

Formally, the cmsh code treats a status of censored as 
``not in any state which is both exact and absorbing''. 
An exact state is one for which the time of entry to the state is known
precisely, i.e., not interval censored. The list of exact states is 
provided by the \code{exact} argument; death is the most common example.
Absorbing states can be inferred from the transitions matrix.
It is possible to have an exact state which is not absorbing, an example is the
surgical resection state in Crohn's disease \cite{Therneau2000}. 

\section{Interval censored data}
\subsection{Colon cancer trial}
The \code{colon} data set in the survival package contains the results of
a trial of three treatments for stage B/C colon cancer.
This is a simple 3 state model of entry, progression, and death.
The data set is organized with 2 rows per subject, the first containing the
progression outcome and the second the death outcome.
As a first step, however, we need to decide what to do with the 5 subjects
for which progression and death were recorded on the same day.
There is nothing wrong with this, per se: the author has for instance
had studies where progression was discovered at autopsy, and one might
reasonably expect an interval censored model to accomodate it.
However, it has been our experience that ``observation'' of two states on the 
same day is more often a data creation error, and the \code{icmsh} routine
currently flags it as such.
To resolve the conflict we will shift those progressions one day earlier.
(Or even .001 day if one wants.)
Also beware the two for whom their progression date is also their last 
follow-up time, so as not to add a superfluous ``censoring'' row at the end.

<<colon1>>=
temp1 <- subset(colon, etype==1) # progression
temp2 <- subset(colon, etype==2) # death
ties <- (temp1$time==temp2$time & temp1$status==1 & temp2$status==1)
temp1$time[ties] <- temp1$time[ties] -1 

# Make the timeline data set, we will use only a few of the predictors
#  The baseline data can use the row for either etype=1 or 2: the covariates 
#  are the identical
baseline <- subset(temp1, , c(id, rx, sex, age, node4, extent))
baseline$time   <- 0
baseline$status <- -1
prog <- subset(temp1, status==1, c(id, time, status)) # progression
dfu  <- subset(temp2, temp1$status==0 | time > temp1$time, 
               c(id, time, status)) # death or last fu
dfu$status <- dfu$status *2  # recode as 0/2
temp3 <- merge(baseline, prog, all=TRUE)
cdata <- merge(temp3, dfu, all=TRUE)
cdata$status <- factor(cdata$status, c(0, -1, 1, 2), 
                       c("censor", "stable", "progression", "death"))
subset(cdata, id<4)
@

Subject 1 has both progression and death, subject 2
is censored without progression at 3087 days.

One of the necessary conditions for a valid model, per underlying counting
process theory, is the concept of a predictable process.
In essense, an outcome observed at time $t$ cannot depend on any predictors
measured at or after time $t$. 
The cmsh function enforces this: any observed outcome on a given line of data is
predicted using information from prior rows of data.
One consequence is that prediction covariates on the final row for a subject 
have no impact. 
A second action within cmsh is to use the most recently observed value for
any predictor; it is not necessary to fill in the values for treatment, age at
entry, etc in every row of the data set.
It is a bit of a semantic argument whether each row of a timeline data set 
should contain only values \emph{measured} at that time or all
values \emph{known} at that time, i.e., whether fixed covariates like sex
should be propogated across all rows. 
The cmsh function is happy with either, and more capable data set creation tools
than the basic R merge used above may well fill these in. 

As a first look compute the transition matrix.
Then compute the probability in state and cumulative
hazard curves. Many of the survival routines can accept timeline data via
the \code{Surv2} operator.

<<coloncount>>=
survcheck(Surv2(time, status) ~1, cdata, id=id)

aj1 <- survfit(Surv2(time, status) ~ 1, cdata, id=id)
plot(aj1, col=1:3, xscale=365, lwd=2,
     xlab="Years post randomization", ylab="Current state")
legend(400, .54, c("Entry", "Progression", "Death"), lty=1, lwd=2, col=1:3,
       bty='n')
plot(aj1, cumhaz=TRUE, col=1:3, xscale=365, lwd=2,  
     xlab="Years post randomization", ylab= "Cumulative Hazard")
legend(1500, 2, c("Entry:Progression", "Entry:Death", "Progression:Death"),
       col=1:3, lwd=2, lty=1, bty='n')
@ 

In this study about 46\% (423/929) of the subjects had no transitions,
i.e., were still in the stable state at last observation, 
both death and progression was observed for 45\% (414/929).  
Only a small number died without
progression (38) or were in the progression state at last follow-up.

The cumulative hazards at 8 years are about .7, .1 and 4 for the transition
rates of entry to progression, entry to death and progression to death,
which provide reasonable starting estimates for the baseline hazards of the
interval censored fit. 
Using years as the time scale will give more interpretable coefficients, so we
add that variable.

Let us start with a simple Cox model fit to serve as comparison.
<<colonb>>=
cfit0 <- coxph(Surv2(time, status) ~ rx, data=cdata, id=id)
cfit0

dummy <- data.frame(rx=c("Obs", "Lev+5FU"))
surv0 <- survfit(cfit0, newdata= dummy, p0=c(1,0,0))
dim(surv0)
plot(surv0, lty=1:2, col=c(1,1,3,3,2,2), lwd=2, xscale=365.25,
     xlab="Years post chemo", ylab="Probabilty in state")
legend("topright", c("Stable, placebo", "Stable, 5FU+Lev", 
                     "Progression, placebo", "Progresion, 5FU+Lev",
                     "Death, placebo", "Death, 5fu+Lev"), 
       lty=1:2, lwd=2, col=c(1,1,3,3,2,2),, bty='n')
@

The hazard ratios show that combined treatment is more effective than either
Levamisole alone or placebo with respect to progression, 
and the latter two are very similar.  The predicted probability in state
curves bear this out, and have a shape similar to the Aalen-Johansen.
Since probability in state curves have to add to 1, we often leave out the
``still in initial state'' ones.
Now create the fit and plot using interval censored.

<<colon2>>=
# create the transition matrix
cstate <- c("stable", "progression", "death")
ctrans <- matrix(c(0,0,0,1,0,0,1,1,0), nrow=3,
                 dimnames= list(from= cstate, to= cstate))
ctrans
statefig(1:2, ctrans)  # visual check that it is correct
@

A transition matrix is necessary for the fit: possible transitions
are marked by 1 and invalid transitions by 0.
(The code actually allows any positive value, since the statefig routine
uses non-integer values between 0 and 2 for drawing curved connections.)

<<colon2b>>=
# Crude transitions, as a starting estimate
crude <-  c(.7, .1, 4)/(8*365)
cfit1 <- cmsh(Surv(time, status) ~ rx, id=id,  
              init=rbind(log(crude),0,0),
             qmatrix= ctrans, exact="death", data= cdata,
             mc.cores=2)
cfit1

surv1 <- predict(cfit1, type="pstate", newdata=dummy, p0=c(1,0,0),
                 time= c(1:45, seq(60, 8*365, by=60)))
plot(surv1, lty=1:2, col=c(1,1,3,3,2,2), lwd=2, xscale=365.25,
     xlab="Years from randomization", ylab="Probability in state")
legend("topright", c("Stable, placebo", "Stable, 5FU+Lev", 
                     "Progression, placebo", "Progresion, 5FU+Lev",
                     "Death, placebo", "Death, 5fu+Lev"), 
       lty=1:2, lwd=2, col=c(1,1,3,3,2,2),, bty='n')
@

The cmsh solution is not at all what we expected. The estimated treatment
coefficients are different than the Cox model and the predicted curves are
\emph{very} different: P(stable) drops almost immediately to zero. 
The issue is that we have no intermediate values in the data: there are no
observations of ``stable'' after entry, and so the best MLE estimate for an
interval censored model is to assume that subjects switch 
immediately to the progression state.
The code iterates, increasing the stable:progression rate until the first 
progression, at 8 days, has a sufficiently large estimated Pr(progression)
to declare convergence of the log-likelihood. 
This first progression on the 5FU+Lev arm, and that has the largest estimated
1:2 transition rate.  

Per reference 1 in the help file for the data, patients were
assessed for progression every 8 weeks for the first year, every 4 months for
the second year, and every 6 months for years 3 to 5.  To properly analyse
this data using interval censored methods, data rows for each of these 
intermediate visits should be included in the study data, but this data is
not available to us.
An interesting exercise is to add psuedo observations that match
the visit schedule, and observe how the estimate behaves. 
Since subjects cannot revert from progression, it suffices to add a
single pseudo visit prior each progression, e.g., id 1 had observed progression
at 968 days = 31.7 months so assume a non-progression visit 6 months before
at 786 days. (Or perhaps seven months, since people are more often late 
than early).
For progressions after 5 years we will assume yearly visits.

However, that is not enough. The multistate Nelson-Aalen hazard estimate
shown earlier does not look like constant hazard.  A somewhat ad hoc way
to show the hazard instead of the cumulative hazard is to fit it using
the smooth.spline and then plot the first derivative of the fit.

<<smoothspline>>=
xtime <- seq(0, 8*365, by=30)
scurve <- sapply(1:3, function(i) {
    smooth <- smooth.spline(aj1$time, aj1$cumhaz[,i], df=5)
    predict(smooth, xtime, deriv=1)$y
})
matplot(xtime/365.25, scurve*36525, type='l', lwd=2, col=1:3, log='y', lty=1,
        xlab="Years post randomization", ylab="Rate per 100 per year")
legend(4,20, c("Entry:Prog", "Entry:Death", "Prog:Death"), lty=1, lwd=2, 
       col=1:3, bty='n')
@ 

Since rates in the cmsh and coxph function are $\lambda(t) \exp(X\beta)$ we see 
that using a linear term $\beta_0 + \beta_1 t$ for the baseline could suffice, 
a spline would be more flexible. 
This leads to an overall hazard of 
$$
\lambda(x,t) = \exp(\beta_0 +\beta_1 t + \beta_2I(trt=2) + \beta_3I(trt=3)
$$
In an mshmm fit the underlying hazard, as a function of time, is an explicit
part of the model. This is unlike coxph where the baseline hazard function 
is implicit, and estimated non-parametrically after solving for $\hat\beta$.
For this data, treating the rate as a constant over time is not a 
satisfactory fit. This was implicitly assumed in \code{cfit1} above, but that
fit had bigger problems.

Years post follow-up is a time-dependent variable which we will need to 
explicitly manufacture and add to the data set.
Yet to do...

<<extravisit>>=
# assume progression in the first 10 weeks had no prior 'clear' visit
tdata <- subset(cdata, status=="progression" & time > 80)
pgroup <- cut(tdata$time, c(0, 80, 365+56, 730+92, 5*365+ 182, max(tdata$time)))
pgroup <- as.numeric(pgroup)
add <- subset(tdata,, c(id, time, status))
add$time <- add$time- c(0, 57, 125, 190, 370)[pgroup]
add$status <- "stable"
cdata2 <- merge(cdata, add, all=TRUE)

cfit2 <- cmsh(Surv(time, status) ~ rx, id=id,  
              init=rbind(log(crude),0,0),
             qmatrix= ctrans, exact="death", data= cdata2,
             mc.cores=2)
surv2 <- predict(cfit2, type="pstate", newdata=dummy, p0=c(1,0,0),
                  time=c(1:45, seq(60, 8*365, by=60)))
plot(surv2, lty=1:2, col=c(1,1,3,3,2,2), lwd=2, xscale=365.25,
     xlab="Years from randomization", ylab="Probability in state")
legend("topright", c("Stable, placebo", "Stable, 5FU+Lev", 
                     "Progression, placebo", "Progresion, 5FU+Lev",
                     "Death, placebo", "Death, 5fu+Lev"), 
       lty=1:2, lwd=2, col=c(1,1,3,3,2,2),, bty='n')
@

The remainder is not filled in yet (volunteers?)
\begin{itemize}
  \item Based in the cumulative hazard plot
    the years on study effect may need to be nonlinear.
  \item Compare results and curves to a multistate Cox for the same data
  \item My expectation is almost no change in hazard ratio coefficients,
    and the time to treatment failure estimate shifted 1-2 months earlier.
  \item Message: when visits are at regular intervals, there is not a great
    deal of clinical difference between the two endpoints 
    of ``time to observed progression'' and ``time to biological progression'';
    any covariate that affects one will have a similar effect on the other.
    The analyis will reflect that.
\end{itemize}    

\subsection{Fatty liver disease}
\label{sect:nafld}
 Metabolic dysfunction-associated fatty liver disease or MASLD 
(previously known as NAFLD) is characterized by fat accumulation in the liver, 
and is linked to 
metabolic dysfunction, such as obesity, type 2 diabetes, or other signs of 
metabolic dysregulation. 
Allen \cite{Allen18} collected information on
all adult subject subjects with a diagnosss of MASLD from 1997 to 2012,
along with 4 potential controls for each case, matched on age, sex, and year
of vist.  These were followed forward through the medical history 
for the occurence of any of 3 metabolic comorbidities (MC):
diabetes, hypertension, and hyperlipidemia.
A reprise of that analysis, based on the multistate mode found in 
Figure \ref{MASLD}, is found in the survival package. 

\begin{figure}
<<nafld1b, echo=FALSE>>=
states <- c("0MC", "1MC", "2MC", "3MC", "death")
nmat <- matrix(0, 5, 5, dimnames=list(states, states))
nmat[1,2] <- nmat[2,3] <- nmat[3,4] <- 1
nmat[1:4,5] <- 1
nmat[1,3] <- nmat[1,4] <- nmat[2,4] <- 0.7
statefig(rbind(4,1), nmat, alty=c(1,2,1, 2,2,1,1,1,1))
@
 \caption{Observed transitions for the MASLD data}
 \label{MASLD}
\end{figure}

<<echo=FALSE>>=
# for the sentences below
i1 <- duplicated(nafld2$id, fromLast=TRUE)
i2 <- duplicated(nafld2$id)
idata <- data.frame(id= nafld2$id[i1],
                    interval= nafld2$days[i2] - nafld2$days[i1])
idata <- subset(idata, interval >7) # don't count two test on the same visit
qq <- quantile(idata$interval, c(.2, .5, .8, 1))/30.5
@ 

If measured continuously, subjects would progress via the solid arrows from 0 
to 1 to 2 to 3 comorbidities;
we assume that no one progresses on two of the markers at the 
\emph{exact} same instant.
However, the interval between clinical visits varies considerably from
subject to subject and visit to visit, with 20, 50 and 80th percentiles
of 3, 9, and 18 months (max 245).
If there are systematic differences in visit frequency, e.g., if women saw
their physician more often on average than men,
this can introduce a bias in the coxph analysis and cmsh may be more
appropriate for that reason alone.

In the observed data, there will be subjects who are in the 0MC
state at one visit, and in the 2MC state at their next visit; as that following
visit might be several years later.  Such visit pairs are shown as dashed
lines in Figure \ref{fig:nafld}.
A fit based on observed transitions, using coxph, will model all observed
transitions, including these jumps. 
One based on the interval censored model will model only the solid arrows,
i.e., the transitions that actually occur.
(Footnote: since comorbidities in the study were defined as 
``history of diabetes'', 
``history of dyslipidemia'', and ``history of hypertension''
no arrows go backwards.)

Like the colon cancer example above we need to include intermediate
visits. The survival package's NAFLD data consists of 3 data sets: 
baseline information
with one row per subject (\code{nafld1}), outcome information (\code{nalfd3}),
and a third with selected office and/or laboratory values for each visit.
In order to construct the interval censored data we will assume that each
office visit represents a potential observation time for progression of
the comorbidities.  The metabolic comorbidity status at a subsequent 
death/last known alive date is not known, however.

Now create the timeline data set.
For illustration we have done this using only the functions in base R, 
but several other, more sophisticated tools can be used.
A couple of notes:
\begin{itemize}
  \item The code \code{index <- match(id, id)} is an old programming trick
    in R (and in S-Plus and S before that). It creates an index that points
    each row of data to the first row with that id value.
  \item In general, in a timeline data set the first row for each subject
    will have few if any missings.
\end{itemize}
<<nafld2>>=
# baseline visit
base <- subset(nafld1, select=c(id, age, male, case.id))
base$days <- 0
base$nafld <- with(base, 1*(!is.na(case.id) & id==case.id)) #nafld at baseline
base$case.id <- NULL  # no longer needed

# cumulative MC count
# times <=0 in nafld3 are conditions found at or before enrollment date
# create the "number of comborbidities so far" variable
temp2 <- subset(nafld3, event %in% c("diabetes", "dyslipidemia", "htn"),
                c(id, days))      # only events of interest
temp2$days <- pmax(0, temp2$days) # set prior events to day 0
#cumulative count
findex <- match(temp2$id, temp2$id)
temp2$mc <- 1+ 1:nrow(temp2) - (1:nrow(temp2))[findex]
# keep the last of any rows that are tied on id and days (2 MC on same visit) 
temp2 <- temp2[!duplicated(temp2[,1:2], fromLast=TRUE),]

lfu <- subset(nafld1, select= c(id, futime, status)) # death or last fu
names(lfu)[2] <- "days"

ndata1 <- merge(base, temp2, by=c("id", "days"), all=TRUE) # other variables
ndata1 <- merge(ndata1, lfu,   by=c("id", "days"), all=TRUE)# add futime

# everyone needs a starting MC state
ndata1$mc[!duplicated(ndata1$id) & is.na(ndata1$mc)] <- 0
# ndata1 is a timeline data
# manufacture the state variable, as a factor suitable for Surv
temp <- with(ndata1, ifelse(!is.na(mc), mc+1,
                    ifelse(!is.na(status) & status==1, 5, 0)))
ndata1$state <-factor(temp, 0:5, 
                      c("censor", "0MC", "1MC", "2MC", "3MC", "death"))

# print out the transition matrix
survcheck(Surv2(days, state) ~1, ndata1, id=id)$ transitions

# Add in the office visits. There will occassionally be labs on sequential
#  days for the same visit, but it isn't worth removing these "duplicate" visits.
# But do remove two tests on the same day.
office <- subset(nafld2, days>0, c(id,days))
office <- office[!duplicated(office),]   # tests on the same day
ndata2 <- merge(ndata1, office, by=c("id", "days"), all=TRUE)
ndata2$state <- lvcf(ndata2$id, ndata2$state)

# The new transition table
survcheck(Surv2(days, state, repeated=TRUE) ~1, ndata2, id=id)$transitions
@ 

We see that data set \code{ndata1} has the exact same off-diagonal counts
nas the expanded data set \code{ndata2}, this is as it should be.
The second data frame adds 0MC:0MC, 1MC:2MC, 2MC:2MC and 
3MC:3MC transitions, all of which serve to narrow the time range over
which a given transition between states will have occured. 
A printout for id 1 shows 0MC visits at 0, 183, 2030, 3578 and 5420 days.
Because there are no backwards transitions we could delete the middle rows, as
0MC at day 0 and 0MC at day 5420 implies 0MC throughout the interim.
The likelihood will be the same without the middle rows, and computation a
smidge faster.  Deletion is not valid, however, if 0MC:1MC and
1MC:0MC transitions were possible.  Think hard before thinning a data set.

<<duprow>>=
# Actually, there are a lot of unneeded rows.  Since there are not any
# TD covariates it is easy to count: the first row of a repeated pair adds
# no further information (except the first row)
isdup <- with(ndata2, diff(id)==0 & diff(as.numeric(state))==0)
isdup <- c(isdup,FALSE) & duplicated(ndata2$id)
table(isdup)
ndata2 <- ndata2[!isdup,]
@
 
As is often the case, the above seemingly simple section of code to create
the analysis data set required
more time and effort than the analysis that appears below.
It is imperitative to create the table of transtions, look at it, and think
about it. The row for death for instance should always be 0.
(Make sure to include missings in any tables, we defined a \code{table2}
function at the start of this vignette to avoid having to type the
\code{useNA= 'ifany'} option again and again.)
Print out final data for a half dozen subjects and READ it. 

One more step is needed, which is to add current age as a time-dependent
covariate. The underlying rate of MC rises very rapidly with age, and this
data set covers a wide range.  The figure below shows the distributions of 
initial age and years of follow-up. 
Using only baseline age as a covariate would imply that for two subjects, both
currently age 85, one who entered the study at age 70 and the other at age 80,
that the current death rate is lower for the earlier recruit.
For the coxph model we are able to use age as the time scale, which causes
this careful matcing to happen silently behind the scenes, but the cmsh
routine has a parametric baseline and needs an explicit
current age variable.

Why did we choose to make 1 year age intervals?
Several centuries of experience with population rate tables, e.g., the 
US death rates found in survival::survexp.us or more generally those
available from the Human Mortality Database (www.mortality.org) have shown
that, other than for infants, yearly event rates provide a sufficiently fine
division of age. For this data a coarser grid would almost certainly
be acceptable, e.g., every 5 years of age, but we have chosen the classic 
strategy.

<<nafldyrs, echo=FALSE>>= 
opar <- par(mfrow=c(1,2), mar=c(5,5,1,1))
hist(nafld1$age, nclass=25, main=NULL, xlab="Starting age")
hist(nafld1$futime/365.25, nclass=25, main=NULL, xlab="Years of FU")
par(opar)
@

<<nafld3>>=
# create a dummy data set with integer ages
# (pretend they had shown up each birthday, but we only recorded "alive")
acount <- floor(nafld1$futime/365.25) # number of extra ages to add
itemp <- unlist(lapply(acount, function(i) 0:i))
dummy <- data.frame(id= rep(nafld1$id, 1+ acount), days=round(itemp*365.25),
                    iage = itemp) 
# merge it in
ndata3 <- merge(ndata2, dummy, by=c("id", "days"), all=TRUE)
ndata3$state[is.na(ndata3$state)] <- "censor"
ndata3$age <- lvcf(ndata3$id, ndata3$age)
ndata3$iage<- lvcf(ndata3$id, ndata3$age + ndata3$iage)
subset(ndata3, id==4)
@

The resulting data set has rows for both the visits, which have a state of
0MC--MC3, rows for the deaths, 
and rows for each age change, which have the generic state ``censor''
since the true state was not observed at that point.
Current age is a time-dependent covariate. We will discuss issues with 
general time-dependent covariates later, but age and time since enrollment
are much simpler than others, since their value at any time is known a
priori, without requiring measurement at a patient visit. 
The reason for integer age will appear at the first theory discussion.

As a final check of the data set use it to create Aalen-Johansen curves.
The Aalen-Johansen fit does not account for interval censoring, so can
use Surv2 and \code{ndata1}, the data before adding the office visits or
time-dependent age. Below is the code which generates figure \ref{nafldaj}.
The resulting compuation will have hazards for both the solid and dashed line 
transitions of Figure \ref{MASLD}, but we have chosen to display only the
solid ones.  The right hand panel has a line for each state.
The hazard plot shows higher transition rates for the MC transitions than for
death, and rough linearity. 
The $p(t)$ plot shows the gradual cascade through 0--3 MC. 
As stated just above, a primary purpose at this point was as a data check.

<<nafldfit1>>=
ndata3$years <- ndata3$days/365.25
ndata1$years <- ndata1$days/365.25

# create the current age variable
index <- match(ndata1$id, ndata1$id)
ndata1$age <- ndata1$age[index] + ndata1$years

ajfit1 <- survfit(Surv2(years, state) ~ 1, ndata1, id=id)
#age scale
ajfit2 <- survfit(Surv2(age, state) ~1, ndata1, id=id, start.time=50,
                  p0=c(1,0,0,0,0))
@

\begin{figure}
<<nafldaj, echo=FALSE>>=
opar <- par(mfrow=c(1,2), mar=c(5,5,1,1))
plot(ajfit1, cumhaz=c(1,3,6:10), col=1:7, lty=rep(1:2, 3:4),
     xlab="Years", ylab="Cumulative hazard")
legend("topleft", c("0MC:1MC", "1MC:2MC", "2MC:3MC",
                    paste0(0:3, ":death")), col=1:7, lwd=2, 
       lty=rep(1:2, 3:4), bty='n')

plot(ajfit2, col=1:6, lty=1, lwd=2,
     xlab="Age", ylab="Probability in state")
legend(61, 1, c(paste0(0:3, "MC"), "death"), col=1:6, lty=1, bty='n')
par(opar)
@
 \caption{Left panel: estimates of the cumulative hazard for selected
   transitions.  Right panel: estimated $p(t)$ for subject starting in
   the 0MC state at age 50.}
 \label{nafldaj}
\end{figure}

For the actual model fit we need initial values for the parameters.
I have found to my dismay that I don't do a very good job of picking initial
coefficients when there are covariates.  The estimates
actually don't need to be that good, just ``in the ballpark'', but 
it is easy to create starting values that give crazy per-subject starting rates.
A good idea appears to start with a model that has only the intercept, 
or intercept + age, either of
which might be thought of as the ``null model''.
For the former we can use the slope of a cumulative hazard plot such
as figure \ref{nafldaj}, for the latter a simple Poisson glm model for death
has been effective. 

<<nafldfit1b>>=
gdata <- data.frame(ndata3,
                    delta = diff(c(0, ndata3$years)))
gdata <- subset(gdata, duplicated(id))
glmfit <- glm(state=='death' ~ iage + offset(log(delta)), poisson, data=gdata)
icoef <- outer(coef(glmfit), rep(1,7), '*')
# optional refinement based on the figure, MC:MC rates are 3x death
# icoef[1,1:3] <- icoef[1, 1:3] + log(3)

states <- c(paste0(0:3, "MC"), "death")
nmat2 <- matrix(0,5,5, dimnames= list(states, states))
nmat2[1,2] <- nmat2[2,3] <- nmat2[3,4] <- 1
nmat2[1:4,5] <- 1
nmat2

#if (file.exists("nfit0.rda")) {
#    load("nfit0.rda")
#} else {
    nfit0 <- cmsh(Surv(years, state) ~ iage, ndata3, id= id,
                  qmatrix= nmat2, init= icoef)
    nfit1 <- cmsh(list(Surv(years, state) ~ iage + male + nafld,
                   0:5 ~ male/common), 
                  ndata3, id=id, qmatrix=nmat2, init=nfit0)
    save(nfit0, nfit1, file= "nfit0.rda")
#}
nfit0
nfit1
@

Now compare this to the MSH fit treating transition times as exact.
<<nfit2>>= 
nfit2 <- coxph(list(Surv2(age, state) ~ male + nafld,
                    0:5 ~ male/common,
                    1:2 + 1:3 + 1:4 ~ male + nafld/common,
                    2:3 + 2:4 ~ male + nafld/common),
               ndata1, id=id)
nfit2

# Hazard ratio plot
xx <- summary(nfit2)$conf.int[, -2]
yy <- c(1,3,5,7, 2,4,6,8:11)
opar <- par(mar=c(5,6,1,1))
matplot(xx, yy, log='x', type='n', xlab="Hazard Ratio", ylab="", yaxt='n')
points(xx[,1], yy, pch=19) #, col=rep(2:1, c(4,7))[yy])
segments(xx[,2], yy, xx[,3], yy)
abline(h=4.5, lty=2)
text(c(1, 1), c(3, 7), c("Male", "NAFLD"))
nstate <- nfit1$states
temp <- c(paste(nstate[1:3], nstate[2:4], sep=":"))
ylab <- c(temp, "death", temp, paste(nstate[1:4], "death", sep=':'))
axis(2, 1:11, ylab, las=2)

# I don't want the intercept or age coefs
index <- unique(c(nfit1$cmap[3:4,]))
tempse <- sqrt(diag(solve(nfit1$fit$S2)))  # theory is still weak
xx2 <- exp(coef(nfit1)[index] + outer(tempse[index], c(0, -1.96, 1.96), '*'))
delta <- .15
points(xx2[,1], yy+ delta, col=2, pch=15)
segments(xx2[,2], yy+delta, xx2[,3], yy+delta, col=2)
par(opar)
@

Now compare the predictions.
<<ncurves>>=
ndummy <- expand.grid(male=0:1, nafld=0:1)
pcurve1 <- predict(nfit1, type='pstate', newdata=ndummy,
                   time=list(iage=50:100), p0=c(1,0,0,0,0))
pcurve2 <- survfit(nfit2, newdata=ndummy, start.time=50,
                   p0=c(1,0,0,0,0))

# compute the sojourn for pcurve1 (1 year intervals makes it easy)
sojourn1 <- apply(pcurve1$pstate[1:50,,], 2:3, sum)
temp2 <- summary(pcurve2, rmean=100)$table
sojourn2 <- matrix(temp2[,3], 4, 5)
ii <- c(1,2, 4, 3)
temp <- t(rbind(sojourn1[ii,], sojourn2[ii,]))
# colnames(temp) <- rep(c("F-", "M-", "M+", "F+"),2)
z <- barplot(temp, horiz=T, 
        col=c(c(4,3,5,2), 0), border=NA, xlab="Years remaining",
        space=c(.1,.1, .1, .1, .5, .1, .1, .1))
axis(2, c(2,7), c("State", "Transition"))
box()
text(rep(37,8), z, rep(c("F-", "M-", "M+", "F+"),2))

opar <- par(mfrow=c(2,2))
tlab <- paste(c("Male", "Female")[1+ndummy$male],
              c("Control", "Nafld")[1+ndummy$nafld])
for (i in 1:4) {
    plot(pcurve1[1,1:2], col=1:5, lty=1, lwd=2, 
         xlab="Age", ylab="Prob in state", main=tlab[i])
    lines(pcurve2[1,1:2], col=1:5, lty=2, lwd=2)
    
}
par(opar)

@ 
 
Yet to do:
\begin{itemize}
  \item Note that nfit0 can be slow: initial estimates are hard
  \item Compare predicted p(t) and E(time in state) estimates
  \item Come to some conclusions
\end{itemize}

\section{Theory, pass 1}
A big difference between coxph and cmsh is how the likelihood is constructed.
The semiparametric MSH (coxph) is a model for observed \emph{transitions}, 
while the interval censored (cmsh) approach is a model for observed
\emph{states}.
The semiparametric model assumes that we see all of the transitions, up to
the point they are censored.  It uses those transition and their timings,
via risk sets, to construct estimated rates. 
These rates can the be used to compte probability in state curves $p(t)$.

Let $R(t)$ be the multistate rate matrix at time $t$.
Off diagonal element $R_{ij}(t;x) = \hat\lambda{ij}(t;x)$ contains the estimate 
transition rate between state $i$ and state $j$, at time $t$, for a subject
with covariate vector $x$.  
To normalize $R$ set its diagonal element such that row sums are 0. 
(This is just what has to be done to compute the matrix exponential, no serious
theory is involved wrt the normalization step.)
If we assume a set of time points 
$t_0, t_1, t_2, ...$ such that the transition rates are constant over each
interval $t_i \le t < t_{i+1}$ the the probability in estimate satisfies
\begin{equation}
 p(t_i; x) = p(t_0) e^{(t_1-t_0)R(t_0;x)} e^{(t_2-t_1)R(t_1;x)} \ldots 
 e^{(t_i-t_{i-1})R(t_{i-1};x)} \label{simplehmm}
\end{equation}
where $p(t)$ is a vector with one element per state, $p_k(t)$ the probability of
being in state $k$, and $p(t_0)$ is the probability vector for the starting
state, normally all zeros with a single ``1'' corresponding to the starting 
state.
The exponential of a matrix, e.g. $\exp(R)$, is dealt with at length in the
mathematics vignette. Suffice it to say that compuation of this quantity, and
of its derivative, is more complex than the exponential of a single value
\cite{Moler78, Moler03, Mohy09}.

In the semiparametric MSH first the parameter estimates $\hat\beta$ are 
computed based on a partial likelihood, predictions $p(t;z)$ for any chosen
covariate vector $z$ are computed at the very end.
In the interval censored MSH $p(t;x)$ is computed during maximization, that is,
for each trial solution of $\hat\beta$ and each subject $i$
\begin{enumerate}
  \item Compute the predicted curve $p(t;x_i)$ for the subject. For the moment
    assume the covariate $x_i(t)$ is not time-dependent.  That will be a later
    topic.
  \item Compare the prediction to the observed state for subject $i$, at each
    observation time $t_{ij}$ for that subject.
  \item Use this to compute an updated $\hat\beta$.
\end{enumerate}

The computation of a likelihood in cmsh is a sum over subjects, 
and each subject can be computed independently.  (We take advantage of this
and use parallel computation if possible, either set \code{mc.cores} using 
\code{options}  or include it in the cmsh call.)
The algorithm for the likelihood of each subject alternates two steps.  
First step forward to a new
time point using the matrix exponential as in equation \eqref{simplehmm}.
Whenever a subject is observed, restrict their $p(t)$ by setting to 0 all of the
``states where they ain't'', i.e., all elements of $p$ except the 
observed state.
The mathematics vignette has more formal details.

\section{Partially observed states}
\begin{figure}
<<mcsa1, echo=FALSE>>=
mstate <- c("CU", "MCI", "dementia", "death")
mmat <- matrix(0, 4, 4, dimnames=list(mstate, mstate))
mmat[1,2] <- mmat[2,3] <- 1
mmat[1:3,4] <- 1
statefig(rbind(3,1), mmat)
@  
 \caption{State space model for the dementia data.}
 \label{mcsastate}
\end{figure}

The simplest extension of the simple interval censored model, and the simplest
hidden Markov model, involves a partially observed state.
An example appears in the Mayo Clinic Study of Aging, represented in the
\code{dementia} data set.
Jack et al \cite{Jack25} looked at a simple model of time to detection of
of MCI and/or dementia, as shown in figure \ref{mcsastate}.
However, for some visits the formal cognitive testing necessary to distinguish
mild cognitive impairment (MCI) is not available, at those visits subjects
are classified as non-demented or dementia.

The modification of the likelihood is simple.  At such a visit, if the
diagnosis is ``dementia'', then all elements of $p(t)$ for that subject, except
state 3 (dementia) are set to 0.  For a non-demented diagnosis, elements 3
and 4 (dementia and death) are set to 0, the other two are unchanged.
We treat the off study diagnosis as a \emph{marker}, our
label for an imperfect assessment of the underlying state.
The data will have three distinct outcome variables: death, observed state
at a study visit, and partial state at an ordinary office visit. 

<<dement1>>=
survcheck(Surv2(age, dx) ~1, id=ptnum, data = dementia)

survcheck(Surv2(age, dx, repeated=TRUE) ~1, id=ptnum, dementia)$transitions
@

As described in the help file for the data set, the on study, off study
and death data have been collapsed into a single variable \code{dx}.
The above table of transitions shows that it not uncommon for a patient's
diagnosis of MCI at one visit to revert back to CU at a later one.
If we fit a model corresponding to Figure \ref{mcsastate} using this
raw data, the result will be an estimated likeihood of 0, whic would
be correct since the data contains an impossible (per the diagram)
transition.

A message which will be repeated multiple times is that you need to
create the transitions table and \emph{read} it.  Really read it, not
just a glance.  There are several things we can note from the above.
\begin{itemize}
  \item The \code{survcheck} routine was written for counting process data.
    One aspect of Surv2, which translates from timeline form to that form,
    is the repeated argument.  When a subject has two sequential visits in
    the same state, the survfit and coxph routines need to know whether to
    treat the second observation as a new event. Most of the time they
    should not, repeated infections in the CGD data set is a counterexample,
    however.  In this data each row is a visit, the repeated form clearly shows
    that over half of all visit pairs are CU:CU; most patients stay stable for
    many years before progression.  The (any) row of the total visits table
    shows that 53\% (2296/4327) have no recorded transtions during follow-up.
  \item There are 30 instances of a CU:dementia pair.  Per the model we assume
    that these subjects passed through MCI, we simply did assess them often
    enough to observe the transient MCI state.
  \item Dementia:MCI is much less common than MCI:CU.  This reflects on one
    hand the clinical reality that CU and MCI are more difficult to distinguish
    than dementia, and also fewer overall dementia cases.
  \item There are no transitions from death to another state, or from
    death to censored (further follow-up after death).  This is as it
    should be.
  \item Off study dementia only transitions to death. This is because
    further record reviews are not scheduled for demented subjects.
  \item There are no transitions from nondem to nondem or off-dem. 
    This is, it turns out, an interesting artifact of how the online
    data collection system was designed.
    The nurse abstracters who review the history have a screen with fields
    for ``last assessment date for dementia' and 'dementia yes/no'.  
    At a second, third, etc review for a patient, should one occur,
    the contents of these are overwritten; thus the master data set
    at any given time only has the most recent value.
  \item More dementias were found in record review than in study visits.
    We believe that this reflects informative censoring: subjects whose
    cognition is slipping selectively drop out, i.e., exactly those most
    likely to receive a dementia diagnosis at their next visit. 
  \end{itemize}
Every real study has unique features and patterns like this.  Something that
looks odd, e.g., item 6 above, needs to be thought through: the ``feature''
you are seeing may often be your own programming error. 
The author's experience has normally been that the total number of calls to
survcheck (and other tabulations) while building a proper analysis data
set will exceed the number of model fits performed when using that data set.

For this desired analysis we need to create two new variables
\begin{itemize}
  \item Sequential progression: the first diagnosis of MCI, dementia (or death)
  \item Off study diagnosis
\end{itemize}
The first is treated as a known state, the second as a marker. 
Misclassification will be explored later in the document.

<<dementdata1>>= 
table2 <- function(...) table(..., useNA= "ifany")  # show NA in tables

noback <- function(x, id, censor) {
    # turn reverse transitions into 'stayed the same'
    # assume the data is sorted by time within unique id, each unique id
    #  is a block (but id labels not necessarily in sorted order)
    ix <- ifelse(is.na(x), -1, as.numeric(x)) # placeholder
    if (!missing(censor)) ix[x==censor] <- 0  #make it the smallest level
    new <- unlist(tapply(ix, match(id, unique(id)), cummax))
    # A censored row can occur any time, not subject to the "only up" rule
    if (!missing(censor)) {
        if (is.factor(x)) new[x==censor | is.na(x)] <- match(censor, levels(x))
        else new[x==censor | is.na(x)] <- censor
    } else new[is.na(x)] <- NA

    if (is.factor(x)) 
        new <- factor(new, 1:length(levels(x)), levels(x))
    else new
}

# first restrict the set of states, then stop backwards transitions
temp <- factor(dementia$dx, c("alive", "CU", "MCI", "dementia", "death"))
ddata <- dementia
ddata$maxdx <-noback(temp, ddata$ptnum, "alive")
ddata$offdx <- factor(as.numeric(ddata$dx), 5:6, c("ND", "dementia"))
with(ddata, table2(dx, maxdx))
with(ddata, table2(dx, offdx))
ddata$iage <- floor(ddata$age)

# The missclassification table for off study dx
missmat <- matrix(c(1,1,0,0,0,1), ncol=2,
              dimnames=list(c("CU", "MCI", "dementia"), c("ND", "dementia")))
missmat

# The true transition matrix
mstate <- c("CU", "MCI", "dementia", "death")
mmat <- matrix(0, 4, 4, dimnames=list(mstate, mstate))
mmat[1,2] <- mmat[2,3] <- 1
mmat[1:3,4] <- 1
mmat

# Initial absolute rate that is "in the ballpark"
drate <- survexp.us[75, 1, "2010"]* 365.25  # death rate per year, 75 year old
icoef <- rep(log(drate),5)

dfit0 <- cmsh(Surv(age, maxdx) ~ 1, 
              data= ddata, id= ptnum, qmatrix= mmat,
              init = icoef, exact="death",
              marker= list(state("CU", "MCI", "dementia"):offdx ~0 
                           /discrete(init=missmat)))
dfit0$fit$iter
dfit0


# Add covariates
dfit1 <- cmsh(list(Surv(age, maxdx) ~ iage, 
                   1:2 + 2:3 ~ any.e4,
                   0:4 ~ male /common), 
              data= ddata, id= ptnum, qmatrix= mmat,
              init= dfit0, exact= "death",
              marker= state("CU", "MCI", "dementia"):offdx ~0 
                           /discrete(init=missmat)
              )
dfit1$fit$iter

@ 

There is a lot to unpack in the above example.
\begin{itemize}
  \item The use of first observed MCI and first observed dementia as our
    endpoint simplifies the model. 
    This endpoint may be of medical interest in and of itself, as
    it corresponds perhaps more closely to clinical practice than the
    ``true MCI'' we will estimate a little later.  The first diagnosis of MCI
    may for instance be the basis for treatment decisions.
  \item The (declared to be) true transition matrix, \code{mmat} above,
    guides the underlying model fit. It is not optional.
  \item The formula statement is a list, the first element of the list is
    the default formula, which serves as the starting point for all model
    transitions (the 5 arrows in Figure \ref{mcsastate}).  Subsequent rows
    modify the formulas for one or more of those five.  1:2 stands for the
    transition from state 1 to state 2, numbers correspond to the rows/cols
    of the transition matrix \code{mmat},
    \verb+'CU':'MCI''+ is equivalent to 1:2.
    0:5 is shorthand for ``any state'':5, in this case all
    3 transtions to death have male sex as a covariate, and all share the
    same coefficient. 
  \item The default initial value of 0 for all coefficients may often not
    work for the intercepts.  It corresponds to a mean time to transition
    of log(2)/1 = .7 units of time. If the time axis were in days, for instance,
    the log-likelihood at $\beta=0$ can be so small that the exp() function
    underflows, giving a probability of exactly 0 and correponding
    log-likelihood of log(0).  The routine may occasionally recover from such
    a bad starting point, or may not.
\end{itemize}

The \code{marker} statment gives a mapping between a subset of states and
a measured but imperfect marker of those states.
The form state:marker reflects that underlying probability model is based on 
Pr(observed value $|$ state), not Pr(state $|$ observation).  
The missclassification matrix \code{mmat} has three rows and each row is
a probability distribution, each has to add to 1.  We read it as
\begin{itemize}
  \item If the true state is CU and the marker offdx is observed, then
    probability(offdx = ``ND'') =1
  \item If the true state is MCI and the marker offdx is observed, then
    probability(offdx = ``ND'') =1
  \item If the true state is demenentia and the marker offdx is observed,
    then probability(offdx== ``ND'') =0
  \item There is no row for death, for two reasons. The first is that if
    death is observed at a given date, we will not have observed a
    nondemented/demented status on that same date, thus
    the case does not arise.  The second is to ask what numerical value one would
    put in that row, given the constraint that it should add to 1?
  \item It is of course possible for someone to have had an office visit and
    evaluation, then die in a car accident that same day on the way home.
    When there is a tied time like this, our experience is that P(data error)
    is by far the most likely case.  If such a case did occur, then
    to avoid complaints from the code
    the user will need to break the tie, e.g., make the office visit 
    .1 day earlier or some such.
    \end{itemize}
The \Sexpr{~0} portion of the formula states that there are no estimated
coefficients for this markere, and is
followed by the distribution and parameters of the distribution.

The \code{msm} package takes a different approach to the case of partially
observed states as shown below.

<<msmfit1>>=
istate <- with(ddata, ifelse(is.na(offdx), as.integer(maxdx) -1L,
                 c(5,3)[as.integer(offdx)]))
table2(ddata$dx, istate) #1,2,3,4 have to line up with qmat
qmat <- mmat
qmat[qmat>0] <- drate # initial values for the intercept
otype <- ifelse(ddata$dx=="death", 3,1)
mfit0 <- msm(istate ~ age, data=ddata, subject= ptnum, death=4,
             qmatrix=qmat, obstype=otype,
             censor=c(0,5), censor.states=list('0'= 1:3, '5'=1:2))
rbind(cmsh= exp(coef(dfit0)), msm= mfit0$Qmatrices$baseline[qmat>0])
# essentially the same solution
@ 

The censor and censor.states arguments identify outcomes in istate that map
to multiple states, and everything else is assumed to be exact.
This approach does not extend to more general missclassification matrices.

Over half the compute time for cmsh is spent in the matrix exponential.
For a small set of state patterns msm has coded special routines for the
matrix exponential, and in those cases is can be significantly faster 
than cmsh.

\subsection{CAV example}
Data from a study that monitors the progression of coronary allograft
vasculopathy (CAV) is provided in the msm package. 
CAV is a post-transplant deterioration of the aterial walls in patients who
have recieved a heart transplant. 
Make a few changes to
the data set to set it up for the cmsh function, and show some summaries. 
First fit CAV outcome as interval censored. 

<<newcav>>=
cav2 <- msm::cav
names(cav2) <- casefold(names(cav2))  # lower case (personal preference)

# The model
cstates <- c("no CAV", "mild/mod", "severe", "death")
cqmat <- matrix(0, 4, 4, dimnames=list(cstates, cstates))
cqmat[1,2] <- cqmat[2,1] <- cqmat[2,3] <- cqmat[3,2] <- 1
cqmat[1:3,4] <- 1
statefig(rbind(3,1), cqmat, offset=.02)

#  multi-state status for Surv(), first level has to be "no event at this time"
cav2$cstate <- factor(cav2$state, 0:4,  
                      c("alive", "no CAV", "mild/mod", "severe", "death"))
table(cav2$cstate)       # no off study FU!
survcheck(Surv2(years, cstate) ~1, cav2, id= ptnum)
table(table(cav2$ptnum)) # number with 1, 2, 3, ... visits
@

We use a standard multi-state Surv(time, state) form of the survival
package, where the state variable is a factor such that
the first level of the factor represents ``no event at this time''.
The CAV data is unusual in that there are no censored observations, 
each interval ends in one of the 4 states.
The 622 subjects have betwen 2 and 15 assessments, 27\% with 2 and 21\% with 3.
The transitions table above shows the count of observed transtition pairs, a 
subject with 5 visits will contribute 4 counts to the table.
Remaining in the no CAV state accounts for the largest number of visit
pairs. As should be the case, there are no transitions from death to another
state.

As seen below, the inter-visit intervals vary widely, a situation that favors
an interval censored model.  

<<cinterval>>=
# what are the inter-visit intervals?
i1 <- duplicated(cav2$ptnum, fromLast=TRUE)
i2 <- duplicated(cav2$ptnum)
interval <- cav2$years[i2]- cav2$years[i1]
ideath <- cav2$cstate[i2]=="death" # did the interval end in death?
#between visits
hist(interval[!ideath], nclass=50, main=NULL,
     xlab="Time between consecutive visits (years)")
#hist(interval[ideath], nclass=30, main=NULL,
#     xlab="Years between last visit and death")
@

For interval censored data we need to specifiy the set of
valid transitions $Q$.  This is a matrix of 0/1 values, which can
also be used by the statefig routine. 
The row/column names of the transition matrix are the names of the states,
levels in the Surv object need to match these.
<<cavstates>>=
cqmat

cfit0 <- cmsh(Surv(years, cstate) ~ 1, data= cav2, id= ptnum,
               qmatrix= cqmat, exact="death")
cfit0  #msm vignette, 2.5, model 1
@

For the above model states are of two types: the
state is known at the measurment time but not when that state was entered,
and exact states, where the entry time to the state is known. These latter
are enumerated in the \code{exact} argument.
Death is the most common exact state.   
One can also have multiple exact states, one of the more common examples 
is cause of death, e.g., states of `death due to cancer' and `other death'
had been separated by the user.
The status variable in the Surv call is a factor with censored as the
first level, followed by the states, in the same order as the $Q$ matrix.
Now add covariates.

<<cav2>>= 
cfit1 <- cmsh(list(Surv(years, cstate) ~ 1, 
                  1:2 + 1:4 ~ sex),
             data=cav2, id= ptnum, init= cfit0,
             qmatrix= cqmat)
cfit1  # msm vignette, 2.7, model 2a
@

The code allows the use of a prior model for the initial values.
Interestingly, the number of iterations needed to estimate the initial
intercept was larger than for \code{cfit1}. This is not uncommon, in
our experience.

<<cav2b>>=
cfit2 <- cmsh(list(Surv(years, cstate) ~ dage, 
                  1:2 + 2:3 ~ sex / common,
                  2:1 + 3:2 ~ sex / common,
                  0:death   ~ sex / common),  data=cav2, id= ptnum,
             qmatrix= cqmat, exact="death", init=cfit0)
cfit2  

cfit2$cmap
@ 

More complex models are specified using a list for the formula argument.
The first formula in the list specifies the response and a default set of
covariates which is used as the starting point for all transtitions.
In the above example age at diagnosis \code{dage}.
Later formulas update the formula(s) for specified transtions
\begin{itemize}
  \item line 2 of cfit1 adds sex to the formulas for none to mild (1:2) and
    none to death (1:4), but not to other transitions
  \item line 2 of cfit2 forces the the 1:2 progression
    (no CAV to mild/moderate) and 2:3 (mild/moderate to severe) to share a
    common sex coefficient
  \item line 3 of cfit2 makes the sex coefficients for the two reverse 
    transitions identical
  \item 0:death stands for any state to death. Transitions marked as 0 in
    qmatrix are ignored whenever exanding a shorthand like this, i.e., 
    a death:death transtion
\end{itemize}

The \code{cmap} component of the returned fit is the overall map between
covariates, linear predictors, and coefficients.
The final fit has 17 unique coefficients, the linear predictor for the 3:4
(severe:death) transition for example makes use of coefficients 16, 17 and 13.

\section{What is a hidden Markov model (HMM)?}
The answer to this is that HMM is a general technique, and we see the
label applied to many different problems in many different subfields.
The cmsh package addresses a particular structure, one that has been useful
in our analyses of data from the Mayo Clinic Study of Aging (MCSA).

Our models can be thought of having two levels.  Level 1 is a multi-state
hazards model, much like those addressed by multistate hazard (MSH) models
fit using the coxph function in the survival library.
Here is a moderately complex model for illustration, based on a dementia study. 
<<states>>=
states <- c(outer(paste0("A", 0:1), paste0("C", 0:2), paste, sep='.'), "death")
statedata <- data.frame(state= states,
                        A=c(0,1, 0,1, 0,1, 2),
                        N=c(0,0, 1,1, 2,2, NA),
                        D=c(0,0, 0,0 ,0,0, 1))
statedata
qmat <- qplus(statedata, death= "death")
statefig(cbind(2,2,2,1), qmat, alty=rep(1:2, c(7,8)))
@ 

The above model assumes two latent processes, amyloid accumulation in the brain,
A0 and A1,
and cognitive decline from no impairment to high, C0, C1, C2.
The premise of an HMM is that these states are not directly observed, rather
what we see are biomarkers that indicate, imperfectly, the underlying process.
The latent or ``hidden'' states operate in continuous time, so transitions in
the figure are a change in A or N, never both at once.  
Because of intermittent observation a subject might well be in A0:N0 at one
visit and A1:N2 at the next, but the unobserved continuous process would not
have made an instantaneous multistate jump.

Here is a possible specification for a model.  
It is purposely a very general one.

<<echo=TRUE, eval=FALSE>>=
mfit <- cmsh(list(Surv(time, death) ~ male,
                 0:death ~ iage,
                 A(0):A(1) ~ apoe + male + ns(iage,4)/ common,
                 C(0):C1(1) + C(1):C(2) ~ iage + cmc),
            marker = list(C:dx ~ 1/ multinomial(pattern= pmat),
                          C:memory~ 1 /logistic,
                          C:memory~ practice/ logistic(param=mean) + common,
                          A(1:2):centiloid + A(1:2):sqrt(p.tau181) ~1/gaussian),
            data= dementia, id=ptnum, qmatrix = qmat, 
            statedata = statedata)
@ 

Full estimation includes 13 transition rates (arrows), along with the 
relationship
of 4 biomarkers (dx, memory, centloid, and p.tau181) to the underlying
states. It is a complex model, with a lot of parameters, and the 
specification is also complex. The statedata data set makes specification a bit 
easier by setting up aliases, e.g., A(0) is shorthand for A0:C0, A0:C1 and
A0:C2. 
The data set has a row per state, in the same order as they are found in
the transition matrix \code{qmat}.  It's first column must be a variable
named ``state'', the other columns provide aliases.

The specification for the 13 transitions rates has the same form as in the
coxph function.  Each of the rates is
 modeled as $\exp(\beta X)$, in the
same manor as a Cox model, each transition has it's own equation.
The formula argument, the first argument of the cmsh function, is a list
whose first element is the default formula for each transiton, subsequent lines
each update the formula for selected transitions.
Here is a sample from the above:
\begin{itemize}
  \item All 6 transitons to death are of the form \code{~ male + iage}; each 
    has separate coefficients
  \item The A0C0:A1C0, A0C1:A1C1 and A0C2:A1C2 transitions, the three vertical
    arrows in the figure, have the form \code{~ male + apoe + ns(iage,4)};
    these three transitions have the same coefficients.
  \item The four C transitions (horizontal arrow) have form \code{~ iage + cmc}
\end{itemize}
Behind the scenes the A(0):A(1) specification translates as any valid transition
from a state where the A column of statedata is 0, to one where the A
column is 1.  
Going from row 1 (A0.C0) to row 6 (A1.C2) formally satisfies the A(0) to A(1)
pattern, but is not one of the valid transitions, per qmat.

The marker specification is also a list of formulas. The 
\code{C:memory ~ /gaussian}
specification states that each of the true cognitive states C has an expected
distribtuion of memory scores which follows a logistic distribution: true
state C(0) gives rise to logistic($\mu_1$, $\sigma_1$) memory scores,
true state C(1) gives rise to logistic($\mu_2$, $\sigma_2$) memory scores,
and true state C(3) to logistic($\mu_3$, $\sigma_3$). This gives rise to
6 linear predictors in the model, one for each mean and log(std) value.
Memory scores tend to be systematically better when the same test is 
readministered a second time, this practice effect is often coded as a factor
with levels of 0, 1-2, 3+ for the number of prior tests.
The second memory line states that the linear predictors for $\mu_1-\mu_3$
will also include the practice effect, and that this effect is assumed to
be the same size for all 3 latent states.
(An assumption that is open to challenge; a C2 subject might not remember prior
test exposures as well.) 

A latent state of none/low amyloid, A(0), is assumed to lead to 
gaussian distributions for centloid values and for log(tau), 
PET based biomarkers, and ditto for A(1). The A(3) row, death, will never
correspond to a PET measurement.
This leads to 2 markers * 2 state groups * 2 parameters = 8 linear predictors.
In this case each LP is simply an interecept.
The diagnosis variable is categorical, leading to a multinomial distribution
for the state:marker combination. The pattern argument will be illustrated in
a later example.


The first major difference between the MSH and HMM models is that observations
on each state come from interval censored data, also known as panel data. 
That is, subjects visit at regular intervals and undergo a panel of tests.
We will know their state at a given test date, but not the time at which the
study participant transitioned to that state.  This leads to a more complex
likelihood than a MSH model, but also more realistic for data such as this.

The second difference is that an HMM treats the states as latent factors.
The model will have standard covariates, things
like age, sex and genotype which affect the transition rates from state to
state, and also reporter or biomarker variables on the states themselves.
In this case, we might have the following misclassification matrix.
\begin{centering}
  \begin{tabular}{ccccc}
   & \multicolumn{4}{c}{Observed} \\
True & CU & MCI & dementia & death \\
C0   & $1- p_1$& $p_1$ & 0 & 0 \\
C1   & $p_2$ & $1-(p_2 + p_3)$ & $p_3$ & 0 \\
C2   & 0     & $p_4$ & $1-p_4$ & 0 \\
death& 0 & 0 & 0 & 1
 \end{tabular} \end{centering}

We have been careful above to use one set of labels for the true states
(C0, etc) and another for the observed states.  
In many cases a user will be tempted to use the same labels for the true
underlying state and for the clinical observation: this is a good way to
generate confusion, and we recommend that you do otherwise.
Death is a special state, it is not interval censored as we
know the exact death date, nor is it a latent state since it is observed
without error.

A primary reference for the material is Christopher Jackson's excellent manual 
for the msm package \cite{Jackson16}.
Others that I found particularly helpful were a web page by Nikolai
Shokiriv \cite{Shokhirev}, Satten and Lingini \cite{Satten96} and
computational details from Kalbfleisch and Lawless \cite{Kalbfleisch85}.

Per Shokhirev there are 3 canonical problems for HMM models.

\begin{enumerate}
  \item Given the model parameters, compute the probability of a particular
    output sequence.  This is solved by the Forward or Backwards algorithms.
  \item Given the model parameters and an output sequence, compute the
    most likely path for the hidden states (the true but unobserved path).
    This is solved by the Viterbi algorithm.
  \item Given an output sequence, find the most likely set of model
    parameters.  This is solved by the Baum-Welch algorithm.
\end{enumerate}
We are focused on problem 1: an underlying search algorithm will choose
parameters $\beta$, which map to rates, which in turn lead to a likelihood
value.  The search algorithm uses this to find an MLE.
Many references, e.g. Wikipedia, focus only on problem 2 the exclusion of
the others.  This led to much early confusion for this author, e.g., 
the Viterbi algorithm involves a forward recursion and earns a 'forward'
label as well.
It might look like 3 is our target, but that would only be true if there 
were no covariates and we were directly estimating the rates.

Further math and computational details are found in a mathematical vignette.

\section{Design}
Specification of an HMM model is complex, because the model is complex.
We need to specify
\begin{itemize}
  \item The underlying Markov model: the states, state names, and the
    allowable transitions.
  \item Which covariates apply to each transition, and which of these
    transition/covariate pairs share a coefficient.
  \item For each marker $y$  transmission function $P(y |s)$ needs to be
    defined, which provides the distribution of $y$ given the true state $s$.
    (Death does not need a transmission function).
  \item The initial probabilities, whether these should be estimated,
    and if so what covariates to use.
  \item Initial values for the coefficients and specification of which of them,
    if any, are fixed.
\end{itemize}


One of the attractions of the HMM likelihood is that reporter
variables need not all be present.  In the MCSA for instance, visits are
scheduled every 15 months, but PET imaging is only gathered on a subset,
and for many of those PET is done every 30 months. For the HMM likelihood there
is no need to ``fill in'' those other measurement using imputation or 
other special
missing value computations, etc.  Each measured reporter adds to the likelihood
and, those which are not measured at this visit don't.  Simple.


\section{Time dependent covariates}
Though markers for the states can be observed intermittently, covariates
that affect the rates can not be missing, the same restriction that applies
in a MSH model.  
If cerebral vascular disease (CeVD) were the state, for instance, with an 
intermittently observed predictor of the disease rate such as systolic blood
pressure, the SBP would commonly be filled in wrt continuous time by using 
the most
recently measured value, also called last value carried forward; see the 
\code{lcvf} function. 


There are 3 kinds of states in the hmm fitter:
latent states, which are not observed precisely but for which we have observed
but imperfect \emph{markers} of the current state, interval censored states,
where the
state a subject is in at the observation time is certain, but not when they
entered the state, and exact states where both the state and its time of entry
is known. Both interval censored and exact states should appear as levels 
in the in the second argument to Surv, \code{cstate} above,
which must be a factor whose first level corresponds to ``no observed state
at this time'' and remaining levels will match the state labels in the
$Q$ matrix. (Common labels for this first level are ``censor'' or ``none'').
Death is the most common exact state, so much so that ``death'' is the default 
value of the \code{exact} argument, and so we could have omitted it
from the above call.

The above fits have no latent states, so the observed outcome is captured in
the Surv argument.  
The formula argument specifies the models for the between state transitions,
and has the same form as in the coxph function of the survival package.
It is a list where the first formula is the default, the left hand side is the
response and the right the covariates.  Further elements of the list have
the form of one or more state:state transitions on the left and covariates on
the right.  Behind the scense there is a formula for each transition, each
starts as the default and is modified by each later addition or subtraction,
using the same logic as \code{update.formula}.  
The \code{common} option states that the specified transitions share a
common \code{sex} coefficient.
The result of the formulas is captured in \code{cmap} component of the fit,
each positive integer is an index into the overall coefficient vector.
The following are valid specifications of transitions:
\begin{itemize}
  \item \code{0:death}, \code{0:state('death')}, \code{0:4}: transition from
    any other state to death.  Illegal transition are silently removed, i.e.,
    this does not include death:death.
  \item \code{c(1:3):4}, \code{state('no CAV', 'mild/mod', 'severe'):death}:
    same as the above
  \item \code{''no CAV'':''mild/mod'' + ''mild:mod'':''severe''}:
    same as \code{1:2 + 2:3}
\end{itemize}
    
The default for cmsh is to not maximize, returning the result at
the initial parameters.  The second two calls use what we have found to be
the most robust option for general practice, which is based on a 
Levenburg-Marquart algorith along with a trust region, and uses the outer
product of the score vectors $U_i$ per subject as an approximate Hessian
matrix. 



\section{Example data}
We will use the included \code{dementia} data set as a running example for
the remainder of the vignette.  This data set is a simulant, based on data
from the Mayo Clinic Study of Aging which was used in the analyses of 
\cite{Jack22} and \cite{Jack25}.
The MCSA is an age and sex stratified sample of subject from Olmsted County,
Minnesota.  After recruitment, subjects are invited to return for a study
visit every 15 months, with the goal of understanding the evolution of
cognitive decline along with various markers of the pathology that underlies
such decline.  
The \code{dementia} data set focuses on two processes. 
The first is cognitive loss, as
measured by clinical assessment, cognitively unimpaired (CU) versus
mild cognitive impairment (MCI) versus dementia, a memory score based on a
battery of cognitive tests, and hippocampal volume, a measure the of neural 
loss that presumably underlies cognitive decline.
The second is progression of amyloid and tau deposition, known
to be part of the Alzheimers disease pathway, direct PET imaging of amyloid and
tau in the brain, and a putative blood based biomarker P-tau181 of amyloid load.
(Whether amyloid and tau are causative the disease or only convient markers
process is vigorously debated.)
Death is a competing risk for both processes.

\section{Multi-state hazard model}
We first fit a multi-state hazard (MSH) model, using functions from the
survival package. This will help make the data clearer, along with the
differences between MSH, interval censored and HMM models.
The MSH fit will partially reprise the analysis in \cite{Jack22}, 
which fits the simple
3 state model of not demented (ND)/dementia/death on age scale, with sex,
 amyloid, CMC, and APOE positivity as covariates.

The choice of time scale is a critical step in the analysis plan. One useful
way to think about this is as a choice of which covariates to explicitly
model and which covariates to adjust for by matching. 
The advantage of matching on some covariate $x$ is that it provides the best 
possible adjustmement: it works independently of the true functional form of the
relationship of the relationship $y = f(x)$.  A disadvantage is that we do not
get a p-value, or an estimate of $f$.  
In epidemiology studies of chronic disease, 
matching on age and sex is often a natural
choice: we already know that rates rise with age and differ by sex, no one
needs a p-value ``proof'' of this, and a given study is usually focused on other
questions. 
In a simple Cox model or a multistate hazard (MSH) model, the partial likelihood
is based on matching. If time-since-enrollment is used as the underlying scale
then for an observed dementia in subject ``Smith'', say, at 249 days post 
enrollment, Smith is compared to all others who were also alive and at 
risk at 249 days post enrollment, using their appropriate covariate values 
at that time.
If age is used as the time scale and that same event happened when Smith was
30104 days of age (approx 82y 8m), the matched group will be all those who were
active in the study at 30104 days of age, some of whom might have been enrolled
in the study for a month while others had been active for a decade.
A general rule of thumb for the Cox model is to match on the time variable
that is the most impactfull and/or difficult to model, and model the easier
and/or less impactful time scale. 
I often tell the researcher ``Assume you want to predict a subject's risk over
the next year, and you can have only one of age, time 
since first diagnosis of desease, or time since enrollment in the study to
guide you.  Which would you choose?''


Both death and dementia rates rise rapidly with
age, death rates are approximately log-linear from age 50 onward 
but dementia rates have a different form (a later but more precipitous rise).
The MCSA is is an age and sex stratified random sample from a defined population,
enrollment ages range from 50 to 90 and follow-up of up to 16 years.  
The data thus has observations from 50 to 100+ years of age, over this range 
population death rates increase by approximately 150 fold, e.g.,
\code{survexp.mn[100,,'2020']/ survexp.mn[50,,'2020']}.
If modeling the effect of age on the hazard one really 
needs to get it right, blindly adding \code{+ age} the the formula will not
suffice, since even a small error can cause effects of interest, such as the
1.3--1.4 fold effect APOE genotype, to be completely lost in the resulting bias.
On the other hand, one would expect little clinical effect for time since
enrollment, which is the time since a subject was randomly selected from the
master age/sex registry of Olmsted County residents for an invitation letter.
This makes age the natural time scale for an MSH model.

A model using time from enrollment as the time scale would include age as
a covariate; similarly a model using age as the time scale should include
time-since enrollment as a covariate. 
Based on prior experience we have coded this as a categorical time-dependent
variable of 0-1 years, 1-4, and 4+ years post enrollment, with 4+ as the
reference level.
The dementia data set included in the package is modeled on the actual MCSA
data, results will not match any analyses using the actual MCSA sample but
will often be similar in magnitude.  


\bibliographystyle{plain}
\bibliography{refer}

\end{document}




