\documentclass{article}
\usepackage{amsmath}
\title{Censored multistate hazard (MSH) models}
\author{Terry Therneau}

\addtolength{\textwidth}{1in}
\addtolength{\oddsidemargin}{-.5in}
\setlength{\evensidemargin}{\oddsidemargin}
\newcommand{\code}[1]{\texttt{#1}}

%\VignetteIndexEntry{Censored multistate hazard (MSH) models}
%\VignetteEngine{knitr::knitr}
%\VignetteEncoding{UTF-8}

<<setup, echo=FALSE>>=
library(survival)
library(icmsh)
library(msm)
library(knitr)
opts_chunk$set(tidy=FALSE, fig.keep='none',
               fig.path='compete',fig.width=6,fig.height=4)

options(continue="  ", width=60)
pdf.options(pointsize=10) #text in graph about the same as regular text
table2 <- function(...) table(..., useNA = "ifany")
options(show.significant.stars = FALSE) # be statistically intelligent
palette("Okabe-Ito")
@ 

\begin{document}
\maketitle

\section{Introduction}
The primary function of this package deals with interval censored data
from a multi-state hazard (MSH) model, where the states are either known, 
latent or a mixture thereof. e.g., 
An MSH model where all the states is known as a hidden
Markov model since the true states are not directly observed, they are
 ``hidden''. 
In the wikipedia entry on HMM for instance, they refer to $X$ as the
states, $Y$ the observed values and $f(Y|X)$ as the emission probability
(or $P(Y\in A|X)$ for discrete $Y$).
Nearly all of our clinical models have one known state, i.e. death,
so none of our examples are a pure HMM. 
We use the terminolgy of states $S$, some of which may be latent and correspond
to $X$ above, markers which corresponds to $Y$, covariates, which are
variables that affect either the transition rates from state to state, 
the relationship between a marker and states, or initial state for each
subject, and last a matrix of coefficients $\beta$.
Then $\eta = X\beta$ is a matrix of linear predictors, each column mapping to
some aspect of the model, e.g., a particular transition rate.  
Here $X$ is the standard $n$ by $p$ design matrix of statistics, one row
per observation, containing intercept, covariate, spline term, etc columns.

Models for the latent processes underlying cognitive decline, e.g., neural
loss or cerebral vascular compromise, have been a primary driver of this work 
and so will be an important focus in this vignette.
However, the simpler interval-censored models are both of interest themselves
and a useful stepping stone in the theory, so will appear first.

We should state at the outset that these problems are also the target of
the \code{msm} package, so why create a new one?
There are currently four primary differences between the two packages.
\begin{enumerate}
  \item From a user point of view, icmsh is designed to have similar structure
    and code to the survival package.  The two packages share a 
    primary author, who (of course) finds this style more natural.
  \item For more complex data, like the dementia example found further below in
    this vignette, the underlying optimization functions in msm were very often
    not successful at finding the maximum, and very slow when they did succeed.
    Expermentation with more robust approaches, along with a need for these 
    models within our dementia research program, 
    have been the primary drivers for the icmsh package.  
  \item Follow-up summaries of the model, e.g., mean time in state, are more
    fully fleshed out in the msm package.
\end{enumerate}
As a user, 1 and 2 might recommend icmsh, while item 3, a longer history, and 
a deserved reputation for reliability would recommend msm.  
We emphatically do not claim that icmsh is superior. Use what works for you.
Christopher Jackson, the author of msm, has provided invaluable feedback
about techincal aspects of the models, along with comments about fits and issues
with particular data sets; both of which have been a key to the success of this
endeavor.

\section{Data}
The icmsh functions use a different shape
of input data than the multistate survfit and coxph functions in the survival
package.
The survival functions use data that has been cast into the counting process
form:
\begin{itemize}
  \item Each line has a subject id along with a time interval (t1, t2] to which
    this observation applies.
  \item Covariates apply over the entire interval, from start to finish,
    likewise for stratification variables, if present.
  \item Outcomes occur at the end of the interval.
\end{itemize}
The data for icmsh should be in \emph{timeline} form.
\begin{itemize}
  \item Each line of the data has a subject id, along with a time value
  \item Other variables on the line are information that was measured or
    known \emph{at that time point}
\end{itemize}

A timeline data set is actually more natural in the sense that it mimics the 
way in which data is gathered. 
It also may be easier to create, since one can use a wider variety of R tools.
For ordinary survival, however, a Kaplan-Meier say,
data in timeline form requires two observations per subject:
the first observation at time 0 will have baseline covariates along with a
status of alive, with a second
observation at the time of death or last follow-up will have the status at that
time point (alive/dead).
This is different than the traditional way that survival data is coded,
i.e., a single observation with a time/status variable pair.
The multistate format for the survival package evolved out of simple survival
and so retains that instance as a special case, i.e., one line per subject
for the simple cases of alive/dead or competing risks.

This second observation is that a timeline dataset will have many missing 
values, e.g., blood pressure would not normally be known on the day of death,
 especially if death date is obtained from other sources.
One consequence is that the usual first step of other modeling functions such
as \code{lm} or \code{coxph}, i.e., to remove any data row that contains missing
values, is not taken by the icmsh function.  The handling of missings
is more nuanced.

\begin{figure}
<<nafld1, echo=FALSE>>=
nstate <- c("0MC", "1MC", "2MC", "3MC", "death")
nmat <- matrix(0, 5, 5, dimnames=list(from=nstate, to=nstate))
nmat[1, 2:5] <- c(1, .6, .6, 1)
nmat[2, 3:5] <- c(1, .6, 1)
nmat[3, 4:5] <- nmat[4,5] <-1
statefig(rbind(4,1), nmat, alty=c(1,2,1,2,2,1,1,1,1))
@
 \caption{Observed transtions in the NAFLD data}
 \label{fig:nafld1}
\end{figure}
 
In interval censored multistate data, the subjects may be observed to be in
some state $s$ at time $t$, but the the time of entry to that state is unknown.
When there is interval censoring, the user will need to create a map of
the valid transitions, as the underlying code is not able to do so with
assurance.  For example consider the data for the NAFLD study, found in 
the survival package.  
Subjects were retrospectively categorized into one of 4 states at each office
visit, with respect to the number of metabolic comorbidities (MC) that 
they had accumulated to that point; the three MC of interest are
diabetes, hyperlipiemia, and hypertension.
Figure \ref{fig:nafld1} shows the observed transtions.
A given subject might have a multi-year gap between two office visits,
leading to the accumulation of multiple MC in the interim;
these observed transitions are drawn as dotted lines in Figure \ref{fig:nafld1}.
The true transition matrix, which would be used as input 
to the hmm function will omit the dashed lines;
it has zero for transtions which do not actually occur (biologically).

In this data set the 1MC state is interval censored: for a subject who had
none of the three conditions at their initial visit at age 56, say,
and 1 MC observed at a visit 2 years later,
we do not know exactly when the condition arose in that interval.
For almost all interval censored data sets there is at least one state which
is not interval censored, i.e., death.  

Contrast this to simpler multi-state hazard (MSH) model as fit by coxph, where
the recorded times are taken to be the actual transtion times.
The non-parametric MSH of coxph is a model for observed \emph{transitions},
and so so must account for the dashed line transitions (we observed 0MC:2MC
transitions.)
The icmsh is a model for observed \emph{states}. 
Censoring marks another difference between the two models.
With respect to the likelihood and predicted curves, in the MSH model fit
by coxph a subject is assummed to still occupy the state of their most recent 
transtion until proven otherwise, e.g., observation of 
1MC at 3 years and censored at 10 implies 1MC at 10: there is an implicit
assumption that all transitions are observed over the time interval.
In an interval censored MSH, censoring means only ``not dead at this time''.
A subject who is 1MC at year 3 and censored at 10 could be in any of the
1MC, 2MC, or 3MC states at that later time.

Formally, the HMM code treats censored as ``not in any state which is both
exact and absorbing''. 
An exact state is one for which the time of entry to the state is known
precisely, i.e., not interval censored. The list of exact states is 
provided by the \code{exact} argument; death is the most common example.
Absorbing states can be inferred from the transitions matrix.
It is possible to have an exact state which is not absorbing, an example is the
surgical resection state in Crohn's disease \cite{Therneau2000}. 

\section{Interval censored data}
\subsection{Colon cancer trial}
The \code{colon} data set in the survival package contains the results of
a trial of three treatments for stage B/C colon cancer.
This is a simple 3 state model of entry, progression, and death.
The data set is organized with 2 rows per subject, the first containing the
progression outcome and the second the death outcome.
As a first step, however, we need to decide what to do with the 5 subjects
for which progression and death were recorded on the same day.
There is nothing wrong with this, per se: the author has for instance
had studies where progression was discovered at autopsy, and one might
reasonably expect an interval censored model to accomodate it.
However, it has been our experience that ``observation'' of two states on the 
same day is nearly always a data creation error, and the \code{icmsh} routine
currently flags it as such.
To resolve the conflict we will shift those progressions one day earlier.
(Or even .001 day if one wants to be fussy.)
Also beware the two for whom their progression date is also their last 
follow-up time, so as not to add a superfluous ``censoring'' row at the end.

<<colon1>>=
temp1 <- subset(colon, etype==1) # progression
temp2 <- subset(colon, etype==2) # death
ties <- (temp1$time==temp2$time & temp1$status==1 & temp2$status==1)
temp1$time[ties] <- temp1$time[ties] -1 

# Make the timeline data set, we will use only a few of the predictors
#  The baseline data can use the row for either etype=1 or 2: the covariates 
#  are the identical
baseline <- subset(temp1, , c(id, rx, sex, age, node4, extent))
baseline$time   <- 0
baseline$status <- -1
prog <- subset(temp1, status==1, c(id, time, status)) # progression
dfu  <- subset(temp2, temp1$status==0 | time > temp1$time, 
               c(id, time, status)) # death or last fu
dfu$status <- dfu$status *2  # recode as 0/2
temp3 <- merge(baseline, prog, all=TRUE)
cdata <- merge(temp3, dfu, all=TRUE)
cdata$status <- factor(cdata$status, c(0, -1, 1, 2), 
                       c("censor", "stable", "progression", "death"))
subset(cdata, id<4)
@

Subject 1 has both progression and death, subject 2
is censored without progression at 3087 days.

One of the necessary conditions for a valid model, per underlying counting
process theory, is the concept of a predictable process.
In essense, an outcome observed at time $t$ cannot depend on any predictors
measured at or after time $t$. 
The hmm function enforces this: any observed outcome on a given line of data is
predicted using information from prior rows of data.
One consequence is that prediction covariates on the final row for a subject 
have no impact. 
A second action within hmm is to use the most recently observed value for
any predictor; it is not necessary to fill in the values for treatment, age at
entry, etc in every row of the data set.
It is a bit of a semantic argument whether each row of a timeline data set 
should contain only values \emph{measured} at that time or all
values \emph{known} at that time, i.e., whether fixed covariates like sex
should be propogated across all rows. 
The hmm function is happy with either, and more capable data set creation tools
than the basic R merge used above may well fill these in. 

As a first look compute the transition matrix.
Then compute the probability in state and cumulative
hazard curves. The survival routines can accept timeline data via
the \code{Surv2} operator.

<<coloncount>>
i1 <- duplicated(cdata$id, fromLast=TRUE)   # all but last obs
i2 <- duplicated(cdata$id)                  # all but first obs
with(cdata, table(from=status[i1], to=status[i2]))[-1,]

aj1 <- survfit(Surv2(time, status) ~ 1, cdata, id=id)
plot(aj1, col=1:3, xscale=365, lwd=2,
     xlab="Years post randomization", ylab="Current state")
legend(400, .54, c("Entry", "Progression", "Death"), lty=1, lwd=2, col=1:3,
       bty='n')
plot(aj1, cumhaz=TRUE, col=1:3, xscale=365, lwd=2,  
     xlab="Years post randomization", ylab= "Cumulative Hazard")
legend(1500, 2, c("Entry:Progression", "Entry:Death", "Progression:Death"),
       col=1:3, lwd=2, lty=1, bty='n')
@ 

In this study about 46\% finished observation still in the stable state, both
death and progression was observed for 45\%.  Only a small number died without
progression (38) or were still in the progression state at follow-up.
The cumulative hazards at 8 years are about .7, .1 and 4 for the transition
rates of entry to progression, entry to death and progression to death,
which provide reasonable starting estimates for the baseline hazards of the
interval censored fit. 
Using years as the time scale will give more interpretable coefficients, so we
add that variable.

<<colon2>>=
# create the transition matrix
cstate <- c("stable", "progression", "death")
ctrans <- matrix(c(0,0,0,1,0,0,1,1,0), nrow=3,
                 dimnames= list(from= cstate, to= cstate))
ctrans
statefig(1:2, ctrans)  # visual check that it is correct
@

A transition matrix is necessary for the fit: possible transitions
are marked by 1 and invalid transitions by 0.
(The code actually allows any positive value, since the statefig routine
uses non-integer values between 0 and 2 for drawing curved connections.)

<<colon2b>>=
options(mc.cores = floor(detectCores()*.7))  # use more than 1, but not all
# Crude transitions, as a starting estimate
cdata$year <- cdata$time/365.25  # rates per year are more understandable
crude <-  c(.7, .1, 4)/8
cfit0 <- icmsh(Surv(year, status) ~ 1, id=id,  init=log(crude),
             qmatrix= ctrans, exact="death", data= cdata,
             mc.cores=2)
cfit0
@

The solution is not at all what we expected: it shows a transition rate from
entry to progression of exp(3.97) = 53, which corresponds to a median time 
to progression of log(2)/53 years or 5 days. 
The issue is that we have no intermediate values in the data: there are no
obserations of ``stable'' after entry, and so the best MLE estimate is to assume
that subjects switch immediately to the progression state.
The code iterates, increasing the stable:progression rate until the first 
progression, at 8 days, has a large estimated Pr(progression). 
The actual MLE is $\beta= \infty$, but the loglik doesn't change very much 
for rates above 3,
the figure below shows the profile likelihood, fixing the other two rates.

<<highrate>>=
beta <- matrix(0, nrow=51, ncol=3)
beta[,1] <- seq(-1, 5, length=51)
beta[,2] <- coef(cfit0)[2]
beta[,3] <- coef(cfit0)[3]
loglik <- double(51)
for (i in 1:51) {
    tfit <-  icmsh(Surv(year, status) ~ 1, id=id,  init=beta[i,],
             qmatrix= ctrans, exact="death", data= cdata, iter=0)
    loglik[i] <- tfit$loglik
}
plot(beta[,1], loglik, type='l', xlab="Coefficient 1", ylab="loglik")
abline(h=max(loglik) +2, lty=3)
@ 

Per reference 1 in the help file for the data, patients were
assessed for progression every 8 weeks for the first year, every 4 months for
the second year, and every 6 months for years 3 to 5.  To properly analyse
this data using interval censored methods data rows for each of these 
intermediate visits should be included in the study data, but this data is
not available to us.
An interesting exercise is to add psuedo observations that match
the visit schedule, and observe how the estimate behaves. 

\begin{itemize}
  \item Not yet filled in (volunteers?).  Based in the cumulative hazard plot
    the years on study effect may need to be nonlinear.
  \item Compare results and curves to a multistate Cox for the same data
  \item My expectation is almost no change in hazard ratio coefficients,
    and the time to treatment failure estimate shifted 1-2 months earlier.
  \item Message: when visits are at regular intervals, there is not a great
    deal of clinical difference between the two endpoints 
    of ``time to observed progression'' and ``time to biological progression'';
    any covariate that affects one will have a similar effect on the other.
    The analyis will reflect that.
\end{itemize}    


\subsection{CAV example}
Data from a study that monitors the progression of coronary allograft
vasculopathy (CAV) is provided in the msm package. 
CAV is a post-transplant deterioration of the aterial walls in patients who
have recieved a heart transplant. 
Make a few changes to
the data set to set it up for the hmm function, and show some summaries. 
This fit treats the CAV outcome as interval censored. 

<<newcav>>=
library(msm)
cav2 <- cav
names(cav2) <- casefold(names(cav2))  # lower case (personal preference)

# The model
cstates <- c("no CAV", "mild/mod", "severe", "death")
cqmat <- matrix(0, 4, 4, dimnames=list(cstates, cstates))
cqmat[1,2] <- cqmat[2,1] <- cqmat[2,3] <- cqmat[3,2] <- 1
cqmat[1:3,4] <- 1
statefig(rbind(3,1), cqmat, offset=.02)

#  multi-state status for Surv(), first level has to be "no event at this time"
cav2$cstate <- factor(cav2$state, 0:4,  
                      c("alive", "no CAV", "mild/mod", "severe", "death"))
table(cav2$cstate)       # no off study FU!
with(cav2, table(from= cstate[duplicated(ptnum, fromLast=TRUE)],
                 to = cstate[duplicated(ptnum)]))[-1,]
table(table(cav2$ptnum)) # number with 1, 2, 3, ... visits
@

We use a standard multi-state Surv(time, state) form of the survival
package, where the state variable is a factor such that
the first level of the factor represents ``no event at this time''.
The CAV data is unusual in that there are no censored observations, 
each interval ends in one of the 4 states.
The 622 subjects have betwen 2 15 assessments, 27\% with 2 and 21\% with 3.
The transitions table above shows the count of observed transtition pairs, a 
subject with 5 visits will contribute 4 counts to the table.
Remaining in the no CAV state accounts for the largest number of visit
pairs. As should be the case, there are no transitions from death to another
state.

As seen below, the inter-visit intervals vary widely, a situation that favors
an interval censored model.  

<<cinterval>>=
# what are the inter-visit intervals?
i1 <- duplicated(cav2$ptnum, fromLast=TRUE)
i2 <- duplicated(cav2$ptnum)
interval <- cav2$years[i2]- cav2$years[i1]
ideath <- cav2$cstate[i2]=="death" # did the interval end in death?
#between visits
hist(interval[!ideath], nclass=50, main=NULL,
     xlab="Time between consecutive visits (years)")
hist(interval[ideath], nclass=30, main=NULL,
     xlab="Years between last visit and death")
@

For interval censored data we need to specifiy the set of
valid transitions $Q$.  This is a matrix of 0/1 values, which can
also be used by the statefig routine. 
The row/column names of the transition matrix are the names of the states,
levels in the Surv object need to match these.
<<cavstates>>=
cqmat

cfit0 <- icmsh(Surv(years, cstate) ~ 1, data= cav2, id= ptnum,
               qmatrix= cqmat, exact="death")
cfit0  #msm vignette, 2.5, model 1
@

For the above model states are of two types: the
state is known at the measurment time but not when that state was entered,
and exact states, where the entry time to the state is known. These latter
are enumerated in the \code{exact} argument.
Death is the most common exact state.   
One can also have multiple exact states, one of the more common examples 
is cause of death, e.g., states of `death due to cancer' and `other death'
had been separated by the user.
The status variable in the Surv call will be a factor with censored as the
first level, followed by the states, in the same order as the $Q$ matrix.
Now add covariates.

<<cav2>>= 
cfit1 <- icmsh(list(Surv(years, cstate) ~ 1, 
                  1:2 + 1:4 ~ sex),
             data=cav2, id= ptnum, init= cfit0,
             qmatrix= cqmat)
cfit1  # msm vignette, 2.7, model 2a

cfit2 <- icmsh(list(Surv(years, cstate) ~ dage, 
                  1:2 + 2:3 ~ sex / common,
                  2:1 + 3:2 ~ sex / common,
                  0:death   ~ sex / common),  data=cav2, id= ptnum,
             qmatrix= cqmat, exact="death", init=cfit0)
cfit2  

cfit2$cmap
@ 

More complex models are specified using a list for the formula argument.
The first formula in the list specifies the response and a default set of
covariates which is used as the starting point for all transtitions.
In the above example age at diagnosis \code{dage}.
Later formulas update the formula(s) for specified transtions
\begin{itemize}
  \item line 2 of cfit1 adds sex to the formulas for none to mild (1:2) and
    none to death (1:4), but not to other transitions
  \item line 2 of cfit2 forces the the 1:2 progression
    (no CAV to mild/moderate) and 2:3 (mild/moderate to severe) to share a
    common sex coefficient
  \item line 3 of cfit2 makes the sex coefficients for the two reverse 
    transitions identical
  \item 0:death stands for any state to death. Transitions marked as 0 in
    qmatrix are ignored whenever exanding a shorthand like this, i.e., 
    a death:death transtion
\end{itemize}

The \code{cmap} component of the returned fit is the overall map between
covariates, linear predictors, and coefficients.
The final fit has 17 unique coefficients, the linear predictor for the 3:4
(severe:death) transition for example makes use of coefficients 16, 17 and 13.


\subsection{NAFLD example}
 Metabolic dysfunction-associated fatty liver disease (previously known as
NAFLD) is characterized by fat accumulation in the liver, and is linked to 
metabolic dysfunction, such as obesity, type 2 diabetes, or other signs of 
metabolic dysregulation. 
The \code{nafld1}, \code{nafld2} and \code{nafld3} data sets contain
baseline, repeated laboratory, and outcome data, respectively from a 2018 
study by Allen.

An analysis using the state space below is found in the vignettes for
the survival package.
See there for creating the counting process data using \code{tmerge}.
The states are the count of three metabolic comorbities (MC) for each
subject at a given visit: diabetes, dislipidemia, and hypertension.

<<nafld1b>>=
states <- c("0MC", "1MC", "2MC", "3MC", "death")
nmat <- matrix(0, 5, 5, dimnames=list(states, states))
nmat[1,2] <- nmat[2,3] <- nmat[4,5] <- 1
nmat[1:4,5] <- 1
nmat[1,3] <- nmat[1,4] <- nmat[2,4] <- 0.7
statefig(rbind(4,1), nmat, alty=c(1,2,1, 2,2,1,1,1,1))
@

Now create the timeline data set.
For illustration we have done this using only the functions in base R, 
but many other, more sophisticated tools can be used.

<<naflddata>>=
temp1 <- subset(nafld1, select=c(id, age, male, case.id))  #baseline
temp1$days <- 0
temp1$nafld <- 1*(temp1$id== temp1$case.id)  # marker of nafld at baseline
temp1$case.id <- NULL  # no longer needed
temp2 <- subset(nafld3, event== "diabetes") # first diabetes
temp2$days <- pmax(0, temp2$days)  # diabetes which began before enrollment 
temp3 <- subset(nafld3, event== "dyslipidemia")
temp3$days <- pmax(0, temp3$days)
temp4 <- subset(nafld3, event== "htn")       # first hypertension
temp4$days <- pmax(0, temp4$days)

# create the cumulative count, recognizing that two outcomes might be
#  discovered at the same follow-up visit
temp5 <- rbind(temp1[,c(1,4)], temp2[,1:2], temp3[,1:2], temp4[,1:2])
temp5 <- temp5[order(temp5$id, temp5$days),]
temp5$count <- 1:nrow(temp5) - (1:nrow(temp5))[match(temp5$id, temp5$id)]
temp5 <- temp5[!duplicated(temp5[,1:2], fromLast=TRUE),]

lfu <- subset(nafld1, select= c(id, futime, status)) # death
names(lfu)[2] <- "days"

ndata <- merge(temp1, temp5, by=c("id", "days"), all=TRUE) 
ndata <- merge(ndata, lfu,   by=c("id", "days"), all=TRUE) 
ndata <- merge(ndata, nafld, by=c("id", "days"), all=TRUE) 

# 3 cases: death, fu after last visit, clinic visit
tstate <- with(ndata, ifelse(!is.na(status) & status==1, 5,
                           ifelse(!is.na(count), count, 4)))
ndata$state <- factor(tstate, c(4,0:3, 5),
                      c("censor", "0MC", "1MC", "2MC", "3MC", "death"))

# table of first visit
with(ndata, table(state[!duplicated(id)]))

# table of transitions
with(ndata, table(from= state[duplicated(id, fromLast=TRUE)],
                   to = state[duplicated(id)]))
@ 

The first table above shows the state at entry, about 45\% of the
\Sexpr{nrow(nafld1)} subjects start in the 0MC state.
The second table shows observed transtions.
Since comorbidities were defined as ``any history of'', subjects
can not go backwards. 
A few subjects have a censored visit in the midst of their state
transitions, e.g., censor to 1MC. These correspond to a NAFLD diagnosis
that was not at the same visit as as a new MC addition.
For the semiparametric counting process analysis using \code{coxph}
we need to account for all of the observed transitions.
This includes the dashed lines in the figure, which arise from a visit
where 2 or 3 MC are observed that were not present at the prior visit.
Biologically, no subject will have gained two new MC at exactly the same
moment, and the interval censored analysis can will eliminate the dashed
lines: an observed transtion from 0MC to 2MC is actually two transitions
of 0MC:1MC and 1MC:2MC, but at unknown times.

<<nafld2>>=
states <- c("0MC", "1MC", "2MC", "3MC", "death")
qmat <- matrix(0, 5, 5, dimnames=list(from= states, to =states))
qmat[1,2] <- qmat[2,3] <- qmat[3,4] <- 1
qmat[1:4,5] <- 1
qmat
if (FALSE) { #there is a bug 
nfit <- icmsh(Surv(days, state) ~ age + male + nafld, data= ndata,
            id = id, qmatrix= qmat)
}
@ 


\section{Theory, pass 1}
A big difference between coxph and icmsh is how the likelihood is constructed.
The semiparametric MSH (coxph) is a model for observed \emph{transitions}, 
while the interval censored (icmsh) approach is a model for observed
\emph{states}.
The semiparametric model assumes that we see all of the transitions, up to
the point they are censored.  It uses those transition and their timings,
via risk sets, to construct estimated rates. 
These rates can the be used to compte probability in state curves $p(t)$.

Let $R(t)$ be the multistate rate matrix at time $t$.
Off diagonal element $R_{ij}(t;x) = \hat\lambda{ij}(t;x)$ contains the estimate 
transition rate between state $i$ and state $j$, at time $t$, for a subject
with covariate vector $x$.  
To normalize $R$ set its diagonal element such that row sums are 0. 
(This is just what has to be done to compute the matrix exponential, no serious
theory is involved wrt the normalization step.)
If we assume a set of time points 
$t_0, t_1, t_2, ...$ such that the transition rates are constant over each
interval $t_i \le t < t_{i+1}$ the the probability in estimate satisfies
\begin{equation}
 p(t_i; x) &= p(t_0) e^{(t_1-t_0)R(t_0;x)} e^{(t_2-t_1)R(t_1;x)} \ldots 
 e^{(t_i-t_{i-1})R(t_{i-1};x)} \label{simplehmm}
\end{equation}
where $p(t)$ is a vector with one element per state, $p_k(t)$ the probability of
being in state $k$, and $p(t_0)$ is the probability vector for the starting
state, normally all zeros with a single ``1'' corresponding to the starting 
state.
The exponential of a matrix, e.g. $\exp(R)$, is dealt with at length in the
mathematics vignette. Suffice it to say that compuation of this quantity, and
of its derivative, is more complex than the exponential of a single value
\cite{Moler78, Moler03, Mohey09}.

In the semiparametric MSH first the parameter estimates $\hat\beta$ are 
computed based on a partial likelihood, predictions $p(t;z)$ for any chosen
covariate vector $z$ are computed at the very end.
In the interval censored MSH $p(t;x)$ is computed during maximization, that is,
for each trial solution of $\hat\beta$ and every $x$.
\begin{enumerate}
  \item Compute the predicted curve $p(t;x_i)$ for each subject $i$
  \item Compare the prediction to the observed state for subject $i$, at each
    observation time $t_{ij}$ for that subject.
  \item Use this to compute an updated $\hat\beta$.
\end{enumerate}

The computation of a likelihood in icmsh is a sum over subjects, 
and each subject can be computed independently.  (We take advantage of this
and use parallel computation if possible, either set mc.cores as an
option or include it in the icmsh call.)
The algorithm for the likelihood of each subject alternates two steps.  
First step forward to a new
time point using the matrix exponential as in equation \eqref{simplehmm}.
Whenever a subject is observed, restrict their $p(t)$ by setting to 0 all of the
``states where they ain't'', i.e., all elements of $p$ except the 
observed state.
The mathematics vignette has more formal details.

\section{Partially observed states}
\begin{figure}
<<mcsa1, echo=FALSE>>=
mstate <- c("CU", "MCI", "dementia", "death")
mmat <- matrix(0, 4, 4, dimnames=list(mstate, mstate))
mmat[1,2] <- mmat[2,3] <- 1
mmat[1:3,4] <- 1
statefig(rbind(3,1), mmat)
@  
 \caption{State space model for the dementia data.}
 \label{mcsastate}
\end{figure}

The simplest extension of the simple interval censored model, and the simplest
hidden Markov model, involves a partially observed state.
An example appears in the Mayo Clinic Study of Aging, a blinded subset of which
is present in the \code{dementia} data set.
Per protocol, enrolled subjects have return visits every 15 months, at each
visit they are diagnosed as being the cognitively unimpaired (CU), mild
cognitive impairment (MCI), or dementia state, leading to the multi-state
model shown in figure \ref{mcsastate}.

Subjects who have not returned in 36 months or more are flagged for a record
review and their medical history is retrieved. (Due to the resources of the
Rochester Epidemiolgy Project, we have access to the medical records of all
participants in the county, across all providers of care.) 
From that review a status, at their most recent physician visit, 
of demented vs non-demented (ND) can be ascertained, 
but CU versus MCI cannot be distinguished.
Study visits include additional cognitive testing, which will not have been
part of a standard office visit.

The modification of the likelihood is simple.  At such a visit, if the
diagnosis is ``dementia'', then all elements of $p(t)$ for that subject, except
state 3 (dementia) are set to 0.  For a non-demented diagnosis, elements 3
and 4 (dementia and death) are set to 0, the other two are unchanged.
We treat the off study diagnosis as a \emph{marker}, our
label for an imperfect assessment of the underlying state.
The data will have three distinct outcome variables: death, observed state
at a study visit, and partial state at an ordinary office visit. 

<<dement1>>=
states <- c("CU", "MCI", "dementia", "death")
dqmat <- matrix(0, 4, 4, dimnames=list(from= states, to=states))
dqmat[1,2] <- dqmat[2,3] <- 1
dqmat[1:3, 4] <- 1
dqmat
# statefig(rbind(3,1), dqmat)  # generate the state figure

table2 <- function(...) table(..., useNA= "ifany")  # show NA in tables
with(dementia, table2(studydx, offdx))

# Create a missclassification table for the off study diagnosis
vmiss <- cbind(c(1,1,0), c(0,0,1))
dimnames(vmiss) <- list(state= states[1:3], visit=c("ND", "dementia"))

# create a state variable for death + on study
temp <- with(dementia, ifelse(is.na(studydx), 4*death, as.numeric(studydx)))
dstate <- factor(temp, 0:4, c("censor", "CU", "MCI", "dementia", "death"))


dfit1 <- hmm(Surv(age, dstate) ~ apoepos + male, qmatrix= dqmat,
             data= dementia, id = ptnum,
             marker= list(state:offdx ~0 /discrete(init=vmiss)))
@ 

\section{What is a hidden Markov model (HMM)?}
The answer to this is that HMM is a general technique, and we see the
label applied to many different problems in many different subfields.
The cmsh package addresses a particular structure, one that has been useful
in our analyses of data from the Mayo Clinic Study of Aging (MCSA).

Our models can be thought of having two levels.  Level 1 is a multi-state
hazards model, much like those addressed by multistate hazard (MSH) models
fit using the coxph function in the survival library.
Here is a moderately complex model for illustration, based on a dementia study. 
<<states>>=
states <- c(outer(paste0("A", 0:1), paste0("C", 0:2), paste, sep='.'), "death")
statedata <- data.frame(state= states,
                        A=c(0,1, 0,1, 0,1, 2),
                        N=c(0,0, 1,1, 2,2, NA),
                        D=c(0,0, 0,0 ,0,0, 1))
statedata
qmat <- qplus(statedata, death= "death")
statefig(cbind(2,2,2,1), qmat, alty=rep(1:2, c(7,8)))
@ 

The above model assumes two latent processes, amyloid accumulation in the brain,
A0 and A1,
and cognitive decline from no impairment to high, C0, C1, C2.
The premise of an HMM is that these states are not directly observed, rather
what we see are biomarkers that indicate, imperfectly, the underlying process.
The latent or ``hidden'' states operate in continuous time, so transitions in
the figure are a change in A or N, never both at once.  
Because of intermittent observation a subject might well be in A0:N0 at one
visit and A1:N2 at the next, but the unobserved continuous process would not
have made an instantaneous multistate jump.

Here is a possible specification for a model.  
It is purposely a very general one.

<<echo=TRUE, eval=FALSE>>=
mfit <- hmm(list(Surv(time, death) ~ male,
                 0:death ~ iage,
                 A(0):A(1) ~ apoe + male + ns(iage,4)/ common,
                 C(0):C1(1) + C(1):C(2) ~ iage + cmc),
            marker = list(C:dx ~ 1/ multinomial(pattern= pmat),
                          C:memory~ 1 /logistic,
                          C:memory~ practice/ logistic(param=mean) + common,
                          A(1:2):centiloid + A(1:2):sqrt(p.tau181) ~1/gaussian),
            data= dementia, id=ptnum, qmatrix = qmat, 
            statedata = statedata)
@ 

Full estimation includes 13 transition rates (arrows), along with the 
relationship
of 4 biomarkers (dx, memory, centloid, and p.tau181) to the underlying
states. It is a complex model, with a lot of parameters, and the 
specification is also complex. The statedata data set makes specification a bit 
easier by setting up aliases, e.g., A(0) is shorthand for A0:C0, A0:C1 and
A0:C2. 
The data set has a row per state, in the same order as they are found in
the transition matrix \code{qmat}.  It's first column must be a variable
named ``state'', the other columns provide aliases.

The specification for the 13 transitions rates has the same form as in the
coxph function.  Each of the rates is
 modeled as $\exp(\beta X)$, in the
same manor as a Cox model, each transition has it's own equation.
The formula argument, the first argument of the hmm function, is a list
whose first element is the default formula for each transiton, subsequent lines
each update the formula for selected transitions.
Here is a sample from the above:
\begin{itemize}
  \item All 6 transitons to death are of the form \code{~ male + iage}; each 
    has separate coefficients
  \item The A0C0:A1C0, A0C1:A1C1 and A0C2:A1C2 transitions, the three vertical
    arrows in the figure, have the form \code{~ male + apoe + ns(iage,4)};
    these three transitions have the same coefficients.
  \item The four C transitions (horizontal arrow) have form \code{~ iage + cmc}
\end{itemize}
Behind the scenes the A(0):A(1) specification translates as any valid transition
from a state where the A column of statedata is 0, to one where the A
column is 1.  
Going from row 1 (A0.C0) to row 6 (A1.C2) formally satisfies the A(0) to A(1)
pattern, but is not one of the valid transitions, per qmat.

The marker specification is also a list of formulas. The 
\code{C:memory ~ /gaussian}
specification states that each of the true cognitive states C has an expected
distribtuion of memory scores which follows a logistic distribution: true
state C(0) gives rise to logistic($\mu_1$, $\sigma_1$) memory scores,
true state C(1) gives rise to logistic($\mu_2$, $\sigma_2$) memory scores,
and true state C(3) to logistic($\mu_3$, $\sigma_3$). This gives rise to
6 linear predictors in the model, one for each mean and log(std) value.
Memory scores tend to be systematically better when the same test is 
readministered a second time, this practice effect is often coded as a factor
with levels of 0, 1-2, 3+ for the number of prior tests.
The second memory line states that the linear predictors for $\mu_1-\mu_3$
will also include the practice effect, and that this effect is assumed to
be the same size for all 3 latent states.
(An assumption that is open to challenge; a C2 subject might not remember prior
test exposures as well.) 

A latent state of none/low amyloid, A(0), is assumed to lead to 
gaussian distributions for centloid values and for log(tau), 
PET based biomarkers, and ditto for A(1). The A(3) row, death, will never
correspond to a PET measurement.
This leads to 2 markers * 2 state groups * 2 parameters = 8 linear predictors.
In this case each LP is simply an interecept.
The diagnosis variable is categorical, leading to a multinomial distribution
for the state:marker combination. The pattern argument will be illustrated in
a later example.




The first major difference between the MSH and HMM models is that observations
on each state come from interval censored data, also known as panel data. 
That is, subjects visit at regular intervals and undergo a panel of tests.
We will know their state at a given test date, but not the time at which the
study participant transitioned to that state.  This leads to a more complex
likelihood than a MSH model, but also more realistic for data such as this.

The second difference is that an HMM treats the states as latent factors.
The model will have standard covariates, things
like age, sex and genotype which affect the transition rates from state to
state, and also reporter or biomarker variables on the states themselves.
In this case, we might have the following misclassification matrix.
\begin{centering}
  \begin{tabular}{ccccc}
   & \multicolumn{4}{c} \\
True & CU & MCI & dementia & death \\
C0   & $1- p_1$& $p_1$ & 0 & 0 \\
C1   & $p_2$ & $1-(p_2 + p_3)$ & $p_3$ & 0 \\
C2   & 0     & $p_4$ & $1-p_4$ & 0 \\
death& 0 & 0 & 0 & 1
 \end{tabular} \end{centering}

We have been careful above to use one set of labels for the true states
(C0, etc) and another for the observed states.  
In many cases a user will be tempted to use the same labels for the true
underlying state and for the clinical observation: this is a good way to
generate confusion, and we recommend that you do otherwise.
Death is a special state, it is not interval censored as we
know the exact death date, nor is it a latent state since it is observed
without error.

A primary reference for the material is Christopher Jackson's excellent manual 
for the msm package \cite{Jackson16}.
Others that I found particularly helpful were a web page by Nikolai
Shokiriv \cite{Shokhirev}, Satten and Lingini \cite{Satten96} and
computational details from Kalbfleisch and Lawless \cite{Kalbfleisch85}.

Per Shokhirev there are 3 canonical problems for HMM models.

\begin{enumerate}
  \item Given the model parameters, compute the probability of a particular
    output sequence.  This is solved by the Forward or Backwards algorithms.
  \item Given the model parameters and an output sequence, compute the
    most likely path for the hidden states (the true but unobserved path).
    This is solved by the Viterbi algorithm.
  \item Given an output sequence, find the most likely set of model
    parameters.  This is solved by the Baum-Welch algorithm.
\end{enumerate}
We are focused on problem 1: an underlying search algorithm will choose
parameters $\beta$, which map to rates, which in turn lead to a likelihood
value.  The search algorithm uses this to find an MLE.
Many references, e.g. Wikipedia, focus only on problem 2 the exclusion of
the others.  This led to much early confusion for this author, e.g., 
the Viterbi algorithm involves a forward recursion and earns a 'forward'
label as well.
It might look like 3 is our target, but that would only be true if there 
were no covariates and we were directly estimating the rates.

Further math and computational details are found in a mathematical vignette.

\section{Design}
Specification of an HMM model is complex, because the model is complex.
We need to specify
\begin{itemize}
  \item The underlying Markov model: the states, state names, and the
    allowable transitions.
  \item Which covariates apply to each transition, and which of these
    transition/covariate pairs share a coefficient.
  \item For each marker $y$  transmission function $P(y |s)$ needs to be
    defined, which provides the distribution of $y$ given the true state $s$.
    (Death does not need a transmission function).
  \item The initial probabilities, whether these should be estimated,
    and if so what covariates to use.
  \item Initial values for the coefficients and specification of which of them,
    if any, are fixed.
\end{itemize}


One of the attractions of the HMM likelihood is that reporter
variables need not all be present.  In the MCSA for instance, visits are
scheduled every 15 months, but PET imaging is only gathered on a subset,
and for many of those PET is done every 30 months. For the HMM likelihood there
is no need to ``fill in'' those other measurement using imputation or 
other special
missing value computations, etc.  Each measured reporter adds to the likelihood
and, those which are not measured at this visit don't.  Simple.


\section{Time dependent covariates}
Though markers for the states can be observed intermittently, covariates
that affect the rates can not be missing, the same restriction that applies
in a MSH model.  
If cerebral vascular disease (CeVD) were the state, for instance, with an 
intermittently observed predictor of the disease rate such as systolic blood
pressure, the SBP would commonly be filled in wrt continuous time by using 
the most
recently measured value, also called last value carried forward; see the 
\code{lcvf} function. 


There are 3 kinds of states in the hmm fitter:
latent states, which are not observed precisely but for which we have observed
but imperfect \emph{markers} of the current state, interval censored states,
where the
state a subject is in at the observation time is certain, but not when they
entered the state, and exact states where both the state and its time of entry
is known. Both interval censored and exact states should appear as levels 
in the in the second argument to Surv, \code{cstate} above,
which must be a factor whose first level corresponds to ``no observed state
at this time'' and remaining levels will match the state labels in the
$Q$ matrix. (Common labels for this first level are ``censor'' or ``none'').
Death is the most common exact state, so much so that ``death'' is the default 
value of the \code{exact} argument, and so we could have omitted it
from the above call.

The above fits have no latent states, so the observed outcome is captured in
the Surv argument.  
The formula argument specifies the models for the between state transitions,
and has the same form as in the coxph function of the survival package.
It is a list where the first formula is the default, the left hand side is the
response and the right the covariates.  Further elements of the list have
the form of one or more state:state transitions on the left and covariates on
the right.  Behind the scense there is a formula for each transition, each
starts as the default and is modified by each later addition or subtraction,
using the same logic as \code{update.formula}.  
The \code{common} option states that the specified transitions share a
common \code{sex} coefficient.
The result of the formulas is captured in \code{cmap} component of the fit,
each positive integer is an index into the overall coefficient vector.
The following are valid specifications of transitions:
\begin{itemize}
  \item \code{0:death}, \code{0:state('death')}, \code{0:4}: transition from
    any other state to death.  Illegal transition are silently removed, i.e.,
    this does not include death:death.
  \item \code{c(1:3):4}, \code{state('no CAV', 'mild/mod', 'severe'):death}:
    same as the above
  \item \code{''no CAV'':''mild/mod'' + ''mild:mod'':''severe''}:
    same as \code{1:2 + 2:3}
\end{itemize}
    
The default for hmm is to not maximize, returning the result at
the initial parameters.  The second two calls use what we have found to be
the most robust option for general practice, which is based on a 
Levenburg-Marquart algorith along with a trust region, and uses the outer
product of the score vectors $U_i$ per subject as an approximate Hessian
matrix. 



\section{Example data}
We will use the included \code{dementia} data set as a running example for
the remainder of the vignette.  This data set is a simulant, based on data
from the Mayo Clinic Study of Aging which was used in the analyses of 
\cite{Jack2022} and \cite{Jack2025}.
The MCSA is an age and sex stratified sample of subject from Olmsted County,
Minnesota.  After recruitment, subjects are invited to return for a study
visit every 15 months, with the goal of understanding the evolution of
cognitive decline along with various markers of the pathology that underlies
such decline.  
The \code{dementia} data set focuses on two processes. 
The first is cognitive loss, as
measured by clinical assessment, cognitively unimpaired (CU) versus
mild cognitive impairment (MCI) versus dementia, a memory score based on a
battery of cognitive tests, and hippocampal volume, a measure the of neural 
loss that presumably underlies cognitive decline.
The second is progression of amyloid and tau deposition, known
to be part of the Alzheimers disease pathway, direct PET imaging of amyloid and
tau in the brain, and a putative blood based biomarker P-tau181 of amyloid load.
(Whether amyloid and tau are causative the disease or only convient markers
process is vigorously debated.)
Death is a competing risk for both processes.

\section{Multi-state hazard model}
We first fit a multi-state hazard (MSH) model, using functions from the
survival package. This will help make the data clearer, along with the
differences between MSH, interval censored and HMM models.
The MSH fit will partially reprise the analysis in \cite{Jack2022}, 
which fits the simple
3 state model of not demented (ND)/dementia/death on age scale, with sex,
 amyloid, CMC, and APOE positivity as covariates.

The choice of time scale is a critical step in the analysis plan. One useful
way to think about this is as a choice of which covariates to explicitly
model and which covariates to adjust for by matching. 
The advantage of matching on some covariate $x$ is that it provides the best 
possible adjustmement: it works independently of the true functional form of the
relationship of the relationship $y = f(x)$.  A disadvantage is that we do not
get a p-value, or an estimate of $f$.  
In epidemiology studies of chronic disease, 
matching on age and sex is often a natural
choice: we already know that rates rise with age and differ by sex, no one
needs a p-value ``proof'' of this, and a given study is usually focused on other
questions. 
In a simple Cox model or a multistate hazard (MSH) model, the partial likelihood
is based on matching. If time-since-enrollment is used as the underlying scale
then for an observed dementia in subject ``Smith'', say, at 249 days post 
enrollment, Smith is compared to all others who were also alive and at 
risk at 249 days post enrollment, using their appropriate covariate values 
at that time.
If age is used as the time scale and that same event happened when Smith was
30104 days of age (approx 82y 8m), the matched group will be all those who were
active in the study at 30104 days of age, some of whom might have been enrolled
in the study for a month while others had been active for a decade.
A general rule of thumb for the Cox model is to match on the time variable
that is the most impactfull and/or difficult to model, and model the easier
and/or less impactful time scale. 
I often tell the researcher ``Assume you want to predict a subject's risk over
the next year, and you can have only one of age, time 
since first diagnosis of desease, or time since enrollment in the study to
guide you.  Which would you choose?''


Both death and dementia rates rise rapidly with
age, death rates are approximately log-linear from age 50 onward 
but dementia rates have a different form (a later but more precipitous rise).
The MCSA is is an age and sex stratified random sample from a defined population,
enrollment ages range from 50 to 90 and follow-up of up to 16 years.  
The data thus has observations from 50 to 100+ years of age, over this range 
population death rates increase by approximately 150 fold, e.g.,
\code{survexp.mn[100,,'2020']/ survexp.mn[50,,'2020']}.
If modeling the effect of age on the hazard one really 
needs to get it right, blindly adding \code{+ age} the the formula will not
suffice, since even a small error can cause effects of interest, such as the
1.3--1.4 fold effect APOE genotype, to be completely lost in the resulting bias.
On the other hand, one would expect little clinical effect for time since
enrollment, which is the time since a subject was randomly selected from the
master age/sex registry of Olmsted County residents for an invitation letter.
This makes age the natural time scale for an MSH model.

A model using time from enrollment as the time scale would include age as
a covariate; similarly a model using age as the time scale should include
time-since enrollment as a covariate. 
Based on prior experience we have coded this as a categorical time-dependent
variable of 0-1 years, 1-4, and 4+ years post enrollment, with 4+ as the
reference level.
The dementia data set included in the package is modeled on the actual MCSA
data, results will not match any analyses using the actual MCSA sample but
will often be similar in magnitude.  

<<counting>>=
state1 <- c("ND", "dementia", "death")
smat1 <- matrix(0, 3,3, dimnames= list(state1, state1))
smat1[1:2,3] <- smat1[1,2] <- 1
statefig(rbind(2,1), smat1)

# The dementia data is in timeline form, our first task is to create a
#  counting process version suitable for an MSH model (coxph).
# Create rows for years since enrollment (fake data set)
first <- subset(dementia, !duplicated(ptnum),c(ptnum, age, male, educ, apoepos))
yrdummy <- data.frame(ptnum = rep(first$ptnum, 3),
                      age= c(outer(first$age, c(0,1, 4), '+')),
                      years= rep(c(0,1,4), each= nrow(first)))
                    

# first row of data, along with fixed covariates
last  <- subset(dementia, !duplicated(ptnum, fromLast= TRUE))
last$age1 <- first$age
cdata <- tmerge(first[,-2], last, id=ptnum, tstart=age1, tstop=age,
                death= event(age, death), 
                options= list(tstartname="age1", tstopname="age2"))
# full counting process form
cdata <- tmerge(cdata, dementia, id= ptnum,
                dementia= cumevent(age, dx=="dementia"),
                centiloid= tdc(age, centiloid),
                cmc = tdc(age, cmc))
c("timeline"= nrow(dementia), "unique id"= length(unique(dementia$ptnum)),
  "counting process"= nrow(cdata))

# Add in years since enrollment as a time-dependent covariate
cdata <- tmerge(cdata, yrdummy, id=ptnum,
                yearc = tdc(age, years))
cdata$yearc <- factor(cdata$yearc, c(4,0,1), c("4+", "0-1", "1-4"))

# create the event variable
temp <- with(cdata, ifelse(death, 2, ifelse(dementia==1, 1, 0)))
cdata$event <- factor(temp, 0:2, c("censor", "dementia", "death"))

check <- survcheck(Surv(age1, age2, event) ~ 1, data=cdata, id = ptnum)
check
@

Of note:
\begin{itemize}
  \item The timeline data set has one more row per subject than the 
    counting process data set.
  \item There are participants in the data set who have multiple office visits
    in the demented state.
    For the MSH model, we don't want to count these as separate instances of a
    new dementia, i.e., as a transition.  Hence the use of
    \code{cumevent}, and setting the event variable to ``dementia'' only for
    the first instance.
  \item Several participants have a diagnosis of dementia followed by a later
    MCI diagnosis, then dementia again; a few flip multiple times.
    Clearly the clinical categorization is imperfect, and our working diagnosis
    of ``first dementia'' may be biased early.  We will 
    discuss this later with HMM models.
  \item CMC and centiloid will be used as predictors of the hazard rates in
    the model, and as such need to have missing values filled in using last
    value carried forward (LVCF), which is done automatically by the tdc()
    operator.
\end{itemize}

The results of survcheck show that 543 subjects had a dementia diagnosis of 
which 469 were followed to death, another 1002 died without dementia. 
(All subjects in the data start in either CU or MCI.)
The row of zeros shows than no one had dementia after death, a second death,
or further follow-up after death, all useful checks that the data set was
correctly created.

A more interesting question is why we did not include MCI as a state. The reason
is that the study has informative drop out --- those who are beginning to
experience cognitive decline, perhaps not yet diagnosed as such, are more
likely to leave the study.  However, we have access to the ongoing medical
records of those who choose to cease active participation, and a diagnosis
of dementia can be made from review of the physician notes and diagnoses that
are part of their their standard care.
Thus, with respect to death and dementia there is not 
informative loss and \code{cfit1} below is valid.  
Accurate diagnosis of mild cognitive impairment (MCI), however, requires formal
cognitive tests, which only occur for on-study visits.
We will return to this with the HMM model.

Here is a MSH hazard model fit, results are similar to the original study.
We have categorized amyloid similarly to that paper (clgp = centiloid group).

<<mshfit>>=
atemp <- with(cdata, ifelse(is.na(centiloid),4,
                            as.numeric(cut(centiloid, c(-100, 20, 68, 500)))))
cdata$clgp <- factor(atemp, 1:4, c("low", "med", "high", "missing"))
cdata$istate <- factor(as.numeric(check$istate), 1:2, c("ND", "dementia"))
cdata$edu4 <- cdata$educ/4  # a more useful coefficient
cfit1 <- coxph(list(Surv(age1, age2, event) ~ male + apoepos + clgp + edu4 +cmc,
                    1:2 ~ male * (apoepos + clgp), 1:3 ~ yearc),
               data=cdata, istate=istate, id= ptnum)
print(cfit1, digits=2)
@ 

It is easier to see the results as a plot.
The result is shown in figure \ref{fig:mshplot}.
For the 12 groups created by the
interacting covariates, sex * apoe * centiloid group we find it easier to 
visualize these by comparing each to an overall average effect rather than 
choosing one as a reference.

\begin{itemize}
  \item With respect to the rate of dementia, the primary question of interest
    in the study
    \begin{itemize}
      \item One or more $\epsilon{4}$ alleles in the APOE gene confer a higher
        risk of dementia, and this increase is larger for females than males.
      \item There is gradation of risk across low/moderate/high amyloid levels;
        however, males do not particpate in the lowest tranche of risk.
        Low centiloid + APOE- is the largest subset of patients, so the marginal
        effect is a higher average dementia hazard for males.
      \item Each CMC condition increases the hazard ratio by about 12\%.
    \end{itemize}
    \item For transitions to death, 
      \begin{itemize}
        \item APOE and amyloid no longer play an important role.
        \item Male sex and CMC are important predictors of death, both with and
          without dementia.
        \item Education lowers the ND:death rate by 9\%, but appears to
          increase the dementia:death hazard by 13\%. The decrease in ND:dementia
          rate (though not ``significant'') along with an increase in the 
          dementia:death rate aligns with
          the popular hypothesis that those with higher education can better 
          mask early cognitive decline, making them appear to enter dementia 
          later but progress faster.
        \item The age ajusted death rate in the first year after enrollment
        is only 1/2 the rate found in year 4+.
      \end{itemize}
\end{itemize}

We have found a lower death rate in the first year of enrollment to be common
for any study that involves informed consent.  A simple explanation for this
would be that subjects who are in extremis do not sign up for research studies.

The more important estimates in a multi-state model are absolute risks:
  \item $p_k(t; x(a), s(a))$, the probability of being in state $k$ at 
     future time $t>a$, given the covariates and starting state at age $a$.
  \item $E(N_k(t); x(a), s(a))$, the expected number of visits to state $k$ up
    through time $t$, given the initial covariates and state.
  \item ${\rm sojourn}_k(t;  x(a), s(a))$, the expected sojourn time in 
    state $k$, through time $t$, given the initial covariates and state.
\end{itemize}
Though these are straightforward compuations when all the covariates $X$ are 
fixed, this
is much more difficult in the presence of time-varying covariates such as 
amyloid and will be taken up in section \ref{tdcov}.

<<contrast, echo=FALSE>>=
# This is a helper function, to compute a marginal effect
contrast <- function(fit, data, global=FALSE, weight, transition=1,
                     tol=sqrt(.Machine$double.eps)) {
    newx <- model.matrix(fit, data= data)
    if (global)  # test for all differences =0
        newx <- scale(newx[-1,], center=newx[1,], scale=FALSE)
    else {    
        if (missing(weight))  # subtract first row
            newx <- scale(newx, center=newx[1,], scale=FALSE) 
        else  { # use a weighted average
            wt <- weight/sum(weight)# use a weighted average
            if (length(wt) != nrow(newx)) stop("wrong length for weight")
            newx <- scale(newx, center= wt %*% newx , scale=FALSE)
        }
    }
    
    if (inherits(fit, 'coxphms')) { 
        # multistate model
        indx <- fit$cmap[,transition]
        beta <- coef(fit, matrix=TRUE)[,transition]
        vmat <- matrix(0, length(indx), length(indx))
        vmat[indx>0, indx>0] <- vcov(fit)[indx, indx]
        # vmat and beta are the coef and variance matrix for this transition
    } else {
        beta <-coef(fit)
        vmat <- vcov(fit)
    }
        
    test <- drop(newx %*% beta)
    V    <- newx %*% vmat %*% t(newx)
    if (global) {
        stemp <- svd(V)
        nonzero <- (stemp$d > tol)
        ctemp <- test %*% stemp$u[,nonzero]
        chi <- ctemp %*% diag(1/stemp$d[nonzero]) %*% c(ctemp)
        c(chisq= drop(chi), df= sum(nonzero))
    }
    else {
        std <- sqrt(diag(V))
        z <- ifelse(std==0, 0, test/std)
        cbind(estimate=test, std.err=std, z= z)
    }
}
@ 

\begin{figure}
<<mshplot>>=
dummy <- expand.grid(apoepos=0:1, 
                     clgp=c("low", "med", "high"), 
                     male=0:1, cmc=2, edu4= 3, yearc="4+")
count <- with(cdata, table(apoepos, clgp, male))[,-4,]
con1  <- contrast(cfit1, dummy, weight= count, transition=1)
hr1 <- con1[,1] + outer(con1[,2], c(0, -1.96, 1.96), '*')
temp <- summary(cfit1)$coefficients
cmcrow <- grepl("cmc", row.names(temp))
temp[cmcrow,c(1,3,4)] <- temp[cmcrow, c(1,3, 4)] *2  # display 2 points of cmc
hr2 <- temp[,1] + outer(temp[,3], c(0, -1.96, 1.96), '*')
hr <- exp(rbind(hr1, hr2[c(6,7, 12:15, 17:24, 26:27),]))
yy <- 31- c(1:14, 16:23, 25:30)
opar <- par(mar=c(5,7,1,1))
matplot(hr, yy, type='n', log='x', yaxt='n', xlab="Hazard ratio", ylab="")
points(hr[,1], yy, pch=19, col=rep(1:3, c(14, 8, 6)))
segments(hr[,2], yy, hr[,3], yy,  col=rep(1:3, c(14, 8, 6)))
abline(h=c(16, 7), lty=2)
abline(v=1, lty=3)
ylab <- c("F- low", "F+ low", "F- mod", "F+ mod", "F- high", "F+ high",
          "M- low", "M+ low", "M- mod", "M+ mod", "M- high", "M+ high",
          "+4 educ", "+2 CMC", "male", "APOE+", "amyl mod", "amyl high",
          "+4 educ", "+2 CMC", "year 0-1", "year 1-4", "male", "APOE+",
          "amyl mod", "amyl high", "+4 educ", "+2 CMC")
axis(2, yy, ylab, las=1, cex.axis=.7)
text(c(.4,4,4), c(24,12, 3), c( "ND: dementia", "ND:death", "dementia:death"),
     col=1:3)
par(opar)
@ 
  \caption{Hazard ratos and confidence limits for the predictors in an MSH fit.}
  \label{mshplot}
\end{figure}

\section{HMM fitter}
\subsection{data}
The \code{hmm} function allows for interval censored data and for latent
states. The combination of these allows us to accomdate the MCI state.
The data set itself needs to be in timeline format: each row has an
identifier plus a timestamp, along with all the covariates measured or
known at that time point, other covariates are NA.  

The hmm model uses a parametric baseline hazard for each transition, i.e., 
intercept, age, sex, apoe etc. appear as covariates.
Age is the most important term, which we will model as a spline for dementia
rates and (log) linear for age; like a Cox model each rate is modeled as
exp(linear predictor) as a way to constrain rates to be non-negative.
A key part of the computation is transition probability matrix
$P(s,t)$ over the time window between two visits at time $s$ and $t$, 
$\exp[(t-s)R]$ where $R$ is the matrix of rates.
If rates are constant over the time window from $s$ to $t$ this
compuataion is feasable, $P(s,t)= exp[(t-s)R]$ where exp is the matrix
exponential; if the rates vary over the window the computation is intractable
(a numerical integration that would take forever).
As a consequence our first task is to create an expanded data set with
time-dependent covariate \code{iage}, the integer ''birthday age'' for each
subject, which is the covariate that will be used as the age predictor.
Treating death and dementia rates as a step function over age is similar to how
population rate tables are organized, see for instance the human mortality
data base (www.mortality.org); 
experience in that domain has shown that it is sometimes necessary to subdivide
the first year of life, but single years suffice from there on.
One could argue for using 2 or even 5 year increments in the dementia data, 
as a way to speed
up the computation, but we have chosen the more conservative route.
It will more than double the size of the data set.

<<expanddementia>>=
# Create a dummy data set of all birthdays for all subjects.
# There are almost certainly more clever ways to do this, but the
#  brute force method below is clear and not all that slow
# Create rows for ages that are strictly between first age +1 and last age.
#  I know that all the ages are in tenths of a year.
first <- subset(dementia, !duplicated(ptnum), c(ptnum, age))
last  <- subset(dementia, !duplicated(ptnum, fromLast=TRUE), c(ptnum, age))
temp  <- lapply(which((first$age+1) < (last$age-.01)), function(i) {
    data.frame(ptnum= first$ptnum[i], 
               age= seq(from= 1+ first$age[i], to= last$age[i]- .01, by=1),
               death=0)
})
temp2 <- do.call(rbind, temp)
c("Original rows"= nrow(dementia), "Added rows"= nrow(temp2))

# Now merge it in
dement2 <- merge(dementia, temp2, all=TRUE)
dement2$iage <- floor(dement2$age)  
# also add the 'years on study' category             
tyear <- with(dement2, age - age[match(ptnum, ptnum)]) #years on study
dement2$cyear <- factor(as.numeric(cut(tyear, c(-1, 1, 4, 100))),
                                   c(3,1,2), c(">4", "0-1", "1-4"))
@ 

We now have to make a choice. Variables in the data set that will act as
markers for a hidden or latent state should be non-missing only when they
are actually observed, as the likelihood involves a probabiliy(observed marker, 
given the true state) term.
Variables that will be used as covariates in the transition rate need to be
available at all times, just as they do for the multi-state hazard model
\code{cfit1} above. For an interval censored version of \code{cfit1} missing
amyloid and CMC values will need to be filled in using most recent value
seen.  Create this version as data set \code{dement2b}.

<<dement2b>>=
dement2b <- dement2
dement2b$centiloid <- with(dement2, lvcf(ptnum, centiloid))
dement2b$cmc       <- with(dement2, lvcf(ptnum, cmc))
# create the categorical centiloid, with missing as a category
atemp <- with(dement2b, ifelse(is.na(centiloid), 4,
                               as.numeric(cut(centiloid, c(-100, 20, 68, 500)))))
dement2b$clgp <- factor(atemp, 1:4, c("low", "med", "high", "missing"))

# the 3 level outcome based on first dementia or death
dtemp <- with(dement2, ifelse(is.na(dx), 0, 1*(dx=="dementia")))
firstdem <- unlist(tapply(dtemp, dement2$ptnum, pmax))
temp <- ifelse(dement2b$death==1, 2, firstdem)
dement2b$state3 <- factor(temp, 0:2, c("censor", "dementia", "death"))
@ 

As the next part of the setup we need to describe the state space and the allowed
transitions, e.g., see the matrix \code{qmat} below, 
as this can not be deduced simply from the data.
The values of qmat are 0 for transitions that can not occur, and 1 for those
that can.
For instance, the dementia data contains many subjects that were
categorized as cognitively unimpaired on one visit and as dementia at the
next study visit (see counts below), but biologically we know that those 
subjects 
must have passed through the MCI state during the intervening period.
The hmm function itself does not know any biology, so it is necessary to
inform it that a direct CU:dementia transition is not possible.

<<dstate>>=
state2 <- c("CU", "MCI", "dementia", "death")
qmat <- matrix(0, 4,4, dimnames= list(state2, state2))
qmat[1:3,4] <- qmat[1,2] <- qmat[2,3] <- 1
statefig(rbind(3,1), qmat)

# All the observed transitions, for all subjects
indx <- which(duplicated(dementia$ptnum))
table(from=dementia$dx[indx-1], to=dementia$dx[indx])
@ 

The fact that there are observed MCI to CU pairs in the data shows that
the measurment of CU/MCI/dementia is imperfect. To deal with this
define a set of latent states C0/C1/C2 corresponding to the true cognitive
state, and treat the clinical measurment of CU/MCI/dementia as an imperfect
biomarker of the true state. 
The underlying probability model is 
$$ y = f(state) $$
i.e., a probability distribution 
of observed values corresponding to each true state.
Since the clinical measurement is categorical, this leads to a set of
3 multinomial distributions shown in the rows of table \ref{tabmulti}.  
We have made an assumption that CU and dementia diagnoses are not confused.

\begin{table} \centering
  \begin{tabular}{ccccc}
    & \multicolumn{4}{c}{Observed biomarker} \\
 True & CU & MCI & dementa & ND \\
  C0  & p_1 & 1-p_1 & 0 &  1  \\
  C1  & p_2 & 1-(p_2 + p_3) & p_3 & 1-p_3 \\
  C2  &  0  & p_4  & 1-p_4 & p_4
 \end{tabular}
 \caption{Multinomial distributions for the dementia data. At an in-person
   study visit CU/MCI/dementia is recorded, 
   a record review yeilds ND/dementia.}
  \label{tabmulti}
\end{table}

A common error is to think in terms of  state = g(observed) as the model, e.g.,
if MCI is observed the probability of CU/MCI/dementia is a,b,c;
but the statistical model goes the other direction.
 After the fit is finished one can compute the relevant
posteriors at a fixed time $t$, which will of course depend on prevalence at
time $t$.

(Note that there are no observed transitions from ND to dementia in the
data, this is structural. 
Medical record reviews were undertaken for subjects who were not yet demented
and had no study visit or prior review within approx 3 years, someone found to
be not demented is coded as ND, as CU and MCI cannot be distinguished in this
instance. However, the data entry screen for this task retains only the most
recent ND/dementia date and the ND/dementia status as of that date.)


\subsection{Fit}
<<hmmfit1>>=
# make death a factor
dement2$death <- factor(dement$death, 0:1, c("censor", "death"))

# updated state matrix, using C0, C1, C2 for the latent (hidden) states
cstate <- c("C0", "C1", "C2", "death")
qmat <- matrix(0, 4, 4, dimnames=list(cstate, cstate))
qmat[1:3,4] <- qmat[1,2] <- qmat[2,3] <- 1

# pattern matrix for the multinomial
pmat <- matrix(c(-1,1,0, 2, -1, 3, 0, 4, -1), 3,3,byrow= TRUE,
                  dimnames=list(true= paste0("C", 0:2),
                                marker=c("CU", "MCI", "dementia")))
ns2 <- function(x, ...) ns(x, Boundary.knots=c(60,90), knots=c(70, 80))
zzz
hfit1 <- hmm(list(Surv(age, death) ~ male + apoepos + clgp + cmc,
                  1:2 + 2:3 ~ ns2(iage) + male*(apoepos + clgp),
                  1:4 + 2:4 + 3:4 ~ iage,
                  1:2  ~ yearc),  qmatrix= qmat,
             marker= c(1:3):dx ~1 / multinomial(pattern=pmat),
             data= dement2, id= ptnum, exacttime="death")
@ 


This leads to the following basic components for an hmm call
\begin{itemize}
  \item A model formula specifying the time and covariates that apply to the
    transition rates. This has the same form as a MSH model fit using
    coxph.
  \item The usual data, weight, and subset arguments that go with a formula.
    Parallel to \code{lm}, \code{glm}, and other standard modeling functions,
    formula, data, weight and subset are the first four arguments.
    There is not an na.action argument, more on this later.
  \item The subject identifier.
  \item A matrix specifying the valid transitions, whose dimnames are the
    names of the states.
  \item An indicator of the death state, if any.
  \item The mapping(s) between latent states and biomarkers.
\end{itemize}

The data is specified by using standard R modeling language, illustrated
in the call below.
<<model, eval=FALSE>>=

fit <- hmm(hbind(age, cstate) ~ iage + ns(iage,3) + male, data=data2,
           subset=1:50, id=clinic, otype=otype,
           qmatrix= qmat, qcoef=qcon, rcoef=rcon, pcoef=pcon,
           rfun = hmmgauss, fitter = hmmscore)
@ 


In this example \code{age} indicates the observation time at which the 
state was observed for the subject and \code{cstate}
is a variable giving the \emph{observed} 
outcome for each observation, as opposed to the true underlying state of
the HMM.  The iage variable is integer age: for HMM models a covariate must
be constant over each time interval, so as a predictor iage moves forward
in steps at each birthday.
The otype and id variables are required, and will normally be found in 
the data set along with the
formula variables.  The data must have all of the observations for a particular
id in contiguous rows, sorted by time within subject, but the data set
does not need to be sorted by subject identifier.
The \code{obstype} variable is 0= censored, 1= usual, 2= death, 3= entry.
The \code{data} and \code{subset} arguments work exactly as in other
R modeling functions.


Having age as both our time scale and ``current age'' as a covariate can be 
confusing, 
and one needs to use two separate variable names.  
The variable on the left hand side encodes actual observation times
and so will be continuous.  The variable on the right hand
side is a time dependent covariate and will normally be an integer,
corresponding to the idea that there is a rate for age 50-51, another for
age 51-52, \ldots and each rate applies over the whole age interval. 
This is similar to US death rate tables. More importantly a stepped
variable like this is the only way that the HMM model can handle continuous
age; the matrix exponential, a key part of the compuation, is only defined
for constant hazard rates over the interval, i.e., constant covariates.
(Or more accurately, the matrix exponential can be efficiently computed for
only this case.)
How many intervals to use is up to the user: single years of age is
perhaps overkill (at least at the younger ages).
Note that the exact same model fit would ensue if the first term were
\code{hbind(time, y)} with \code{time} the time since enrollment.

In the current iteration of the package (1.x series) the hmm function acts as
more of an organizer of the computation than than a doer of the work.
This was done on purpose, to make the code a better testbed for new ideas.
The fitter argument, for instance, specifies an external program to use as
the maximizer.  We have routines that make use of the optim library, Fisher
scoring, and MCMC methods.  The default fitter simply returns the fit at 
the initial values.  

Although this made the code a good tool for exploration, setting up any given
problem can be tedious. Sections below talk about all of the individual bits.

\subsection{Transition rates}
The matrix of transition rates is specified using the \code{qmatrix}
argument, which has the same form as it does in the msm package.
If there were 6 true states then $Q$ will be 6 by 6, element $i,j$ is 0
if transitions from state $i$ to state $j$ do not (directly) occur
and a positive value if the transition is allowed.
The row and/or column names of $Q$ contain
the names of the states, which will be attached to various parts of the
printout; no dimnames corresponds to using 1, 2, 3, \ldots as the state names.
(This is discouraged).

For our 6 state model of Alzheimers the $Q$ matrix would be
<<qmat>>=
qmat <- matrix(c(0, 1, 1, 0, 0, 1,
                 0, 0, 0, 1, 0, 1,
                 0, 0, 0, 1, 1, 1,
                 0, 0, 0, 0, 1, 1, 
                 0, 0, 0, 0, 1, 1,
                 0, 0, 0, 0, 0, 1), ncol=6, byrow=TRUE)
states <- c("A-N-", "A+N-", "A-N+", "A+N+", "demented", "dead")
dimnames(qmat) <- list(states, states)
qmat
@ 
The diagonal is ignored and can contain any value.  
(Subjects can always stay in the same state, and the program
knows this.)  Zeros correspond to transitions that cannot occur
and non-zero to those that can.
The non-zero values will normally be simple indicators as in the above example,
with initial values for the transitions found in the \code{qcoef} argument.
Alternately, the elements of \code{qmat} can contain initial values for the
log of the transition rates.  Any initial values in \code{qcoef} will 
override the values in \code{qmat}.



The first three variables can be either numeric or character, depending
on whether you want to refer to the states and/or terms by number or label.
A term in the model formula such as \code{ns(x3, 3)} will expand into multiple 
coefficients but is thought of as one \emph{term} by R, and entered as
such in qcoef.  Do not forget the intercept, which is
implicit in most R models and can be referred to either as `(Intercept)'
or as term number 0.

Any row in \code{qcoef} that has coef=0 causes that coefficient to not
be optimized; it will be fixed at its initial value. 
All rows with \code{coef} set to the same nonzero value are 
constrained to share the same coefficient.  
The actual values used in the coef column for this purpose 
are of no consequence although one will normally use integers.
Initial values for the intercept terms are are taken from the 
\code{qmatrix} argument or the \code{qcoef} data frame; if present
the \code{qcoef} values override any in $Q$.

In the model given above, assume that we want a common death rate for
the first 4 states, differing for males and females, and
the spline term only for the A-N- to A+N- transition.
Below is a sample qcoef argument.
The program will automatically add the
intercepts and their initial values. 
In order to be consistent with the msm package the current code expects the
hazard (exp(coef)) in qmat and the coefficient itself in qcoef.  
I'm not sure if this is a good idea.

<<qcon>>=
states <- c("A-N-", "A+N-", "A-N+", "A+N+", "demented", "dead")
qcon1 <- data.frame(state1 = states[c(1,3,1,2,3,4,5)],
                    state2 = states[c(2,4,3,4,5,5,6)],
                    term = rep(c("ns(iage, 3)", "iage"), c(1,6)),
                    coef = 1:7)
# force equal age coefficients for death
qcon2 <- data.frame(state1 = states[rep(1:4, 3)],
                    state2 = rep("dead", 12),
                    term   = rep(c("(Intercept)", "iage","male"), c(4,4,4)),
                    coef = rep(12:14, c(4,4,4)))
rbind(qcon1, qcon2)
@ 

\subsection{Response functions}
Response functions are set up in a parallel way.
The \code{rfun} argument contains the name of the response
function, or a list of functions if there are multiple y values at
each visit.  The first response function goes with the first $y$ value
and etc.
The \code{rcoef} argument is a data frame with names of 
response, lp, term, coef and optionally init; 
the first of these is not needed if there
is a single response.
A given response function can depend on multiple linear predictors.
The term, coef, and init arguments are identical to those for qcoef.

A response function will be called with four arguments
\begin{description}
  \item[y] a vector of values $y$ of length $n$
  \item[nstate] number of states
  \item[eta] a matrix of linear predictors with $n$ rows.
  \item[derivative]  FALSE or TRUE, whether the function should also return
    derivatives of the result
\end{description}
The routine will return a matrix with $nstate$ rows and $n$ columns.
Each column refers to a single observation, and contains
$P(y_i | s_i=j)$, the probability of seeing the given $y$ if the true state
were $j$.  
The routine is not called for missing $y$ values, the parent \code{hmm}
routine has taken care of that.
If derivatives are requested then the response will have a \code{gradient}
attribute which is an array whose first two dimensions are identical to 
the return, and last dimension is the number of linear predictors.
Each ``slice'' of the array contains the derivatives wrt a single linear
predictor.

The code contains a response function \code{noerror.hmm} which treats every
response as though it were observed without error.  Using this yields the
usual Markov model rather than a hidden Markov model.
Say one has a response function with no optimized parameters, e.g., if error
rates were known a-priori.  
One way to deal with this are to write a simple function with those rates
baked in as constants; it depends on no parameters so the
the \code{rcoef} argument would be empty.
Another is to write one that depends on parameters but call
it with those parameters fixed.
An rcoef data frame for the latter would have one or more rows with
lp= 1, 2, \ldots, term=0 (intercept), coef=0 (fixed
value) and init = the desired value. 
In either test cases the parent routine is smart enough not to 
ask for derivatives.

\subsection{Starting probabilities}
The starting probability $\pi_0$ is defined in the same way as the
response functions using \code{pfun} and \code{pcoef}.
The \code{pfun} function has arguments of number of states, linear predictors,
and derivative.

\section{Optmization}
Within the code there are a few key variables.
First is the $X$ matrix which has $n$ rows and $m$ columns, and is
like any other X matrix in a modeling function.
Second is $\beta$ which has $m$ rows and $p$ columns, one for each linear 
predictor.  There is a linear predictor for each allowed transition rate,
along with those for the response functions and $\pi$.  
Some elements of $\beta$ may be constant.
The third is \code{cmap}, which has the same shape as $\beta$, and contains
parameter numbers.  A value of 0 means that the corresponding element of
$\beta$ is fixed (often at zero), a value of $k$ means that the corresponding
element of $\beta$ is taken from the $k$th parameter.
The maximum value of \code{cmap} is the number of estimated parameters,
which is also the length of the \code{coefficient} vector. 
This is the vector that the optimization routine sees.

The \code{scale} option controls centering and scaling of the variables.
If centered then the intercepts are with respect to the mean
covariate values, scaling scales them all to a standard deviation of 1.
Centering can be critical for convergence of the code, and scaling will
often be helpful.  The default for the routine is \code{c(TRUE, FALSE)}
for centering but not scaling.
The \code{scale} component of an hmm fit contains the vector of centering
values and the vector of scale values.  This can be used as the argument
in other hmm fits to ensure the same center/scale from run to run of a 
set of models.

A strength of the code (but more work for the user) is that it allows the
use of an optimizer of choice.  The routine should have \code{par} and
\code{fn} as the first arguments, and return a list containing elements
\code{loglik} and {coefficients}.
As an olive branch to the optim routine the results can also be labeled
as \code{par} and \code{value}.
The \code{mfun} argument to \code{hmm} should contain the name of the
optimizer and \code{mpar} a list of any other parameters desired by the
routine.  
When called \code{par} will contain the initial values of the parameters
and \code{fn} will by default be 'hmmloglik'.  However, any of
'hmmloglik', 'hmmgrad' or 'hmmfull', can be be used by
adding this as the \code{fn} element of \code{mpar}.  
Each of these takes a single vector of parameter values as input.
\begin{itemize}
  \item hmmloglik returns a single log-likelihood value
  \item hmmgrad returns a vector of first derivatives
  \item hmmfull returns vector of log-likelihood values, one per subject,
    along with a matrix of derivatives with one row per subject and one
    column per parameter.
\end{itemize}

\section{Constraints and penalties}
One way to create the constraints is to use the hmmpenalty function.
The primary idea is to define contrasts between linear predictors.
The arguments are
\begin{itemize}
  \item A data set with the same covariates as the fitted model, and one
    row for each target.
  \item A vector of linear predictor names, which will be matched to the
    column names of \code{coef(fit)}.  Alternately this can be a vector of
    column numbers.
  \item A set of contrasts/comparisons between the linear predictors.
\end{itemize}

For instance, suppose that we want the a:b rate to be similar to the c:d rate
for a model with multiple transitions, with age, sex, and APOE as covariates.
As our default subject choose a 70 year old male, APOE negative.  Then the
data set and linear predictors could be:
<<apoe>>=
newdata <- data.frame(age=c(70, 70), male=c(1,1), apoe=c(0,0))
lp      <- c("a:b", "c:d")
@ 
to create a contrast matrix that will be used as a penalty.

Alternatively we might want to force the rate to be increasing from age 70 to
80, in which case the data set and linear predictors would be
<<apoe2>>=
newdata <- data.frame(age=c(70, 80), male=c(1,1), apoe=c(0,0))
lp      <- c("a:b", "a:b")
@ 

A call might have two targets or a hundred, it is entirely up to the user.
The third argument creates combinations of the constraints.  For instance if
there were 4 targets we could have a contrast argument of
<<apoe3>>=
contrast <- rbind(c(1, -1, 0, 0), c(0, 0, 1, -1), c(1, 0, -1, 0))
contrast
@ 
This compares linear predictors 1 with 2, 3 with 4, and 1 with 3.
If all of the pairing are simple +1/-1 comparisons like the above then an
alternate form of the argument is allowed which is a 2 column matrix
with rows of (1,2), (3,4), and (1,3).


One reason for thinking of the constraints in this way is that the result is
invariant to any variable recoding.  A covariate can be centered or rescaled
and the predicted value is unchanged.
A second reason which is perhaps more important is that working directly 
with the
parameters can be hard.  For instance, we might want one linear rate to be 
greater than another --- but what does this mean?  Consider the figure below.
The second rate will cross the first at about age 95, but it may be larger
for all the ages we care about.  Constraints that the rate is
higher at ages 60 and 80 may accomplish what we want without resorting to 
non-linear tail behavior.
<<agefig, echo=FALSE>>=
age <- 50:90
y <- cbind(-8 + age/100, -7.55 + age/190)
matplot(age, 1e4*exp(y), type='l', lty=1, lwd=2, log='y',
        xlab="Age", ylab = "rate/100")
@ 

A last advantage is that this approach is simple to specify for non-linear
functions such as a spline.  

The result of a call to \code{hmmpenalty} is a 3 dimensional array whose 
first 2 dimensions match \code{coef(fit)} and third dimension the number of
comparisons.  Each ``slice'' is one comparison.
An array can instead be created directly by the user, if desired.
The same form is used for both the penalty and constraint arguments.
Let $C\beta$ be the set of linear contrasts after translation to the
underlying parameters $\beta$ of the maximization. 
(This is done automatically by hmm).  Then a penalty
is the addition of the square of each contrast to the log-likelihood,
formally $\beta'(C'C) \beta /2$.  
For our figure above, a penalty at age 70 adds the square of the distance
between the two curves.
(Actually the log curves, since rates are fit on log scale to avoid negative
numbers).

How should penalties be scaled?  
For penalties, a degrees-of-freedom argument would note that the likelihood
should increase by about 2 units with the addition of an extraneous
degree of freedom,
which is the basis of Akiake's information criterion.  
(Compare 2*loglik to a chi square on 1 degree of freedom).
The BIC replaces 2 with log(n).
Since rates are all on the log scale, two rates that differ by 1 unit
corresponds to a 2.7 fold change in the event rate, which is fairly 
substantial.  The penalty to the loglik in this case is $1^2/2 = 1/2$ unit.
A difference of 2 units (7.4 fold rate change) has a penalty of 2 units.
We see that an unscaled penalty does not impose a large practical constraint
from a biology point of view.  
In a small number of examples, however, it seems to be able to stop the
derivative based methods from particularly bad guesses during optimization.
When using an MCMC optimization the priors on the parameters perform the same 
function.

Constraints are handled by the minimization routines themselves.  The MCMC
code deals with them perfectly.  
The hmmscore function obeys the constraints and seems to do well, but there
is no guarantee that it will find the optimal solution.  More importantly
the approximate variance matrix that is returned is not a reliable way to 
create confidence intervals.  The optim function will ignore any constraints.

\bibliographystyle{plain}
\bibliography{refer}

\end{document}




